### ISSUE TITLE
Download Error with Patches

### ISSUE THREAD

**Issue by SolidPython2099** [blastrock/pkgj#101]
Version of firmware: 3.68
Version of PKGj: 0.22

## Steps to reproduce the issue

- Try to download any patch from the "Show Updates" section

Obtained result: Error
Download failure: failed to rename: 0x80010002
Expected result: Patch downloaded and installed

**Comment by blastrock** [comment]
Strange indeed, do you have an `ux0:patch` folder on your device?

**Comment by SolidPython2099** [comment]
Oh, stupid me. Yeah, i’ve added the folder and it works now, thanks mate! 👍

**Comment by blastrock** [comment]
Reopening this. pkgj should create that folder automatically I think
