### ISSUE TITLE
Sort by size isn't working as intended

### ISSUE THREAD

**Issue by ivan2340** [blastrock/pkgj#102]
Version of firmware: 3.67 h-encore
Version of PKGj: 0.22

## Steps to reproduce the issue

- open pkgj
- press triangle
- sort by size
- press triangle again

Obtained result: Files above ~2.5GB get shown at the top before the rest in ascending order
Expected result: Everything in ascending size order

This is probably a simple integer-overflow problem, can't seem to find the related code by myself though.

**Comment by blastrock** [comment]
Indeed there's an overflow in there, my bad, fixed in the next version.

**Comment by ivan2340** [comment]
That was quick, thank you! :)

**Comment by blastrock** [comment]
Not released yet, don't get your expectations too high ^^
