### ISSUE TITLE
download error: sceHttpSendRequest Failed: 0x80431068

### ISSUE THREAD

**Issue by azizdluffy** [blastrock/pkgj#104]
Version of firmware: 3.68 with h-encore
Version of PKGj: 0.22

## Steps to reproduce the issue

- trying to download games at 0.99 GB or more
- it stays at 0B/s , 0%
- download failure: Http error: sceHttpSendRequest Failed: 0x80431068

Obtained result: can't download games at 0.99 GB or above 
Expected result: fix the issue

[all games with 0.99 GB or more]

**Comment by blastrock** [comment]
I just downloaded a 1.3GB game successfully, seems like an internet connectivity issue. Your error is SCE_HTTP_ERROR_TIMEOUT, "Could not connect to the server in time.".

I will probably implement download resuming to allow you guys workaround these issues. I really have no idea what I can do in pkgj for that if the bug is in there...

**Comment by blastrock** [comment]
Oh wait, I just saw that you said that the download is stuck at 0%, I probably can't do anything about that. Maybe your wifi router is doing some nasty stuff...

**Comment by azizdluffy** [comment]
i don't really know, very thing works fine exept when i try to download any psvita game above 1 GB
it stucks at 0% aroud 10 sec and the error pops up

**Comment by azizdluffy** [comment]
i tried to restart the system and it works now
but i tried it before it didn't change anything.

**Comment by Animeotakunoah** [comment]
al descargar cualquier juego, cuando va por 90 % o por hay me sale un error que es (Download failure: scePromoterUtilityPromotePkgWithRif failed 0x80870004

**Comment by DatCurryGuy** [comment]
same.....

**Comment by iRuthl3ss** [comment]
same type of issue,

**Comment by Roboko22** [comment]
I have this same failure, I wouldn't mind it but it steals my memory, I used to have like 5 GB and now I only have 2.94 GB thanks to two games that failed, Like I said, I don't mind the error but I want my memory back. Any solution?
