### ISSUE TITLE
Install Game Issue

### ISSUE THREAD

**Issue by hoangdai1241** [blastrock/pkgj#105]
Version of firmware: 3.68 with H-encore
Version of PKGj: v0.22
## Steps to reproduce the issue

I got the Errow Download failure : scePromoterutuilityPromotePkgWithRif faield ... 0004 

i install the nonpdrm.skprx already even in ur0 and ux0 but i cant install the game .. how can i do :(

**Comment by blastrock** [comment]
see #74 or #97 

I can't help with that
