### ISSUE TITLE
"Http Error"

### ISSUE THREAD

**Issue by calos9999** [blastrock/pkgj#106]
Version of firmware: 3.68
Version of PKGj: 0.23

## Steps to reproduce the issue
While config.txt url is correct i'll press "show PSP games" than refresh

Obtained result: can't get list: HttpError: sceHttpSendRequest failed: 0x80431075
Expected result: normal list of games

**Comment by nighto** [comment]
This is a recurring issue as in from times to times someone reopens it. Just proposed a `README` change so this gets more attention: https://github.com/blastrock/pkgj/pull/107

**Comment by calos9999** [comment]
Thanks bro's ;)
