### ISSUE TITLE
0.23 error when refresh

### ISSUE THREAD

**Issue by igrira** [blastrock/pkgj#108]
Version of firmware: [3.68 h-encore]
Version of PKGj: [0.23]

When I try to refresh, I'm getting the next error:

ERROR
Can't get list:vector::_M_range_check:_n(which is 5) >= this->size() (which is 4)

How can I fix this issue?
Thanks!!

**Comment by blastrock** [comment]
I think there is a problem with the downloaded file. Check your URLs maybe.

**Comment by igrira** [comment]
Hi,
I checked my URLs from config.txt and there are:
url_games http://nopaystation.com/tsv/PSV_GAMES.tsv
url_updates http://nopaystation.com/tsv/PSV_UPDATES.tsv
url_dlcs http://nopaystation.com/tsv/PSV_DLCS.tsv
url_psx_games http://nopaystation.com/tsv/PSX_GAMES.tsv
url_psp_games http://nopaystation.com/tsv/PSP_GAMES.tsv


Is anyone wrong?

**Comment by AndrewNDR** [comment]
Hi, i'm getting some issues with the new version. Now it's downloading way more slower. It keeps going to 0 MB/s every second. I'm using the 3.67 H-Encore.

**Comment by cheseter** [comment]
yeah i have same issue too.
but only happen when i want to refresh the DLCS.

FW : 3.67 (H-Encore)
PKGj : v0.24
ERROR
Can't get list:vector::_M_range_check:_n(which is 5) >= this->size() (which is 4)

**Comment by XeQMuK3K4** [comment]
Same here, how i fix?

**Comment by XeQMuK3K4** [comment]
Mine woks, how? I dunno, But i keep trying, i got the error, open the vitashell delete the broken file, and try again to download, and it works, soo keep trying some moment it gonna work

**Comment by wsokc** [comment]
Strange, I did like you said it works.
Deleting the db files and kept refreshing

**Comment by XeQMuK3K4** [comment]
Took me around 2 days making it, for sure this error are a shi*

**Comment by blastrock** [comment]
I improved this error in the next version

**Comment by igrira** [comment]
Same error in v0.27

**Comment by blastrock** [comment]
You get the exact same error? No more detail?

**Comment by igrira** [comment]
I got:
ERROR
Can't get list:vector::_M_range_check:_n(which is 5) >= this->size() (which is 5)

PD: I checked the URLs
Thanks!!

**Comment by wsokc** [comment]
yes, after refresh the second time the error come out again
Version of firmware: [3.68 h-encore]
Version of PKGj: [0.26]

**Comment by wsokc** [comment]
Just an update on how i have done so far
I go to the menu
click on show psx, empty... ask for refresh
Then i refresh
works.

Goto menur
click on show psp, empty... ask for refresh
then i refresh
works
