### ISSUE TITLE
V0.23 3.68 Download Error

### ISSUE THREAD

**Issue by joeybloggs666** [blastrock/pkgj#109]
Version of firmware: 3.68
Version of PKGj: 0.23

## Steps to reproduce the issue

- Installed pkgj, worked first time.
- came up with an error while downloading a game.
- Error: "Download failure: scePromoterUtilityPromotePkgWithRif failed: 0x80870004
- Uninstalled, deleted all files, reinstalled. Still showing failure
- Will happen while downloading anything.

Obtained result: Error as described
Expected result: Download to continue

**Comment by RY0M43CH1Z3N** [comment]
It's a NonPDRM failure, please install the plugin.

**Comment by joeybloggs666** [comment]
Thank you, after some digging i managed to find it :) All fixed now, i know you probably get it alot- so thank you for replying :)
