### ISSUE TITLE
Downloads slower

### ISSUE THREAD

**Issue by AndrewNDR** [blastrock/pkgj#112]
Version of firmware: [3.67 H-Encore]
Version of PKGj: [0.24]

When downloading, the Mb, keeps dropping to 0 every second. And my connection is perfect.

There's a way to fix this?

Thanks!

**Comment by jamesghorn** [comment]
I had the same problem. Just downgrade to 0.23

**Comment by blastrock** [comment]
I have these speed drops as well, they depend on the game you are downloading. These drops occur when games contain a lot of small files and folders. In my case they are very slow to create (250ms for one directory), it may be related to sd2vita, but I don't have a sony memory card to test that.

The speed is similar between 0.23 and 0.24 for me though.

**Comment by jamesghorn** [comment]
It's not depending on sd2vita. Happens with my Sony card everytime I download something big.

**Comment by daedalion18** [comment]
Mine is doing the same thing. My vita has always been slow to download, but every second it fluctuated between 0B/s and 0.999MB/s

**Comment by blastrock** [comment]
No, it's just that the vita is slow

**Comment by jamesghorn** [comment]
But original packages and patches from LiveArea downloading way faster.

**Comment by blastrock** [comment]
I never benchmarked that. But if you are right, I just can't explain it, maybe a private API that is faster.

**Comment by pryg-skok** [comment]
I've never encounter this issue on older versions. But today I install 0.33 and encounter such drops on that packages, that definitely has no such issue previously. So it seems like new bug.

**Comment by blastrock** [comment]
@pryg-skok What is the package and the versions you tried?

@nighto Seems unlikely, the vita is slow to download because the vita is slow at everything :P

**Comment by pryg-skok** [comment]
@blastrock for example, today I've download latest psvita games tsv via "thesite" and tried to install: spelunky, salt and sanctuary, stardew valley etc. And every time I've encountered drops from 0.999 Mb/s to 0 after some time of downloading.
I've never encounter such issue before (but before I used 3.60 and 3.65 versions also, and now 3.68)

**Comment by blastrock** [comment]
I have these drops too, just tested salt and sanctuary, and they exist because these games have lots of folder in them and creating directories on the vita is slow as I explained before. This issue was there in earlier versions too and I don't think it has gotten any worse.

I don't know if this directory creation issue is due to sony or to henkaku or some other hack, but I have no idea how I can investigate that...

**Comment by pryg-skok** [comment]
I think the problem needs more info. Can anybody test pkgj on 3.60 and 3.65 versions? For example with salt and sanctuary. I can't prove it, but I definitely do not encounter such issue earlier - now it's with every title I try to download.
