### ISSUE TITLE
where to put .pkg files to install offline?

### ISSUE THREAD

**Issue by ronnyc4** [blastrock/pkgj#113]
on readme.
"To avoid downloading pkg file over network, you can place it in ux0:pkgi folder. Keep the name of file same as in http url, or rename it with same name as contentid. pkgj will first check if pkg file can be read locally, and only if it is missing then pkgj will download it from http url."
this doesn't work.

**Comment by RY0M43CH1Z3N** [comment]
Is for .tsv files, not for .pkg files.

**Comment by blastrock** [comment]
Sorry, this feature is not supported anymore, I will remove it from the README file. If you want to download files yourself, you should use NPS Browser.
