### ISSUE TITLE
Error when downloading games/DLC

### ISSUE THREAD

**Issue by 9BitStrider** [blastrock/pkgj#116]
Version of firmware: 3.68
Version of PKGj: 0.24

## Steps to reproduce the issue

Attempted to download DLC.

Obtained result: Received [Download Failure: scePromoterUtilityPromotePkgWithRif failed: 0x80871004
Expected result: Expected to download selected DLC.

Was able to grab a few DLCs before this error popped up. Opened VitaShell to reboot and this caused caused LED to blink and screen to go blank, followed by a forced reboot of the system. Restarting h-encore seems to fix it. May be a problem with PSVSD and StorageMgr get plugin.

**Comment by blastrock** [comment]
please search before opening an issue, there are like 5 other issues about the same error
