### ISSUE TITLE
Cant get list

### ISSUE THREAD

**Issue by NariIro** [blastrock/pkgj#118]
Version of firmware: [3.68]
Version of PKGj: [0.24]

## Steps to reproduce the issue

- [Install from github]
- [Open bubble that has installed on LiveArea]
- [Hit refresh]

Obtained result: [cant get list: HttpError: sceHttpSendRequest failed: 0x80431075]
Expected result: [Update and show list of games available to download]

[please make sure to add all possible details, like the title id (the 9-chars string in the left column) of the game you are talking about]

**Comment by blastrock** [comment]
Use HTTP URLs, not HTTPS.

**Comment by NariIro** [comment]
Ah see didnt know I had to setup URLs, I just downloaded it and ran it. I'll look into that. Thanks
