### ISSUE TITLE
Bug: Invalid filtering

### ISSUE THREAD

**Issue by AnalogMan151** [blastrock/pkgj#12]
The lines here cause some unintended issues: https://github.com/blastrock/pkgj/blob/master/pkgi_db.cpp#L320-L334

```cpp
pkgi_db.cpp
        if (*url == '\0' || *size == '\0')
            continue;

        if (mode == ModeUpdates)
        {
            std::reverse_iterator<const char*> rbegin(url + strlen(url) - 1);
            std::reverse_iterator<const char*> rend(url - 1);
            auto const it =
                    std::find_if(rbegin, rend, [](char c) { return c == '/'; });
            if (it != rend)
                content = it.base();
        }

        if (std::string(url) == "MISSING" || std::string(zrif) == "MISSING")
            continue;
```
According to this, if a file size is missing from the TSV file, then the entry is not shown at all. This includes games, updates and DLC.

Also, it only filters out URL's that are blank or state MISSING, but not the ones that say CART ONLY. While all of these entries have a zero file size and get filtered anyway, I think they should still be filtered by URL if you decide to allow 0 size entries to be listed. 

I know the code checks the file size against free space before installing, but perhaps you can have a message display when the file size is 0 to warn the user that free space allowance cannot be confirmed and to proceed with caution, making sure there's enough space on their card. 

PS: I think these lines could be combined as so:
```cpp
pkgi_db.cpp
        if (*url == '\0' ||  std::string(url) == "MISSING" || std::string(url) == "CART ONLY"|| std::string(zrif) == "MISSING")
            continue;
```

```cpp
pkgi.cpp
int pkgi_check_free_space(uint64_t size)
{
    uint64_t free = pkgi_get_free_space();
    if (size == 0)
    {
        // Show error about free space and confirm first
    } else if (size > free + 1024 * 1024)
    {
        char error[256];
        pkgi_snprintf(
                error,
                sizeof(error),
                "pkg requires %u %s free space, but only %u %s available",
                friendly_size(size),
                friendly_size_str(size),
                friendly_size(free),
                friendly_size_str(free));

        pkgi_dialog_error(error);
        return 0;
    }

    return 1;
}
```

**Comment by blastrock** [comment]
I didn't know about the "CART ONLY" thing.

So there are games that actually work for which the size is missing? I can skip that check indeed...

About the warning in check_free_space when size == 0, I think it's a bit hard to do. Now that downloads are done in background, such code has become very unsafe. I don't even know if it still works in its current state. I'll keep that in mind, but I don't think I will work on it in the near future.

I will make the two other fixes though, and I agree on merging the conditions like you said. Thanks!
