### ISSUE TITLE
PSP games not installing as eboot (help with setup)

### ISSUE THREAD

**Issue by TheNerdBR** [blastrock/pkgj#123]
Version of firmware: [3.65]
Version of PKGj: [0.24]

## Steps to reproduce the issue

So, I installed np_drm free to my ux0:pspemu/seplugins folder and added both ms0:/seplugins/npdrm_free.prx 1 and install_psp_as_pbp 1 to vsh.txt (in the same ux0:pspemu/seplugins folder). I don't know if this is the correct setup. The instructions are kind of vague to me, since I have no experience in PSP homebrew.

Obtained result: [The downloaded PSP games are still installed as ISOs]
Expected result: [The games should be EBOOT files]

**Comment by blastrock** [comment]
`install_psp_as_pbp 1` must go in pkgi/config.txt

**Comment by TheNerdBR** [comment]
I see. Thank you
