### ISSUE TITLE
can't get list: HttpError: sceHttpSendRequest failed: 0x80436007

### ISSUE THREAD

**Issue by ghost** [blastrock/pkgj#130]
Version of firmware: 
3.65
Version of PKGj: 
0.26

## Steps to reproduce the issue
- install pkgj.vpk with vitashell
- create pkgi folder in ux0 OR ur0 (currently in ur0, tried it with ux0 before)
- create config.txt file in pkgi folder
- fill config.txt with the following content:
url_games http://thesite/games.tsv
url_updates http://thesite/updates.tsv
url_dlcs http://thesite/dlcs.tsv
url_psx_games http://thesite/psxgames.tsv
url_psp_games http://thesite/pspgames.tsv

- I can start pkgj but it wont list any titles at all, instead, when I try to refresh I get the error from the title

Obtained result: 
In the main menu of pkgj:
No items! Try to refresh

Refreshing the list:
Error
can't get list: HttpError: sceHttpSendRequest failed: 0x80436007 

Expected result:
Game list should appear

**Comment by SmegmaChicken** [comment]
What on Earth do you mean? This still doesn't work for me.

**Comment by TheRadziu** [comment]
@SmegmaChicken 
try to click on any of those links, do they work? Do they look all right to you? I thought so. 

You need to replace those links with actual links to those files, there is a big website that hosts those and update them with new content almost on daily basis.
