### ISSUE TITLE
Download Failure: failed to rename:0x80010002

### ISSUE THREAD

**Issue by zerohot99** [blastrock/pkgj#131]
pkgj  - 0.25 
Firmware - 3.68

Error shows when downloading any updates [USA]

**Comment by blastrock** [comment]
Please fill the template. Version of pkgj?

**Comment by zerohot99** [comment]
Version of firmware: 3.68
Version of PKGj: 0.25

When I download any updates. it shows the error

**Comment by blastrock** [comment]
Update to 0.26

**Comment by blastrock** [comment]
Sorry, I was reading this by email, I didn't see your edit with the version
