### ISSUE TITLE
DB initalization error

### ISSUE THREAD

**Issue by Dragoon709** [blastrock/pkgj#134]
Version of firmware: 3.68
Version of PKGj: 0.26

## Steps to reproduce the issue
I launch the app and it's the first and only thing I see. Red letters on a black screen.

**Comment by blastrock** [comment]
Algright, I got it, you didn't configure pkgj, read the doc please

**Comment by Dragoon709** [comment]
I read through the doc and followed the setup and still get the same error. Is there a url that you can give me that will work in case that is my issue?

**Comment by nighto** [comment]
@Dragoon709 `http://thesite` is a placeholder, for security reasons we're not allowed to give you the URL. But you should be putting the URLs from that _station_ which you do _not _pay_. Make sure you remove the `s` from the `https`. Got it?

**Comment by Dragoon709** [comment]
That's exactly what I'm using and still getting the error.

**Comment by blastrock** [comment]
try 0.27?

**Comment by Dragoon709** [comment]
Didn't know 0.27 was released. I'll give it a try in a few.

**Comment by Dragoon709** [comment]
0.27 did the trick.  it gave me a different error which pointed me in the right direction to fix it.
