### ISSUE TITLE
(Sorry bout my last post) Some dlcs don't complete download 

### ISSUE THREAD

**Issue by NinjaStyle11** [blastrock/pkgj#135]
Version of firmware: 3.68
Version of PKGj: 0.26

## Steps

- I have opened PKGJ went to sort out DLC to most recent then went to the dlcs with the BLUE dot the ones that are not installed. When download reached 100% it does not complete and gives me the error of 
Download Failure: pkg integrity failed, try to download again.
The dlcs are for Persona 3 Dancing MoonNight but the dlcs that do not work are the dances performed by characters as costumes/accessories dlcs work fine.

For example PCSG01031 JPN

**Comment by blastrock** [comment]
Maybe related to #94

**Comment by NinjaStyle11** [comment]
I have no problems downloading games though?

**Comment by NinjaStyle11** [comment]
I still get the same error code? Could it be the DLCs itself?

**Comment by blastrock** [comment]
Alright, that was the bug indeed, but there was another bug ^^

Will be fixed in 0.28
