### ISSUE TITLE
Can't keep up woth the speed?

### ISSUE THREAD

**Issue by enmaai123** [blastrock/pkgj#137]
Hi,
I got 20mbps of data plan, yet it only hit about 1mb/s or lower. Sometimes it hits 2mpbs. Is there a problem on seeding a games from the source? Thanks.

Btw why delete the resume data? Its really helpful tho..

**Comment by TheRadziu** [comment]
its not an issue with pkgj, its an issue with vita itself. Hardware limitations cap the speed to around 2mb/s or (usually) less.

**Comment by blastrock** [comment]
Exactly, that's also written [here](https://github.com/blastrock/pkgj#qa) .

The resume data is deleted when resuming the download fails, so that you can try again.
