### ISSUE TITLE
When installing an update the bullet stays blue and the version is not updated in the menu

### ISSUE THREAD

**Issue by blastrock** [blastrock/pkgj#14]
This one needs quite a bit of work, it will probably wait.

**Comment by dem1980** [comment]
I have also problems with updates. They are not installed.
They are downloaded but not installed (games are always at 1.00 after update) and the blue bullet.
No problems with PSV games, and PSX games (in Adrenaline).

**Comment by blastrock** [comment]
Can you give me the title id of a game you can't update? And what makes you say that the update is not installed?

**Comment by leosabii** [comment]
Updates do not seem to install after download. The only way you can tell is that the update icon appears on the launch page right before you launch the game. If you click on the update icon, then the patch re-downloads and updates the game. It looks to me that PKGj doesn't really do anything with the patches it downloads. Thanks!

**Comment by blastrock** [comment]
For all the games I tried, they did update.

The bullet stays blue, and the update icon right before you launch the game in live area is still there. But if you launch the game and the game somehow shows its version or something in the menu, you will see it updated.

**Comment by blastrock** [comment]
Oh so that's the problem! Indeed, I didn't know about that app.db and I didn't think about checking how stuff works when doing the update manually and refreshing with vitashell.

So I guess a temporary workaround here is to refresh games through vitashell after installing an update.

Thanks for the hint, it has probably saved me a couple hours of research :)

**Comment by TheRadziu** [comment]
> So I guess a temporary workaround here is to refresh games through vitashell after installing an update.

Only if game wasn't refreshed before (so there is no livearea bubble for it). If it was refreshed already, this function wont update app_ver on its own ^^ Since app.db is regular sql database I bet you can make pkgj read extracted `/patch/gameid/sce_sys/param.sfo` (after download/extraction is complete) for new app_ver and update matching gameid with it :)

**Comment by blastrock** [comment]
Oh ok :(

I'll try to implement this as soon as I can. Thanks for your help! :)

**Comment by ronnyc4** [comment]
game update don't work
it said version 1.00 on game details
**and** if you launch the game it still ask you to update, meaning there is no update detected at all.
maybe you can tell me what game that you try that the update works? if you say it works.

thx for your work btw, this is a great app.

**Comment by blastrock** [comment]
If you start the game, and you can see the version number somewhere in the game, you will see that it is updated. I did it on various games.

**Comment by nighto** [comment]
Using newest release (0.30), pkgj shows available updates as blue circles. If I click on one of them, it downloads and supposedly installs it but it doesn't show as white circle on app and the game also doesn't recognize it.

Maybe it is because I tried downloading them before 0.30 update? What files/directories should I delete to try out fresh?

**Comment by blastrock** [comment]
You are right, I closed this bug a little to early...

What has been done is that livearea now shows the game as up to date after the update has been installed by pkgj

**Comment by nighto** [comment]
Yes. I didn't test with a new game. But for games that I have downloaded and updates that I have tried to download on previous versions of pkgj, it fails like it use to do. I wonder if it deletes automatically if it succeeds but does not if the file was already there.
