### ISSUE TITLE
Bookmarks/favorites

### ISSUE THREAD

**Issue by MNKqwerty** [blastrock/pkgj#140]
Hi!
Is it possible to add something like list of marked games? For example, if I have not enough storage, I can bookmark the game/dlc/etc. and download it later.

**Comment by eze92** [comment]
Hi, 
One question of possible enhancement , in update futures You can implements pictures the games? how the free shop of 3DS . Thanks

**Comment by blastrock** [comment]
Yes, duplicate of #7 

And I don't plan to implement game pictures anytime soon as I don't have the time.
