### ISSUE TITLE
I can not install de updates

### ISSUE THREAD

**Issue by ferro212** [blastrock/pkgj#143]
Version of firmware: 
Version of PKGj: 0.22 & 0.28

## Steps to reproduce the issue

- I start downloading the Update
- when the download just finish, nothing happen
- (the blue point beside the file still being blue)
- when i try to start the game, always the game version is 1.00

**Comment by blastrock** [comment]
duplicate

**Comment by ferro212** [comment]
But? What do I have to duplicate? And where do I have to copy that duplicate?

**Comment by blastrock** [comment]
I mean this is a duplicate issue, as I said on #142

**Comment by ferro212** [comment]
Oh Sorry, I didn't noticed
