### ISSUE TITLE
error 0x80010002

### ISSUE THREAD

**Issue by TheNewestAddition** [blastrock/pkgj#145]
Version of firmware: [3.65]
Version of PKGj: [29]

start pkgj

Fatal error: failed to load config:
sceloOpen(uxO:pkgj/config.txt) failed: 0x80010002

the application to start

I've got nothing else

**Comment by trophywhale** [comment]
Can you upload your pkgj config.txt file?

**Comment by TheNewestAddition** [comment]
I'll need steps to guide me through that, I suspect the only issue here is that I have no clue what I'm doing...

**Comment by Hyroero** [comment]
Just wanted to add i'm in the exact same boat. Got the same error so i made the pkgi folder my self, added a text document and put in 

url_games http://thesite/games.tsv
url_updates http://thesite/updates.tsv
url_dlcs http://thesite/dlcs.tsv
url_psx_games http://thesite/psxgames.tsv
url_psp_games http://thesite/pspgames.tsv

The program now launches on my vita but it cant find any games and gives me an error if i refresh

**Comment by TheRadziu** [comment]
hope you guys realize you need to replace those links with actual links to those .tsv files?

**Comment by Hyroero** [comment]
Yeah. Just figured we aren't allowed to link them here no?

After restarting and trying every combination of different urls I can find
I can get it to start loading but it errors at around 50 percent. I'm using
0.29 is it worth trying an older version?

**Comment by HardBoiledEggMan** [comment]
Try removing the 's' in https to just http.
That fixed the issue for me.

**Comment by Hyroero** [comment]
That got it loading but it never gets to 100 percent. Either hangs forever
at 50 of gives me an error...

**Comment by Hyroero** [comment]
So it gets to 100% when i refresh now but then i get "ERROR can't get list: failed to parse line vector::_M_range_check:_n(which is 10)

**Comment by blastrock** [comment]
Have you put the right url in the right place? like not mixed up the game and dlc urls for example

**Comment by fidzerone** [comment]
for me, start beginning several days ago the program run just fine. 
Start normally, database created, and of course downloads works.
Then when I trying to refresh database I got
ERROR can't get list: failed to parse line vector::_M_range_check:_n(which is 10)

I tried to uninstall (also deleted all in pkgi files, of course after backup it)
then install again, put pkgi folder and config.txt that work at 1st time
and now it wont refresh now.
So I paste .db files which I backed up last time and its works, but still, cant refresh.

One thing may triggered this, on pkgi folder it was several resume file and folder(which maked when I incidentally hit to download and cancel it).
it was DLC resume file and all of them already downloaded but still resume file on it.

thats all I'm100% sure it's not my config file triggered all this

**Comment by blastrock** [comment]
This error is not related to resume and temporary files.

Are you using the last version of pkgj?

**Comment by fidzerone** [comment]
now Im trying using latest 0.30
1st time error parsing line on destiny of spirits,  tried 2nd time I got it completely refreshed

guess the tsv files from link itsef making some problem, thanks for concern 'though

**Comment by ptrinh2** [comment]
hey guys, should I use the urls from thesite or the urls from nopaystation.com? what are differences between them?

**Comment by trophywhale** [comment]
Use nopaystation.com

One works, one doesn't exist.

**Comment by blastrock** [comment]
closing this as there are too many different issues here and they seem to be solved now
