### ISSUE TITLE
[LiveArea] New (again) app design

### ISSUE THREAD

**Issue by JesterIOS** [blastrock/pkgj#147]
Hello, again.
After 3 months I decided to go back and again with a new design of **PKGj**

So... how it looks on the **PSVITA/PSTV** (_Not bad?_):

![2018-07-17-232106](https://user-images.githubusercontent.com/30769120/42832959-1076390e-8a1d-11e8-8710-69bce6db9f0d.jpg)

### Assets:
**icon0:**

![icon0](https://user-images.githubusercontent.com/30769120/42833302-e89af95a-8a1d-11e8-9958-44caffb8f23f.png)

**startup:**
![startup](https://user-images.githubusercontent.com/30769120/42833339-0861d812-8a1e-11e8-96ba-6b3d1bdab39c.png)

**bg:**
![bg](https://user-images.githubusercontent.com/30769120/42833360-19e00f1e-8a1e-11e8-9639-2dc15fb88678.png)

### + Changed **template.xml** in archive
[PKGj livearea.zip](https://github.com/blastrock/pkgj/files/2202635/PKGj.livearea.zip)

**Comment by jamesghorn** [comment]
Иконка фуфлыжная

**Comment by nighto** [comment]
I miss the `j` on `PKGj`

**Comment by eze92** [comment]
Personalmente el actual me gusta un poco mas, lo que si se se pudiera cambiar un poco la estetica negra de la aplicacion en si por otro color que resalte mas creo que quedaria mejor pero bueno es una idea muy personal xD

**Comment by JesterIOS** [comment]
You don't like it? Okay, here's a slightly updated design with an old icon, but with a new template.xml

![2018-07-18-115035](https://user-images.githubusercontent.com/30769120/42860597-8bd46c4c-8a81-11e8-8a6b-1d193556a5ba.jpg)

[PKGj again.zip](https://github.com/blastrock/pkgj/files/2204489/PKGj.again.zip)

**Comment by blastrock** [comment]
Thanks! I like the first one. I agree with @nighto however that it would be nice to have the j of pkgj there.

I will apply your app design when I get some time.
