### ISSUE TITLE
Feature Request: Log errors on a txt file

### ISSUE THREAD

**Issue by nighto** [blastrock/pkgj#150]
I believe it could be useful to write a detailed log in case something gives error.

Ideally it would be better to have an option on Settings to activate or deactivate it, but other than that it would be super useful to understand why it is failing.

**Comment by blastrock** [comment]
I prefer improving error messages than forcing people to rely on logs. That's what I have been doing until now and the logs are becoming less and less useful.

If someone really wants the logs, I guess they will need to compile pkgj themselves.
