### ISSUE TITLE
LiveArea Concept

### ISSUE THREAD

**Issue by WesleyPolicena** [blastrock/pkgj#154]
![concept](https://user-images.githubusercontent.com/21372797/43039233-88ce440c-8cff-11e8-9035-306cd6db8b77.png)
## LiveArea PKGJ Concept

- [bubble]
![icon0](https://user-images.githubusercontent.com/21372797/43039239-acf23b4a-8cff-11e8-8392-089fda780632.png)

- [startup]
![startup](https://user-images.githubusercontent.com/21372797/43039241-b01f31f6-8cff-11e8-838e-b2cc585e2dbf.png)

- [background]
![bg](https://user-images.githubusercontent.com/21372797/43039243-b466a5d2-8cff-11e8-9bcc-dc817efe172f.png)

**Comment by nighto** [comment]
I miss the `J` on the logo. IMHO it should be `PKGJ`, not `PKG`.

**Comment by gnuton** [comment]
what about something like this in the background? https://www.deviantart.com/zhowee14/art/The-Dark-Merchant-499978144

**Comment by blastrock** [comment]
Thank you, but @jesterios is already doing the design of pkgj on #147. I will stay with his designs as I don't want this to become a contest to choose the design of pkgj and change it every two weeks.
