### ISSUE TITLE
make visible all games for higher firmware!

### ISSUE THREAD

**Issue by j0s3ph19** [blastrock/pkgj#161]
now the game for 3.61+ are playable on 3.60, but on 0.22 version you make hidden all games for higher firmware, please make visible again! (0.21 version get me SQL error) all games are playable is useless to have it still hidden (maybe make a option to set hidden or not)

thanks :)

**Comment by joseluisametller** [comment]
I support this. Now with this feature added, and the compatibility packs would be perfect!
