### ISSUE TITLE
Not able to download compatibility packages

### ISSUE THREAD

**Issue by Haruki15** [blastrock/pkgj#162]

**Comment by ToqQrrl** [comment]
This is the error message:
ERROR
failed to refresh compact db:
HttpError: bad http status: 401

**Comment by joseluisametller** [comment]
Make sure you added the following line to the config.txt

url_comppack https://gitlab.com/nopaystation_repos/nps_compati_packs/raw/master/

**Comment by eze92** [comment]
Hi what is url_comppack , which is the difference ?

**Comment by joseluisametller** [comment]
url_comppack is the param you use to tell PKGJ where to download the compatibility package list. Without this, PKGJ doesn't know where to download those pkgs
