### ISSUE TITLE
Add new menu option

### ISSUE THREAD

**Issue by symbuzzer** [blastrock/pkgj#163]
Version of firmware: [3.65 h-encore enso]
Version of PKGj: [0.31]

Can you add "L install comppack - X install - Δ menu" options bottom center of screen for games which needs comppacks, sir?

It is impossible to find L button

**Comment by joseluisametller** [comment]
Once you have the game that needs compatibility pack already installed, if you move over it on PKGJ it will say on the bottom:
L install comppack - Δ menu

**Comment by symbuzzer** [comment]
ı saw :(
