### ISSUE TITLE
It wont let me Load the PSP menu in PKGJ v 0.31

### ISSUE THREAD

**Issue by Turtlepower6899** [blastrock/pkgj#164]
Version of firmware: [insert version]
Version of PKGj: [insert version]

## Steps to reproduce the issue

- [insert the steps to reproduce the issue here]
- [insert the steps to reproduce the issue here]
- [insert the steps to reproduce the issue here]

Obtained result: [insert the result you got here]
Expected result: [insert what you expected here]

[please make sure to add all possible details, like the title id (the 9-chars string in the left column) of the game you are talking about]

**Comment by blastrock** [comment]
fill the template please
