### ISSUE TITLE
Cant Get List Fail: 0x80431084

### ISSUE THREAD

**Issue by dckiller21** [blastrock/pkgj#165]
Version of firmware: 3.67
Version of PKGj: 0.31

## Steps to reproduce the issue
-Downloaded Pkgj and set up config.text file
- Config file is set up as this :
url_games http://nopaystation.com/tsv/PSV_GAMES.tsv
url_updates http://nopaystation.com/tsv/PSV_UPDATES.tsv
url_dlcs http://nopaystation.com/tsv/PSV_DLCS.tsv
url_psx_games http://nopaystation.com/tsv/PSX_GAMES.tsv
url_psp_games http://nopaystation.com/tsv/PSP_GAMES.tsv
url_comppack http://gitlab.com/nopaystation_repos/nps_compati_packs/raw/master/entries.txt

-Installed an launched PKGj
-Refreshed 
Obtained result: can't get list : httpError: sceHttpSendRequest failed: 0x80431084
Expected result: Game list to show up

**Comment by blastrock** [comment]
This error code is not listed in the vita wiki, I don't know what's wrong.

**Comment by plxjammerplx** [comment]
Reboot your Vita and restart H-Encore after a fresh install of the update to get PKGj working normally.
