### ISSUE TITLE
download fail when screen locked

### ISSUE THREAD

**Issue by TheOneEyedGrimReaper** [blastrock/pkgj#168]
Version of firmware: [insert version]
Version of PKGj: [insert version]

## Steps to reproduce the issue

- [insert the steps to reproduce the issue here]
- [insert the steps to reproduce the issue here]
- [insert the steps to reproduce the issue here]

Obtained result: [insert the result you got here]
Expected result: [insert what you expected here]

[please make sure to add all possible details, like the title id (the 9-chars string in the left column) of the game you are talking about]

when the screen locks automatically in 30minutes the download failed.
fuuuuuuckkkkkkkkkk.
plz fix this somehow

**Comment by blastrock** [comment]
please fill the template, version, packages downloaded, full error message etc.

**Comment by TheOneEyedGrimReaper** [comment]
@blastrock 
here is the problem: download failure: HttpError: HTTP download error 0x80410136
