### ISSUE TITLE
Download Failure: Failed sceloDopen

### ISSUE THREAD

**Issue by Methaneus** [blastrock/pkgj#169]
Version of firmware: 3.68
Version of PKGj: 0.32

## Steps to reproduce the issue

- Using NoPayStation, install the DLC Omnimon MX for PCSE01171 Digimon Story : Cyber Sleuth - Hacker's Memory (USA)

Obtained result: The error "download failure: failed sceloDopen(ux0pkgiUP0700-PCSE01171_00 (the rest is cut off)"
Expected result: No error, a download completed and installed.

I googled, I reddit-searched, I googled again, asked in the /r/VitaPiracy discord, used Github's search to search through the issues, but nothing. Apparently I'm the first to get this error.

**Comment by blastrock** [comment]
Retry when NPS next refreshes, should be fixed.
