### ISSUE TITLE
100 percent noob here

### ISSUE THREAD

**Issue by supendi42** [blastrock/pkgj#17]
please teach me how to set up pkgj,only games download list no dlc or updates

**Comment by blastrock** [comment]
This is an issue tracker, if you want help on using this software, please ask on forums or reddit.

**Comment by edale2** [comment]
https://www.youtube.com/watch?v=rNOh2L9P2z4

Youtube, it's like Google, but with pictures! It can answer oh so many questions you may have on stuff like this.
