### ISSUE TITLE
Game Refresh doesn't refresh.  Loads 1 time only

### ISSUE THREAD

**Issue by jordaninthesky** [blastrock/pkgj#170]
Version of firmware: [3.65 ENSO]
Version of PKGj: [Past several versions and current]

## Steps to reproduce the issue

- [Refresh game list from scratch (only config.txt inside pkgi directory)]
- [It will finish loading]
- [Refresh Again]
- [It will get stuck at %100]
- [I have to manually clean pkgi directory of all db files to fix]

Obtained result: [freeze]
Expected result: [refresh]

**Comment by blastrock** [comment]
Just wait when it's stuck, it will finish.
