### ISSUE TITLE
error 0x8087004 also psx and dlc dont appear

### ISSUE THREAD

**Issue by deskgun** [blastrock/pkgj#172]
Version of firmware: 3.68
Version of PKGj: V0.31

## Steps to reproduce the issue
 for 0x8087004
- download a vita game 
- right before it finishes the error pops up

for psx and dlc
-download dlc and/or psx game
-finishes downloading (error doesn't pop up)
-but doesn't appear aka psx game isn't on livearea screen and (leasts say the dlc is a costume) the costume wont appear in the customization screen
 
Obtained result: error and dlc/game not appearing
Expected result: game and dlc downloading 

[please make sure to add all possible details, like the title id (the 9-chars string in the left column) of the game you are talking about]

**Comment by blastrock** [comment]
full error please. that code is also incorrect btw.

psx games don't appear in livearea, they appear in adrenaline

I don't know why your dlc doesn't work

**Comment by deskgun** [comment]
(sorry for late respond I was busy today) so psx games appear in adrenaline good to know because I didn't know so whenever I download a vita game lets say its uncharted for this case so I would download the game and nothing would happen then right at 99% a message would pop up saying "download failure: scepromoterutilitypromotepkgwithrif failed 0x80870004 please check your nonpdrm installation" which I have reinstalled nonpdrm a few times (2-3 times if correct) also the dlc thing is weird because it doesn't show the error message and says the dlc is installed

**Comment by blastrock** [comment]
Well, that's a nonpdrm issue then, can't help you on this one either.

For the DLC, it may be related to that nonpdrm issue.

**Comment by deskgun** [comment]
ok got it
