### ISSUE TITLE
PSP and PSX games as .PBP don't work

### ISSUE THREAD

**Issue by RY0M43CH1Z3N** [blastrock/pkgj#177]
Version of firmware: [3.68]
Version of PKGj: [0.32]

## Steps to reproduce the issue

- [add line install_psp_as_pbp 1]
- [download a game, mini or PSX game (any)]
- [I have npdrm_free.prx in ux0:pspemu/seplugins and activate]
- [Launch adrenaline and the game]

Obtained result: [Error 80010087]
Expected result: [Game runing]

With any other game in .iso or .cso have working.

**Comment by blastrock** [comment]
There's probably something wrong with your npdrm_free installation

**Comment by RY0M43CH1Z3N** [comment]
I tried with different versions and doesn't work, with another .pbp from my backups works fine and .cso .iso files also works fine, only using this option i have this error.

**Comment by RY0M43CH1Z3N** [comment]
I fixed following the next steps:

1. Downloading [qwizkrazor87 npdrm_free lates update](https://github.com/qwikrazor87/npdrm_free/releases) 

2. Copy npdrm_free.prx at ux0:pspemu/seplugins/npdrm_free.prx

3.Enable plugin in both ux0:pspemu/seplugins/game.txt **(and i think this is important to add to the readme)** ux0:pspemu/seplugins/vsh.txt.

**Comment by blastrock** [comment]
Well it is written it npdrm_free's readme. I don't think this needs to be written in pkgj's readme as it's not related to it, pkgj only installs the game. This leaves you the choice of whatever plugin you want with whatever config you want to run the games, like this new fork of npdrm_free.
