### ISSUE TITLE
Failed to refresh compack db: 0x80431061

### ISSUE THREAD

**Issue by cristianguter** [blastrock/pkgj#178]
Version of firmware: [3.67]
Version of PKGj: [0.32]

## Steps to reproduce the issue

- [Open PKGj]
- [Tap on refresh comp pack]

Obtained result: [failed to refresh compack db:
HttpError: sceHttpCreateConnectionWithURL failed: 0x80431061]

**Comment by blastrock** [comment]
That's SCE_HTTP_ERROR_UNKNOWN_SCHEME 

You got the URL wrong
