### ISSUE TITLE
pkgj - how to change psp/ps vita/psx installation folder?

### ISSUE THREAD

**Issue by maxflexpl** [blastrock/pkgj#179]
Version of firmware: [3.68]
Version of PKGj: [0.32]

Hi, 

quick question: how to change psp/ps vita/psx installation folder from ux0 to uma0 (SD2Vita)?

I change at pkgj config file input:
install_psp_psx_location ux0: to install_psp_psx_location uma0:

but when i start PKGj, pickup the game, download, instalation error ocure:
Download failure: scePromoterUtilityPromotePkgWithRif failed: 0x80870004

**Comment by blastrock** [comment]
ps vita games always go to ux0, that's where you sd2vita should be I guess

You have that error because there is an issue with your installation of nonpdrm.
