### ISSUE TITLE
[Feature request] Add "Refresh all" option in PKGj menu

### ISSUE THREAD

**Issue by JesterIOS** [blastrock/pkgj#180]
"**Refresh all**" - a new item in PKGj menu.
it will refresh all lists (_psv/psx/psp + comp pack_). it's very useful for users, who don't want to spend a lot of time and just quickly update all the content in every lists.

**Comment by eze92** [comment]
HI, but if you implement this option we should have the comp pack configured because if dont show error,I personally dont use this because have software 3.68

**Comment by JesterIOS** [comment]
@eze92 maybe add config.txt file check? I mean, **Refreash all** will check _url's_  in your config file. If you don't have "url_comppack..." - All lists will be updated except this.

**Comment by eze92** [comment]
ah ok , I think that if you implement this condition may be worked.

**Comment by symbuzzer** [comment]
Any news about this feature sir?

**Comment by Rameron** [comment]
And I think it would be perfect to refresh the psm games too. Cause VitaShell cannot do this.

**Comment by azumukupoe** [comment]
Is refreshing on start possible as well?

**Comment by blastrock** [comment]
@Rameron This is about refreshing the list of games, not about refreshing livearea, can't do anything about psm games yet

@azumukupoe I don't think that's a good idea as refreshing is quite slow, you don't want to wait for the refresh to finish on each start

FYI I am currently working on this, coming soon™

**Comment by JesterIOS** [comment]
Thanks =)
