### ISSUE TITLE
Download failure: failed sceloDopen

### ISSUE THREAD

**Issue by Korsovich** [blastrock/pkgj#181]
Version of firmware: 3.65
Version of PKGj: v0.32

## Steps to reproduce the issue

Everytime I try to download PSX (or PSP) games I get the error-
Download failure: failed sceloDopen (ux0:pkgj/UP9000-NPUJ01201_00

Obtained result: won’t let me download PSX from Pkgj
Expected result: wanted to download and play oldschool PSX games

Happens with all games I have tried but tried Alone in the Dark NPUJ01201, Amored Core NPUJ94182, Castlevania Symphoney of the night NPUJ00665, and Command and Conquer NPUJ00379

![954278bd-f97a-421d-a1f9-d8623cc275d9](https://user-images.githubusercontent.com/42100829/43826034-8d9f4bca-9af6-11e8-9c6f-9c3c6d8623b2.jpeg)

**Comment by blastrock** [comment]
Closing this, please reopen if it still occurs with the last version.
