### ISSUE TITLE
Unpack local PKG

### ISSUE THREAD

**Issue by Ziusun** [blastrock/pkgj#182]
I think it would be useful to have an option to unpack any local PKG. Work.bin/zrif could be obtained from somewhere else & PKG not on NoPaystation. With a directly downloaded PKG to Vita no PC would neccessary. Or maybe a fork of PKGJ would be better just to be able to open DRM PKG on Vita. I just can't do it myself 😖.

**Comment by blastrock** [comment]
I guess it would be possible, but I don't think I will have time to implement that unless there is more demand for it, sorry.
