### ISSUE TITLE
[Feature request] That you could download stuff while playing a game.

### ISSUE THREAD

**Issue by GarnettGaming** [blastrock/pkgj#183]
Version of firmware: [3.68]
Version of PKGj: [0.24]

## Steps to reproduce the issue

- It would be really nice if you could download games while playing another game, like listening to music on ps vita while playing a game with the ps vita

Obtained result: N/A
Expected result: N/A

[please make sure to add all possible details, like the title id (the 9-chars string in the left column) of the game you are talking about]

**Comment by blastrock** [comment]
There was an issue for that suggesting using sony's download manager, but someone needs to reverse engineer it before. It was issue #42 , github made it disappear...
