### ISSUE TITLE
Download depleting unnecessary amounts of storage.

### ISSUE THREAD

**Issue by TheKTD** [blastrock/pkgj#185]
Version of firmware: [3.65 Enso]
Version of PKGj: [0.32]

I'm receiving an issue when I download any content on PKGJ. My storage starts depleting quickly, regardless of the size of the game. For example, Persona 3 Portable (ULUS10512) is 1.07GB, but my storage is 2.05GB. I expected the size of my storage to then be around 0.97GB, but instead it was 735MB. I've experienced this issue with previous versions as well, but I thought it would be fixed by now. PKGJ is an amazing software, but this ruins it for me.

**Comment by blastrock** [comment]
That's a PSP game, if you are using the default mode, they are converted to ISO files, which are uncompressed. To keep them compressed, you need to install npdrm_free and set `install_psp_as_pbp 1` in pkgj's config file
