### ISSUE TITLE
Feature: Auto-update

### ISSUE THREAD

**Issue by MottoWolf** [blastrock/pkgj#19]
Could be possible an auto-update? 

to avoid downloading from github all the time

**Comment by blastrock** [comment]
I tried to make it work, but the psvita wouldn't connect to github.com (even in the browser) because of an SSL error. I only tried with 3.60 though.

**Comment by MottoWolf** [comment]
Have you tried to use https://github.com/TheOfficialFloW/VitaShell/tree/master/updater ?

maybe you can ask him to get it working, because it has been done already :D

**Comment by symbuzzer** [comment]
we dont need to use pc for downloading games to vita because pkgj. 
but we need to pc for downloading every pkgj update :(

**Comment by YokYokYokYok** [comment]
Yes, auto update would be useful

**Comment by blastrock** [comment]
I haven't forgotten this, I will try to do it soon enough.
