### ISSUE TITLE
A way to highlight newly added content (albeit games, dlc, etc) to PKGj

### ISSUE THREAD

**Issue by thee-i-cast-aside** [blastrock/pkgj#192]
Version of firmware: [3.68 h-encore]
Version of PKGj: [0.33]

## Steps to reproduce the issue

- [N/A]

Obtained result: [N/A]
Expected result: [N/A]

[With the rate of games being added to PKGJ (not to mention NPS) it would be cool to have a bright yellow or pink (or some other never-used color) to highlight which games have been included in the last, say, 168 hours (or 1 week)].  Just another way to make browing PKGJ even more wonderful.]

**Comment by blastrock** [comment]
You can already sort the entries by date, isn't that enough?

**Comment by thee-i-cast-aside** [comment]
I think it gets better every update but we don’t just sort by date release?  Some sort by names; some sort ascending, some sort descending..  It’s just frustrating when you tell it to refresh something, it does it, but you have no clue of easily seeing if something new dropped.

**Comment by blastrock** [comment]
Well, sorting by date does just that. It's not the game release date, it's the date the game was added to nps, so you can just sort by date after refreshing and you'll see at the top what was recently added.
