### ISSUE TITLE
Download failure: scePromoterUtilityPromotePkgWithRif failed

### ISSUE THREAD

**Issue by Squal23** [blastrock/pkgj#193]
Version of firmware: PS Vita PCH-1004 [3.68]
Version of PKGj: [0.33]

## Steps to reproduce the issue

- choose game from list
- download it

Obtained result:
-Download failure: scePromoterUtilityPromotePkgWithRif failed: 0x80871003
-Download failure: scePromoterUtilityPromotePkgWithRif failed: 0x80871004
-Download failure: scePromoterUtilityPromotePkgWithRif failed: 0x8001002f

Expected result: 
-Game to being dowloaded and installed

Hi,
first of all thanks guys for all work You're doing with PKGJ. Keep it up! Really appreciate it.

**I'm not reporting bug but one of possible solutions**, this can be closed after my comment:
I got those errors when I changed old microsd to new bigger one from Sandisk 64gb to Sandisk 256gb, I've read all reported bugs but steps with TAI folder didn't helped. Reinstalling PKGJ and nonpdrm also. 

Games were downloaded until memory limit reached certain value like +/- 30gb then those error codes started to appear everytime game reached 99% during download. 

After a lot of reading about memory cards ;) I've made a wipe of card and then used this program **h2testw** to check my card, it turns out card was modified and it was a 32gb card and errors were popping because Vita theoretically saw free space but there was no space at all. So if You buying new card please check it first to save some time. Mine was sold as new and actually there were no differences between this fake and original one. So possibilities are:
1. Your old card is dying
2. New card is fake and it's memory is not as big as windows show You

**in both cases Your nonpdrm and tai folder doesn't need to be modified in any way.**

I struggled with this issue for few days, when I returned to old 64gb card everything was working without any errors. I hope this description will help somehow all of You guys. 

UPDATE:
One more thing, why I recognized it's not nonpdrm and tai folder issue? I could play games that I downloaded before errors showed up. So if You have the same thing, I bet You have issue with Your card.

**Comment by nighto** [comment]
Just adding two cents: another good software to test for card quality is **[F3 - Fight Flash Fraud](https://github.com/AltraMayor/f3)**. It writes a bunch of random data with a specific algorhythm then reads everything back, checking if it is as expected. It is a great way to test if your card really has the capacity written on it, and also check for real read and write speeds.

**Comment by blastrock** [comment]
All right, thanks for sharing your knowledge guys! I'll redirect people here if they have such issues.
