### ISSUE TITLE
can´t get list: HttpError: sceHttpSendRequest failed: 0x80436007

### ISSUE THREAD

**Issue by RyuSeisuke1992** [blastrock/pkgj#194]
Version of firmware: 3.60
Version of PKGj: v0.33

1. Start PKGj
2. Error `No items! Try to refresh`
3. I press the triangle button to enter the menu
4. I choose the option "Refresh"
5. Then the following error message appears: `can´t get list: HttpError: sceHttpSendRequest failed: 0x80436007`

**Comment by RuggeDX** [comment]
Got the same problem a few days ago. Delete all files in the pkgi folder except for your config.txt. That's what fixed it for me.

**Comment by RyuSeisuke1992** [comment]
Solved, thanks @RuggeDX!
