### ISSUE TITLE
Download stops, no error code

### ISSUE THREAD

**Issue by Squal23** [blastrock/pkgj#195]
Version of firmware: PS Vita PCH-1004 [3.68]
Version of PKGj: [0.33]

## Steps to reproduce the issue

- set long downloads que of big Vita games
- keep an eye on screen from time to time 
- make sure the screen will not go off

Obtained result:
Download stops, no error. 

Expected result:
-Game to being dowloaded and installed

Looks like internet connection is lost or some kind of timeout but there's no error message. Cancelation of affected game and renewing download helps and game is being downloaded, if You have a que next game will start download without any problem. It happens only with games bigger than 1GB. Hard to reproduce because You need a long que to do it. I was downloading games whole day and this situation happend 5 times. If You need more info please let me know, I'll try my best to provide them.

**Comment by blastrock** [comment]
Probably the same issue as this https://github.com/blastrock/pkgj/issues/112#issuecomment-403127824
