### ISSUE TITLE
No items!Try to refresh,Pressed the refresh button did not respond

### ISSUE THREAD

**Issue by psv1kdump** [blastrock/pkgj#196]
Version of firmware: 3.68
Version of PKGj: 0.34

## Steps to reproduce the issue

- No items!Try to refresh，Pressed the refresh button did not respond
- Already try restart psv,try delete pkgi folder,reinstall pkgj 0.34
- [insert the steps to reproduce the issue here]

Obtained result: [insert the result you got here]
Expected result: [insert what you expected here]

[please make sure to add all possible details, like the title id (the 9-chars string in the left column) of the game you are talking about]

**Comment by blastrock** [comment]
What do you mean "the refresh button did not respond"? It just does nothing??

**Comment by psv1kdump** [comment]
yes，nothing。

**Comment by psv1kdump** [comment]
![2018-09-02-100255](https://user-images.githubusercontent.com/38326397/44951477-dca69700-ae97-11e8-90fc-72e910302855.jpg)

**Comment by psv1kdump** [comment]
![2018-09-02-111002](https://user-images.githubusercontent.com/38326397/44951808-f7313e00-aea0-11e8-8611-4c213004e3df.jpg)
![2018-09-02-110949](https://user-images.githubusercontent.com/38326397/44951809-f7313e00-aea0-11e8-8ab3-206c82f984bc.jpg)

**Comment by JesterIOS** [comment]
Since 0.34, .db files (_GAMES/UPDATES/DLC & etc)_ moved into 1 file (_pkgj.db_).
Try to delete all .db files in pkgi folder and try to refresh.

**Comment by blastrock** [comment]
So it does something.

There's a problem with your internet connection or something, change wifi?

**Comment by unl1nk** [comment]
Hi, I exactly the same issue. Can you please re-install pkgj and change your config.txt to this:

https://pastebin.com/arWfMUhx   just copy lines and paste your config.txt file.

If it doesn't work, please change https to http. 

Hope it will help!

**Comment by omerbereket** [comment]
Hi, i found this website and it seems to work with 0.33 at least.

https://psvitamod.com/wp-content/uploads/2018/07/config.txt

good luck
