### ISSUE TITLE
[bug] some dlc says the basegame isnt installed when it is.

### ISSUE THREAD

**Issue by SilicaAndPina** [blastrock/pkgj#2]
noticed that after installing HDNRB3 i went to download the DLC, and it lets me download some of it.. but some of it it says i don have the game installed when i do, and al the dlc has hte same titleid.. its

**Comment by richard1222** [comment]
Not sure if this will help you but i got my dlc/vita game  from a site and the piratebay when pkgj gave that issue to

**Comment by SilicaAndPina** [comment]
i could just download it manually from the NPS database but thats lame

**Comment by blastrock** [comment]
Should be fixed, please reopen if it still happens
