### ISSUE TITLE
0.36 doesn't work

### ISSUE THREAD

**Issue by gamestars9** [blastrock/pkgj#200]
Version of firmware: [3.67 HENkaku]
Version of PKGj: [0.36]

## Steps to reproduce the issue

- [Opened the app]

Obtained result: [Error C2-12828-1]
Expected result: [Expected the app was working]

**Comment by sdragon74** [comment]
me too.

**Comment by blastrock** [comment]
Try to disable autoupdate in the config or stay on 0.35. I'll check that out soon.

**Comment by KamaruKou** [comment]
Can't recall if the error code was the same but I experienced a similar problem. What I did was install an older version. 0.34 specifically. Then install 0.36 using the Vita Homebrew Browser App. Once installed, I rebooted and it seems to work now. Please give that a try and see?

**Comment by sdragon74** [comment]
in fact its not work -----install 0.36 using the Vita Homebrew Browser App

**Comment by kofwinner** [comment]
0.36 doesn't work
0.35 is fine

**Comment by Carrieshot** [comment]
c2-12828-1 was the error code that it gives

**Comment by halo2028** [comment]
0.36
It can be opened or downloaded.
But when I stop downloading, the program crashes.
Shown below:
(C2-12828-1)
Saved Core File Succeeded.
ux0:data/psp2core-1536927510-0x00000725f5-eboot,bin.psp2dmp

**Comment by gatesphere** [comment]
Same here -- PSTV H-encore Enso 3.65.

0.36 appears to be broken in some way.  0.35 works without issue.

**Comment by berrios30** [comment]
by adding no version check made it work for me only thing is that getting passed 6/8 on the refreshing part i keep getting stuck their

**Comment by ericchavarin** [comment]
adding no version check did not work for me on 3.68.

**Comment by berrios30** [comment]
i am on 3.65 enso updater one just getting stuck at the part where it tries the find the entries.txt from the github

**Comment by pkly** [comment]
I installed 0.36 through Vita Homebrew Channel and it works fine.

**Comment by KamaruKou** [comment]
The stop downloading error finally hit me too. Similar issue with Halo2028. Guess I'll downgrade to 0.35 as well for now.

**Comment by rsn8887** [comment]
I installed 0.36 through VHBB and then again from the github vpk. Both ways, I got the error "(C2-12828-1)" on start.

**Comment by blastrock** [comment]
I could reproduce the cancel issue, but not the start-up issue. I think they are related though.

Here's a vpk on which I tried to fix them: https://drive.google.com/file/d/1wMpHaI7lKPcpJi395GYQVZ19KDpf-ZGp/view?usp=sharing

If someone who has a C2-12828-1 on start could test it for me, it would help. I am wondering if the issue can only happen on ps vita fat (I have a slim one).

**Comment by halo2028** [comment]
My device is PSV 2000(slim), and the system version is 3.68.
I installed the application you had fixed, and repeated more than 10 times the "Start Download - Cancel Download" operation, no problem. It seems that the problem has been solved at least on my device.

**Comment by yexun1995** [comment]
My device is psv 1000.And,368 h-encore with sd2vita.The fixed version is really working.There is no C2-12828-1 error on start now.

**Comment by blastrock** [comment]
Thanks for your tests, let's release!
