### ISSUE TITLE
Download failure: scePromoterUtilityPromtePkgWithRif failed: 0x80af55055

### ISSUE THREAD

**Issue by hikarisilver** [blastrock/pkgj#203]
Version of firmware: [3.68]
Version of PKGj: [0.37]

## Steps to reproduce the issue

- Install PKGj, created a "pkgi" folder in ux0: 
- Install autoplugin and installed "nonpdrm" and config file into ux0: and ur0:
- Reboot PSTV and refresh live screen and databases
- Mount USB and install nonpdrm onto USB 
- Copy PKGI folder to mounted USB.
- Refresh databases upon reboot

Obtained result: Error code as described in the title
Expected result: My download(s) in PKGj to be sucessful

**Comment by Trulydark** [comment]
I'm having the same problem but I didn't even need to do anything other then update pkgj to the newest version

**Comment by Trulydark** [comment]
I can confirm nonpdrm is working properly, not only can I still use my dowloaded games that I had done previously but I had not changed anything in any files, I just downloaded and installed the update and it had begun to get this problem.

**Comment by blastrock** [comment]
Might be related to #193

**Comment by hikarisilver** [comment]
I was attempting to download Netflix, YouTube, and other games from PKGj and got this error.

**Comment by MuRr3YsKu11** [comment]
Good night friends, i was getting this same fucking error, and waste some time searching for a fix in the web but without sucess. Then i decide to do a quick review in the files and folders on vitashell. To my surprise, i found an empty folder called 'new' on ux0:/appmeta, and deleted this fucking folder ux0:/appmeta/new. Tried to use pkgj again and everything back to normal. This fix the problem to me, maybe sove yours too.

**Comment by Trulydark** [comment]
Nope I checked my appmeta strangely enough it seems it's just hatsune miku project diva f 2nd edit mode since I was able to download undertale with zero issue

**Comment by Trulydark** [comment]
Well I decided to go into safe mode and tried to rebuild the database and it seemed to have fixed it, I have no idea why but it did
