### ISSUE TITLE
HTTP download error 0x80431068 plz help ;-;

### ISSUE THREAD

**Issue by smashedupface** [blastrock/pkgj#204]
Version of firmware: [3.56]
Version of PKGj: [0.37]

## Steps to reproduce the issue

dowload anything over 100mb

Obtained result: [HTTP download error 0x80431068]
Expected result: [it should download]

anybody know how i can fix this its been driving me insane trying to fix it :(

**Comment by blastrock** [comment]
Just retry the download for the moment...
