### ISSUE TITLE
"Download Failure: Wrong PKG Header"

### ISSUE THREAD

**Issue by TheKTD** [blastrock/pkgj#206]
Version of firmware: [3.65 Enso]
Version of PKGj: [0.37]

If I try to download anything, I get the "Download Failure: Wrong PKG Header" error. Refreshing doesn't work either as it simply says, "can't get list: fail to parse line <fieldset>.

Even when I launch the app, I get a notification telling me to install a DOC HEADER update. Nothing happens when I press either yes or no.

**Comment by blastrock** [comment]
Your IPS or router is injecting stuff on the connection, try with another connection

**Comment by JooJ7475** [comment]
I'm having this problem to my PKGj, I'm trying to install Crash Bandicoot (USA ver.), but I'm getting this error 
(Download failure : wrong pkg header)

**Comment by JooJ7475** [comment]
> Your IPS or router is injecting stuff on the connection, try with another connection

I'm having this same error trying to download ps1 games through PKGJ but this solution not helped me
