### ISSUE TITLE
v0.37 installed but always show version v0.26

### ISSUE THREAD

**Issue by citrabatam** [blastrock/pkgj#208]
Version of firmware: enso 3.65
Version of PKGj: 0.37

I installed version 0.37 and other earlier versions, it always show as version v0.26

I have checked and double checked, the config.txt and NoNpDrm plugin correctly installed.

**Comment by blastrock** [comment]
Is that in the live area or in the app?

**Comment by citrabatam** [comment]
i believe it's the app. how do i see in the live area?

**Comment by blastrock** [comment]
When you click on pkgj's icon, just before you start it. If you see 0.26 in the app, then you clearly have the wrong version. Did you download it from here?

**Comment by citrabatam** [comment]
Yes, I downloaded it from here and I even tried several earlier versions plus deleting and re-installing 0.37

Strangely today, I tried with a fresh download and it worked !  Thanks so much for the assistance.
