### ISSUE TITLE
DLC redownload error 0x80010078

### ISSUE THREAD

**Issue by gameer19** [blastrock/pkgj#209]
Version of firmware: 3.68 h-encore
Version of PKGj: .37

## Steps to reproduce the issue
Game: Asian Eng. SD Gundam Generations Genesis

- deleted dlcs that failed to install
- tried to redownload said dlcs
- got error 0x80010078

Obtained result: unable to download dlc
Expected result: redownload just fine

Edit: not sure why it posted empty before.

**Comment by blastrock** [comment]
Can you give the complete error message please?

**Comment by gameer19** [comment]
Hi, the error stopped happening after the latest update. It was probably
caused by my nephew tinkering with my Vita.

Great job, btw. We really appreciate it. So many crappy games out on the
psn so being able to try them out before buying the actual game is like
performing cpr on my wallet.

Cheers!
