### ISSUE TITLE
Accidentally canceled PSX download couldn't be restarted.

### ISSUE THREAD

**Issue by edale2** [blastrock/pkgj#21]
I was downloading Xenogears US, and accidentally hit 'X' again, canceling the download.

Nothing I did could restart the download, including restarting my PSTV.

I ended up using VitaShell to manually go into ux0:pkji/ and deleting the 2 folders it had created during the download, which let me start the download over.

**Comment by blastrock** [comment]
I dropped the download resume feature, so this should now work.
