### ISSUE TITLE
PKGj 0.37

### ISSUE THREAD

**Issue by jake071789** [blastrock/pkgj#210]
Version of firmware: [3.68]
Version of PKGj: [0.37]

## Steps to reproduce the issue

- [ After downloading PSV game to 100% it's show a pop up download failed: scepromoterutilitypromotewithpkgrif failed: 0x80010002]
 [ I try to download again another PSV game it's a pop up again scepromoterutiltypromotepkgwithrif: 0x8001002f]
- [can you help me fix that download failed]

Obtained result: [download failed:]
Expected result: [ i hope you fix that error thank you]
![img_20181004_093321](https://user-images.githubusercontent.com/43844339/46465630-b445eb80-c7fb-11e8-9d5c-d88b03f55e62.jpg)
![img_20181004_171209](https://user-images.githubusercontent.com/43844339/46465650-bf991700-c7fb-11e8-9af2-6d24e8221a8e.jpg)

**Comment by hendraandi** [comment]
i cant refresh the vita games, always error . it says "cant get list, failed to parse line'' 

any solution?

**Comment by blastrock** [comment]
@jake071789 There's a problem with your nonpdrm installation, see also #193 

@hendraandi there are a lot of similar issues open, I think this is a problem with your router.
