### ISSUE TITLE
Error with comp packs

### ISSUE THREAD

**Issue by Costiny** [blastrock/pkgj#211]
Version of firmware: [3.65]
Version of PKGj: [0.37]

## Steps to reproduce the issue

- [Added the line  url_comppack https://github.com/nopaystation_repos/nps_compati_packs/raw/master/ in the config.txt file in pkgj folder. I've also tried with variatons of the link (entering entries.txt or deleting the s in http, things like that, and also tried using the config.txt in a pkgi folder)]
- [I get the error "No compatibility pack found" for the games I tried, which are Stardew Valley (PCSE01235) and Super Skull Smash Go! 2 Turbo (PCSE01225)]

Obtained result: [No comp packs were found when they actually exist]
Expected result: [I expected it to install them]

**Comment by Costiny** [comment]
Sorry, that's the wrong link, I used https://gitlab.com/nopaystation_repos/nps_compati_packs/raw/master/

**Comment by karinfam** [comment]
Have you tried with http:// instead of https://? Seems like NPS dropped the SSL support (according to this reddit comment https://www.reddit.com/r/VitaPiracy/comments/8ec6qi/nopaystationpkgj/dxw3dv0)

I'm on 3.65 and 0.37 too, and I just got Stardew Valley working for me.

**Comment by ismael587** [comment]
hello
Don't use https but http because secure https connection doesn't work
i use the following link
url_comppack http://gitlab.com/nopaystation_repos/nps_compati_packs/raw/master/

**Comment by ismael587** [comment]
if you can't download them you can copy them directly in the rePatch folder
first go here
https://gitlab.com/nopaystation_repos/nps_compati_packs
go for exemple to PCSE01235
then download the file PCSE01235-03_670-01_00-01_01.ppk
rename it PCSE01235-03_670-01_00-01_01.zip and unzip it to directory PCSE01235 and copy this directory directly in the rePack folder. and now it should work.

**Comment by ismael587** [comment]
I tried downloading comp pack for PCSE1235 with pkgj and it works fine for me.
Maybe you should uninstall pkgj and reinstall it. here is my pkgi folder, maybe it will help you.
[pkgi.zip](https://github.com/blastrock/pkgj/files/2470345/pkgi.zip)

**Comment by Costiny** [comment]
Well, I honestly have no idea of why it worked, but it just worked. Could it be that the config.txt has to be in pkgi folder? Anyway thanks a lot!!
