### ISSUE TITLE
Will PKGj Install .pkg Files in Directory?

### ISSUE THREAD

**Issue by Smoker1** [blastrock/pkgj#214]
Version of firmware: [insert version] 3.65Enso
Version of PKGj: [insert version]0.37

Will PKGj Install from .pkg Files on the Card? Running out of Space due to the Folders being too large. 
I get a Game and the Folder shows - 
Size 716MB
Size on Disk - 728MB
I move it to my Vita -
Size 716MB
Size on Disk 1.94GB !!!!!!!!!!!!!!!
With pkgi , I can Install Directly from the Device with a .pkg File, and the Size remains close to what it should be.

**Comment by blastrock** [comment]
That's strange, pkgj does essentially the same thing as NPS browser. Have you tried formatting your sd card?

**Comment by Smoker1** [comment]
I dont have my Vita Connected to the Internet. But yeah, I download a item from NPS, and it has the File Size like the Example. But when I Move it to the Vita, and the Size on Disk goes through the roof. But if I get the .pkg File from the NPS place (the actual name tdcyjth....pkg), and Install with the old pkg App, it is much better. 
Just thinking, for other Users, there should still be the pkgi.txt File that can be Updated, for Users who still prefer that Method. 

There is a addcont item as well. DL and Extract with NPS, it is 1.48 Size, but 2.16 SoD. On my Vita, it is 1.48 Size, but 35.2MB SoD. 
But yeah, I move to my PC again, the Size returns to normal. Will do that today and Reformat with 64kb Allocation Size and let you know. But yeah, should keep that method. The only problem is, the PSVSD seems to slow WAY down after a while when Installing :(

**Comment by Smoker1** [comment]
Yeah, starting the Transfer now. From what the Transfer is showing, I should have 14GB Left, but the Vita shows around 1.5?????? LOL

**Comment by Smoker1** [comment]
Now I have 11.1GB on my Vita. I think the Card was using 256KB Allocation since it is a 256GB. Read somewhere that whatever the Card Size is, is usually the Default Allocation for it. Also made sure to Show Hidden System Files, to make sure I got EVERYTHING!!!

**Comment by blastrock** [comment]
@windsurfer1122 You can do that with NPS browser.

I do not plan on implementing this at the moment, closing it for now.

**Comment by windsurfer1122** [comment]
@blastrock: For Windows that is possible.

**Comment by blastrock** [comment]
Right, but it should work on wine for linux (though I haven't tried), and there's a nps browser for macos too.

Btw, if you have a .pkg file, you can extract it with https://github.com/mmozeiko/pkg2zip (despite the name, it actually extracts pkgs), pkgi comes from there.
