### ISSUE TITLE
ERROR: 0x80870004

### ISSUE THREAD

**Issue by PagigLp** [blastrock/pkgj#216]
Version of firmware: [3.68]
Version of PKGj: [0.37]

When i opened pkgj without henkaku pkgj wont start so i opened henkaku again.  When tried downloading a game in pkgj it install but after 100% this pop: 
Download failure: scePromoterUtilityPromotePkgWithRif failed: 0x80870004 Please check your NoNpDrm installation
 After that I reinstall pkgj. I also tried #74 #97 but still not work.
By the way I have nerver installed NoNpDrm!

**Comment by ismael587** [comment]
install NoNpDrm and retry
[](url)https://github.com/TheOfficialFloW/NoNpDrm

**Comment by PagigLp** [comment]
I have nerver installed NoNpDrm!

**Comment by PagigLp** [comment]
Thank you so much
