### ISSUE TITLE
DLC redownload error 0x80010078

### ISSUE THREAD

**Issue by nanashi89** [blastrock/pkgj#217]
Version of firmware: 3.68 h-encore
Version of PKGj: 0.37

## Steps to reproduce the issue

- [Deleted DLC for Digimon Story Cyber Sleuth (EU)]
- [Attempted re-installation]
- [Gave me error 0x80010078]

Obtained result: [error 0x80010078]
Expected result: [downloaded and installed DLC]

[Have started with a fresh, different, well-known microSD card, tried re-installing nonpdrm and the PKGi config.txt, both manually and through Autoplugin, and I'm only able to install Games and Patches]

**Comment by blastrock** [comment]
Can you give the complete error message please?
