### ISSUE TITLE
NPUJ94457 Grandia US won't install.

### ISSUE THREAD

**Issue by edale2** [blastrock/pkgj#22]
I've installed several PSX games, so this isn't a configuration problem.

I tried to install Grandia, and after it finished downloading, instead of a filled in white circle, there's a white circle outline, with a grey center.

It's not showing up in Adrenaline, and hitting 'X' on the game again does nothing.

**Comment by edale2** [comment]
Same just happened to Chrono Trigger NPUJ01363

**Comment by edale2** [comment]
Deleting everything but the config file from ux0:pkgi/ let me redownload and actually install the games (well Chrono Trigger, working on redownloading Grandia atm)

**Comment by blastrock** [comment]
Did the vita go to sleep during the download? This seems to break things...

**Comment by edale2** [comment]
I don't think so. It might have happened though. Happened on a PSTV.

**Comment by blastrock** [comment]
I dropped the download resume feature, so this should be fixed by just redownloading the game
