### ISSUE TITLE
pocketstation download failure 

### ISSUE THREAD

**Issue by crazy2k4** [blastrock/pkgj#220]
Version of firmware: [3.68 H-Encore]
Version of PKGj: [0.37]

## Steps to reproduce the issue

- [simply,try download pocketstation app for vita,but appears this error code: ]
- [download failure: scePromoteUtilityPromotePkgWithRif failed: 0x8010111c]
- [only this app failed,any other game or app,download and install fine]

Obtained result: [error code and not install app]
Expected result: [download and install app]

[please make sure to add all possible details, like the title id (the 9-chars string in the left column) of the game you are talking about]

**Comment by TheRadziu** [comment]
pocketstation can't even be properly extracted using pkg2zip or pkg_dec, so no wonder pkgj fails at it too. 

It needs more research, plus I doubt it could work with non-bubble psx eboots
