### ISSUE TITLE
[discussion] Why PSX games (installed as EBOOT) placed in psm folder?

### ISSUE THREAD

**Issue by JesterIOS** [blastrock/pkgj#222]
_Sorry for bad English =)_
**Version of firmware:** 3.65 HENkaku Enso
**Version of PKGj:** 0.38

## Steps to reproduce the "issue?"

- Add **`install_psp_as_pbp 1`** in config.txt.
- Install any **PSX** game.
- Check game in _Adrenaline_

**Obtained result:** the game isn't displayed in Adrenaline menu and placed in psm folder.
**Expected result:** the game placed in pspemu folder and displayed in Adrenaline menu.

## Example:
1. Downloading PSX game
![2018-11-07-190506](https://user-images.githubusercontent.com/30769120/48130927-cfa38b00-e2c0-11e8-8c5b-b4f8775f17e1.png)

2. Downloading PSM or PSX? xD
![2018-11-07-190513](https://user-images.githubusercontent.com/30769120/48130969-f3ff6780-e2c0-11e8-802d-517752df98a0.png)

3. Not marked as installed
![2018-11-07-190530](https://user-images.githubusercontent.com/30769120/48130941-dc27e380-e2c0-11e8-94f8-cc38515056dc.png)

4. here is it
![2018-11-07-190626](https://user-images.githubusercontent.com/30769120/48130985-07aace00-e2c1-11e8-82ab-b8433d167890.png)

5. no game =(
![2018-11-07-190639](https://user-images.githubusercontent.com/30769120/48130983-01b4ed00-e2c1-11e8-8d42-68f4533fa52e.png)

**Comment by JesterIOS** [comment]
**+ My config file:**
![2018-11-07-193034](https://user-images.githubusercontent.com/30769120/48131896-370f0a00-e2c4-11e8-9c07-fb5ddb729520.png)

**AND one more thing:**
**PSM installing as DLC**
![2018-11-07-192900](https://user-images.githubusercontent.com/30769120/48131927-5148e800-e2c4-11e8-9c0d-6b0b1ec2ddc0.png)

**Comment by blastrock** [comment]
I messed up in that last release indeed.
I couldn't test this one so this is kind of a blind fix, hope it works ^^

**Comment by JesterIOS** [comment]
It works! =]
