### ISSUE TITLE
Fatal Error 0x80010002

### ISSUE THREAD

**Issue by SyncZero** [blastrock/pkgj#225]
Version of firmware: [3.68]
Version of PKGj: [v0.40]

## Steps to reproduce the issue

- [install pkgjv0.40 update]
- [delete old pkgj from live area]
- [ux0/PKGJ/pkgj-v0.40/vpk install]

Obtained result: [Fatal error: failed sceloDopen(ur0:app): 0x80010002]
Expected result: [pkgj properly works]

[ux0:PKGJ/config.txt:
url_games http://nopaystation.com/games.tsv
url_dlcs http://nopaystation.com/dlcs.tsv
url_psx_games http://nopaystation/psxgames.tsv
url_psp_games http://nopaystation.pspgames.tsv
url_psm_games http://nopaystation/psmgames.tsv
url_comppack http://nopaystation/comppack/ ]
note: NoNpDrm v1.2 already installed in KERNEL ur0:tai/config.txt

**Comment by JesterIOS** [comment]
Why do you use _"example urls"_ in your config? They **don"t work**!
