### ISSUE TITLE
DLC C2-12828-1

### ISSUE THREAD

**Issue by mrzyaklo** [blastrock/pkgj#226]
Version of firmware: 3.65 HEN Enso
Version of PKGj: 0.39

## Steps to reproduce the issue

- Install game PCSG1079(3.67) with NoDRM copy and refresh LiveArea
- Install base and 1.02 CompPack with PKGj
- Install game update 1.02 with LiveArea
- Start game, all going well. In PKGj all green
- Install DLC with PKGj with no errors.
- After that game not start, with error C2-12828-1
- If I delete folder ux0:addcomt/PCSG1079 game was start.

Obtained result: Can`t use DLC
Expected result: DLC

Game - Utawarerumono, PCSG1079, for V 3.67
Game and console(and my, sorry for my english) - JP region
This topic is continue of https://github.com/blastrock/pkgj/issues/221
With update PKGj to 0.39 game  more not crash, but DLC not run.
In that case maybe trouble not in PKGj, but searching no take result.
In other games DLC runing whithout troubles, but this is first game with version 3.66+

**Comment by blastrock** [comment]
Which DLC causes the error?

**Comment by mrzyaklo** [comment]
In this game - yes. In other game almost no problem.

**Comment by blastrock** [comment]
I mean: what is the DLC that causes the error?

**Comment by mrzyaklo** [comment]
For this game - all. All item DLC, all unite DLC.
