### ISSUE TITLE
[Bug] Unity PSM Titles have runtime directory extracted into wrong place.

### ISSUE THREAD

**Issue by TheRadziu** [blastrock/pkgj#227]
Version of firmware: Affects all
Version of PKGj: 0.33 and up to the latest 0.41

## Steps to reproduce the issue

- download any Unity PSM game, in this example NPNA00204

Obtained result:  runtime directory within a game extracted to `ux0:psm/NPNA00204/RO/runtime`
Expected result: runtime directory within a game extracted to `ux0:psm/NPNA00204/runtime` 

with runtime extracted incorrectly game(s) can't be run. pkg2zip has the same issue (posted issue [there too](https://github.com/mmozeiko/pkg2zip/issues/20))

sidenote: those unity games also require drm free license for PCSI00010 (PSV GAMES tab) extracted to `ux0:license/app/PSM_GAME_ID/6488b73b912a753a492e2714e9b38bc7.rif` (in case of this example PSM_GAME_ID would be NPNA00204) but hopefully this will be done automatically by vita when proper PSM promotion emerges.

**Comment by k4nine** [comment]
My psv 3.68 cant play unity game .It show C1-11843-7

**Comment by TomySakazaki** [comment]
Can confirm that this still happens in v0.51

**Comment by cuevavirus** [comment]
Fixed in https://github.com/blastrock/pkgj/commit/2ec817f02053a373fd7d9206e6efa24072b61a7b
