### ISSUE TITLE
Can't cancel download of PSP title

### ISSUE THREAD

**Issue by Localhorst86** [blastrock/pkgj#228]
Version of firmware: [Vita 2004 3.68]
Version of PKGj: [0.39-0.41]

When downloading a psp (Edit: or psx) title, pressing x will not cancel the download, it will just continue.

Obtained result: no change in the download status
Expected result: download getting cancelled

Happens on every title, tried UCES01245, NPUH10122
Download location is uma0, which is actually the vita memory card (mounted via storage-Mgr)
Happens with and without 
install_psp_as_pbp 1

**Comment by Alcanderian** [comment]
PS: It has been canceled, but resume soon.
