### ISSUE TITLE
no more update option

### ISSUE THREAD

**Issue by Percolateur2000** [blastrock/pkgj#229]
Version of firmware: 3.65 H-Encore
Version of PKGj: 0.41

I have a pstv 3.65 with H-Encore, a 64go USB 3 usb drive, and the option to update games in pkgj is not available. It use to be tho, but can't remember when/how.

Obtained result: No Update option
Expected result: Update option under "Show Game"

my config.txt :

url_games http://youknowwhat.com/tsv/PSV_GAMES.tsv
url_dlcs http://youknowwhat.com/tsv/PSV_DLCS.tsv
url_updates http://youknowwhat.com/tsv/PSV_UPDATES.tsv
url_psm_games http://youknowwhat.com/tsv/PSM_GAMES.tsv
url_psx_games http://youknowwhat.com/tsv/PSX_GAMES.tsv
url_psp_games http://youknowwhat.com/tsv/PSP_GAMES.tsv
url_comppack https://gitlab.com/nopaystation_repos/nps_compati_packs/raw/master/
install_psp_psx_location ux0:
psm_disclaimer_yes_i_read_the_readme NoPsmDrm
sort name
order asc
filter USA

---

tried with both http and https

**Comment by Localhorst86** [comment]
Intended behavior. Has been removed with 0.38:

Removed features:

    PKGj can't download game updates anymore as they were outdated. Use the livearea to update your games.

**Comment by Percolateur2000** [comment]
Thanks for the answer !

i'll now check why i can't udpate with livearea, i can download but it won't install, not pkgj issue. Thanks
