### ISSUE TITLE
Cant install DLC for certain games

### ISSUE THREAD

**Issue by SpooksMcBoners** [blastrock/pkgj#232]
Version of firmware: [3.68]
Version of PKGj: [0.41]

## Steps to reproduce the issue

- [Go-to download botzone dlc for killzone mercenary PCSA00107]

Obtained result: [ERROR CORRESPONDING GAME NOT INSTALLED]
Expected result: [Kinda want it to install. I have the game.]

[please make sure to add all possible details, like the title id (the 9-chars string in the left column) of the game you are talking about]

**Comment by blastrock** [comment]
Can't reproduce here, I need more detail about what you did.
