### ISSUE TITLE
Resistance burning skies USA region are broken. it crash at first 5 minutes gameplay

### ISSUE THREAD

**Issue by cesar19004** [blastrock/pkgj#233]
Version of firmware: 6.68
Version of PKGj: 0.42

## Steps to reproduce the issue

- Just download Resistance: Burning skies from USA region
- It crash at first 5 minutes gameplay

**Comment by TheRadziu** [comment]
so... the game crashes within 5 minutes of gameplay no matter where you are in the game, or just crashes at certain spot in the game?

**Comment by cesar19004** [comment]
it happens when you cross [this door ](https://youtu.be/MnUhbm-g8AA?t=365) (  minute 6:05  ).
there are no textures, you can only see the sky and if you die the game gets stuck in load screen

**Comment by cesar19004** [comment]
it happens when you cross [this door](https://youtu.be/MnUhbm-g8AA?t=365) ( minute 6:05 ).
there are no textures, you can only see the sky and if you die the game gets stuck in load screen

**Comment by harleyknd1** [comment]
report it to NPS instead, PKGJ doesn't maintain the game database itself

**Comment by TheRadziu** [comment]
@harleyknd1 it might be caused by incorrect extraction, which would be pkgj's concern. 

Will try to download it via PC and check if same happens.

Other possible reason might be memory stick corruption on OP's ux0.

**Comment by cesar19004** [comment]
do you know how can I install a .pkg file? I downloaded via pc

**Comment by TheRadziu** [comment]
either NPS browser or do it manually using pkg2zip + zRIF
