### ISSUE TITLE
can't get list: std::bad_alloc

### ISSUE THREAD

**Issue by MegaPramuk** [blastrock/pkgj#235]
Version of firmware: 3.65 (Ensō)
Version of PKGj: 0.42

## Steps to reproduce the issue

- Refresh databases
- After PKGj finishing, refresh again

Obtained result: 
![2018-11-15-222234](https://user-images.githubusercontent.com/9656711/48582614-3eb65a80-e925-11e8-8c2f-0922c7953b1d.png)

Expected result: Refresh again with no error message

**Comment by harleyknd1** [comment]
Change the url's in your config, I had the same error but after updating the config it went away....

**Comment by guch8017** [comment]
Oh, I met the same problem, when using a server built by myself instead of nopaystation.
