### ISSUE TITLE
Error downloading persona 4 golden (usa)

### ISSUE THREAD

**Issue by ITh3MisT** [blastrock/pkgj#238]
Version of firmware: 3.68
Version of PKGj: v0.42

## error Fatal error: sceloOpen(ux0:patch/PCSE00120/sce_sys/param.sfo) failed: 0x80010002

- When I try to download persona 4 golden (usa) appear an error message and the application stops running

**Comment by blastrock** [comment]
Can you give me the exact steps to reproduce this?
