### ISSUE TITLE
cant reload list : cant execute SQL command : database disk image is malformed

### ISSUE THREAD

**Issue by aruna87** [blastrock/pkgj#242]
Version of firmware: 3.68
Version of PKGj: 0.41

## Steps to reproduce the issue

- open PKGj v0.42
- cant reload list : cant execute SQL statement : database disk image is malformed
- [insert the steps to reproduce the issue here]

Obtained result: cant install any apps/games
Expected result: can install any apps/games
[please make sure to add all possible details, like the title id (the 9-chars string in the left column) of the game you are talking about]

**Comment by blastrock** [comment]
Your database is corrupt, just delete ux0:pkgj/pkgj.db

**Comment by aruna87** [comment]
ive delete pkgj,trying toreinstall, now i got error 0x8001002F

**Comment by TheRadziu** [comment]
sounds like ux0 corruption tbh. If its 64gb vita memory card it might be failing already.

**Comment by aruna87** [comment]
its....128gb...so no fix?

**Comment by TheRadziu** [comment]
make a backup of your current microsd, check for corruption and try reformatting it. 

So far this issue is not related to pkgj.

**Comment by blastrock** [comment]
Also, databases are now stored as text files, so you can check if they are corrupted by opening them on a computer
