### ISSUE TITLE
HttpError:bad http status: 404

### ISSUE THREAD

**Issue by koogelpotato** [blastrock/pkgj#243]
Version of firmware: 3.65
Version of PKGj: 0.43

## Steps to reproduce the issue

- update pkgj from 0.42 to 0.43 vpk 
- (no games list)
- refresh
-while refreshing get HttpError: bad http status: 404

Obtained result: error and inability to download games
Expected result: fixed error

[please make sure to add all possible details, like the title id (the 9-chars string in the left column) of the game you are talking about]

**Comment by calos9999** [comment]
Remove the files from ux0:pkgj folder, reinstall config.txt with autoplugin and refresh data

**Comment by blastrock** [comment]
There's something wrong with your config, probably unrelated to 0.43

**Comment by blastrock** [comment]
Remove all the urls from your config and use pkgj 0.44
