### ISSUE TITLE
attempting to install giives error 0xffffffff

### ISSUE THREAD

**Issue by timewreck24** [blastrock/pkgj#244]
Version of firmware: [3.68]
Version of PKGj: [0.43]

## Steps to reproduce the issue

- downloaded update through the download update option on opening version 0.42
- went to vitashell and attempted to install it

Obtained result: error: 0xffffffff
Expected result: successful install
also, now when i try to ss the error, or anything, my vita says in top left corner "an error has occurred" in a grey bubble. no error code for that just the text quoted. i would add a ss of the error happening, but the ss is corrupted when i try to view it although it seems to save it.

**Comment by TheRadziu** [comment]
Sounds like ux0 corruption.

**Comment by timewreck24** [comment]
i sure hope not, everything else installs fine via .vpk files though, so i dont know if this is ux0 corruption, but lets hope that isnt the issue.

**Comment by timewreck24** [comment]
also tried it again just now, and a different error is now being returned consistently. 0x8001002f is the new error.

**Comment by blastrock** [comment]
Closing this as it seems unrelated to pkgj
