### ISSUE TITLE
Cant get list

### ISSUE THREAD

**Issue by RichieAbuget** [blastrock/pkgj#245]
Version of firmware: [3.68]
Version of PKGj: [vO.43]

## Steps to reproduce the issue

- [cant get list: HttpError: sceHttpSendRequest failed: 0x8041013d]
- [after i update pkgj from pkgj app there is no game list]
- [and when i try to refresh , that error notice just appear]

**Comment by iorbon** [comment]
Same here. Since 0.43 I have the same problem, and it's not us only, in reddit there is a lot of people with the same problem. I updated the urls by autoplugin but still don't work.

Till 0.43 everything was working ok. 

Thank you for the hard work!

**Comment by ZombieGarou** [comment]
Maybe try this guys:
https://www.youtube.com/watch?v=Ha0e5pBdIzY

Worked for me.
But remember when typing in the Spoofed Version to use 3.69 since its the latest version.

**Comment by iorbon** [comment]
It worked thank you. But still I don't know why till 0.42 it worked ok without doing this 🤔

**Comment by ZombieGarou** [comment]
Youre welcome,happy taht it worked.

And yeah for me it suddenly stopped working twice,dont know what made it go crazy..

**Comment by micbuffa** [comment]
Well, I have the exact config from the YT video, but I still can't refresh the list. It says "can't get the list". I have the latest nonpdrm plugin installed etc.

**Comment by micbuffa** [comment]
I manage to fix that by installing the autoplugin.vpk app, that has a menu for installing a proper config.txt for pkgj. I also created manually a ux0:pkgj folder. This fixed the problem. I hope this helps.

**Comment by OffNix** [comment]
> Version of firmware: [3.68]
> Version of PKGj: [vO.43]
> 
> ## Steps to reproduce the issue
> * [cant get list: HttpError: sceHttpSendRequest failed: 0x8041013d]
> * [after i update pkgj from pkgj app there is no game list]
> * [and when i try to refresh , that error notice just appear]

i had the same version and same problem
i deleted everything in the folder(including folder pkgj and the content of pkgi
using autoplugins option recreated the pkgj config.txt
because you are spoofing to version 3.69 you will need to disable the manual DNS while using the Refresh and Download, and advise you to reboot after you finished getting all the apps/games and set the DNS back to manual
hope this helps :)

**Comment by boypuro** [comment]
> > Version of firmware: [3.68]
> > Version of PKGj: [vO.43]
> > ## Steps to reproduce the issue
> > 
> > * [cant get list: HttpError: sceHttpSendRequest failed: 0x8041013d]
> > * [after i update pkgj from pkgj app there is no game list]
> > * [and when i try to refresh , that error notice just appear]
> 
> i had the same version and same problem
> i deleted everything in the folder(including folder) pkgj and the content of pkgi
> using autoplugins option recreated the pkgj config.txt
> because you are spoofing to version 3.69 you will need to disable the manual DNS while using the Refresh and Download, and advise you to reboot after you finished getting all the apps/games and set the DNS back to manual
> hope this helps :)

this helped me :)
