### ISSUE TITLE
Can't get list erro 0x80431075 HTTPS URLs not supported device.

### ISSUE THREAD

**Issue by L3nnux** [blastrock/pkgj#247]
Version of firmware: [3.65]
Version of PKGj: [0.43]

Try Download Comppack Pack and not working.

"Can't get list: HttpError: sceHttpSendRequest failed: 0x80431075
HTTPS URLs may not be suported on your device.
Try with HTTP."

any help?

**Comment by FmT0** [comment]
Seems to be a TLS1.2 Problem. I have same problem, website is now using tls 1.2 Change https to http doesn't solve anything. 
Until this issue [https://github.com/SKGleba/iTLS-Enso/issues/3](url) is not resolved we cannot use pkgj to download compack from this tls 1.2 website anymore...

**Comment by fonkfader** [comment]
a workaround is to change the url for url_comppack with : http://proxy.nopaystation.com/https://gitlab.com/nopaystation_repos/nps_compati_packs/raw/master/

source : http://nopaystation.com/pkgj/config.txt
