### ISSUE TITLE
Cant get list

### ISSUE THREAD

**Issue by Trulydark** [blastrock/pkgj#248]
Version of firmware: 3.68
Version of PKGj: 0.43

HttpError: sceHttpSendRequest failed: 0x80412113
## Steps to reproduce the issue

- try to refresh my lists

Obtained result: it don't wanna refresh
Expected result: refresh the dang list

So I was trying to use pkgj and a error automatically popped up about the list so I deleted my list and tried to refresh and now I'm getting this problem.

**Comment by blastrock** [comment]
Try removing all the urls from the config and use pkgj 0.44
