### ISSUE TITLE
can't get list

### ISSUE THREAD

**Issue by citrabatam** [blastrock/pkgj#249]
Version of firmware: [3.65]
Version of PKGj: [0.43]

HttpError: sceHttpSendRequest failed: 0x80436003

- try refresh list

Obtained result: can't get list
Expected result: refresh list

[please make sure to add all possible details, like the title id (the 9-chars string in the left column) of the game you are talking about]

**Comment by blastrock** [comment]
That's SCE_HTTP_ERROR_RESOLVER_ETIMEDOUT, check your internet connection

**Comment by citrabatam** [comment]
Thanks ! It's working.Apparently, DNS settings was in manual, changed to automatic. Somehow while refreshing, encountered same error as described in #247 at 6/7 point. Followed fonfader and changed url_commpack in config.txt and refresh, no more error.

**Comment by TheRadziu** [comment]
https://github.com/blastrock/pkgj/issues/247#issuecomment-449083290 literally servers you with the answer how to fix it.

**Comment by citrabatam** [comment]
from the link, i change the url in config.txt with the proxy server, it doesn't work. do i miss something? appreciate some help. thanks.

**Comment by blastrock** [comment]
Just remove all the urls from your config with pkgj 0.44 and it should work.
