### ISSUE TITLE
Last result in TSV file not displayed in list

### ISSUE THREAD

**Issue by AnalogMan151** [blastrock/pkgj#25]
The very last result in the TSV file is not shown in PKGj's list, whether it be Games, DLC, update, etc. Adding an new entry to the end (even a bogus entry without PKG link or zRIF) causes the previously missing entry to appear. Will edit if I find error responsible.

**Comment by edale2** [comment]
This is why back in the day, EoF (End of File) tags were a thing, lol.

**Comment by blastrock** [comment]
Forgot to close this one, fixed by f682ae5
