### ISSUE TITLE
can't reload list: std::bad_alloc

### ISSUE THREAD

**Issue by ronnyc4** [blastrock/pkgj#250]
Version of firmware: 3.68 henkaku (3.69 spoof)
Version of PKGj: v0.43

## Steps to reproduce the issue

- open pkgj app
- choose show dlcs
- the error pops up. there is no list, asking me to refresh. but after refresh always same, the error keeps pops up

Obtained result: error when selecting show dlcs
Expected result: dlcs list got open normally

not seeing other get this error. is it just me?

**Comment by vitakev** [comment]
Did you sort it?
