### ISSUE TITLE
[Feature Request] Download Queue

### ISSUE THREAD

**Issue by Saix13** [blastrock/pkgj#255]
I have the following request:

- Download Queue
--Just like we have Triangle->Installed games only, it would be great to have an entry for Download Queue (Triangle->Download Queue)
--Perhaps using contentid.status files for all necessary data to read, display, and utilize queue?

Thanks!

**Comment by TheRadziu** [comment]
thanks to bgdl support introduced in v0.47 queue is now handled natively within livearea.
