### ISSUE TITLE
Adding support for PSP demos

### ISSUE THREAD

**Issue by Ziusun** [blastrock/pkgj#257]
I think adding url_psv_demo & url_psp_ demo would be a good thing since right now one always has to replace the PSV/PSP urls to dl a demo from nopaystation with pkgj.

**Comment by TheRadziu** [comment]
@nighto for example Catherine full body JP demo, full game is not out yet and not everybody wants to mess with account switching.

Also some games give you additional items and profits if you transfer your save from demo to full game.

**Comment by nighto** [comment]
Oh, I see, wasn't aware of that! Thanks for the explanation! 👍

**Comment by blastrock** [comment]
psv demos are now done
