### ISSUE TITLE
uma0:pspemu support

### ISSUE THREAD

**Issue by Localhorst86** [blastrock/pkgj#26]
I noticed that the psx game only install when the folder ux0:pspemu/psp/game exists.

Some people use uma0 for their adrenaline path, it would be great if we could tell pkgj to move psx games to uma0 instead.

**Comment by mrdude2478** [comment]
@Localhorst86 

You can check a folder exists - similar to this, if not create it:

int dfd;
    dfd = sceIoDopen("uma0:pkgi"); //check this folder exists
  	if(dfd <= 0)
  		{
  		sceIoMkdir("uma0:pkgi", 006);
  		}
  	sceIoDclose(dfd);
  	return "uma0:pkgi";

**Comment by tiduscrying** [comment]
With the addition of PSP games, this would be a really neat feature to at least have configurable with the pkgi.txt. Adding a line like "PSPEMU_LOCATION:" and allowing you to enter uma0, ux0, etc. would be ideal.

**Comment by blastrock** [comment]
Yup, I know this feature is much requested. Probably the next one that I will implement.

**Comment by nghiadhd** [comment]
I think PKGj is best plugin if we can allow selecting the location save file base on Vita Game/PS1/PSP
I have ux0 for PSV and umd0 for PSP/PS1 but when I download PSP/PS1 game from PKGj, I must copy it to umd0 manually. Otherwise, I must save free 2GB on ux0 as a temporary download directory

**Comment by blastrock** [comment]
Closed by a0b9368
