### ISSUE TITLE
can't reload list: failed to parse line 565: stoll

### ISSUE THREAD

**Issue by burtman316** [blastrock/pkgj#260]
Version of firmware: [insert version]
Version of PKGj: [insert version]

## Steps to reproduce the issue

 open pkgj 0.46
 select show psx games

Obtained result: [insert the result you got here]  can't reload list: failed to parse line 565: stoll
Expected result: [insert what you expected here] full list catalog

I know the Q is dumb but I tried all I could think of and couldn't fix it

**Comment by jricardorosasb** [comment]
That's happend to me too, it seem to be caused by the word "MISSING" in the tsv. Delete the word manually in the titles_psxgames.tsv file fix the problem.

**Comment by cvskid** [comment]
> That's happend to me too, it seem to be caused by the word "MISSING" in the tsv. Delete the word manually in the titles_psxgames.tsv file fix the problem.

I had the same problem. I deleted every part inside of the psxgames.tsv file that has the word "MISSING" and tried the file in pkgj 0.46 and i get a new error messages without the word "MISSING" being in the file.

can't reload list: failed to parse line 879: vector: :_M_range_check: __n (which is 8) >= this->size() (which is 8)

**Comment by niuus** [comment]
I started from scratch, tried to refresh and download the lists, the error is:
_can't get list: HttpError: HTTP download error 0x80431068_

**Comment by burtman316** [comment]
it appears to be fixed thamks
