### ISSUE TITLE
0.46 - cant get list with or without config.txt

### ISSUE THREAD

**Issue by admz0r** [blastrock/pkgj#261]
Version of firmware: 3.65
Version of PKGj: 0.46

## Steps to reproduce the issue

I updated recently to pkgj 0.46 from 0.45. Everything was working on 0.45/0.44 without using the config.txt. Made a fresh 0.46 install to a brand new Vita, didnt put the config.txt into its folder since its not needed anymore and like I said in 0.45 I could made it work that way. So when I try to refresh list, I keep getting this error: cant get list HttpError: sceHttpSendRequest failed: 0x8041210c OR cant get list HttpError: sceHttpSendRequest failed: 0x8041210b.

If i check its folder its making for itself (ux0:pkgj) after rI try to refresh, theres a 0 byte file called dbtmp.tsv and 2 comppack files 3-3 KiloBytes)

Tried to reinstall 0.45. Same problem remains. Tried 0.45/0.46 with config file included. Same problem.

So after the update I had to refresh the list, but it just not letting me, because Im getting that error message in the first step when its trying to refresh PSV games. I was using pkgj without any issues and out of nowhere this happened. Any ideas please? Thanks!

Obtained result: cant get list HttpError: sceHttpSendRequest failed: 0x8041210c OR cant get list HttpError: sceHttpSendRequest failed: 0x8041210b
Expected result: like it used to be. refresh game list

**Comment by blastrock** [comment]
These errors are SCE_NET_CTL_ERROR_NO_SUITABLE_SETTING_FOR_AUTO_CONNECT and SCE_NET_CTL_ERROR_AUTO_CONNECT_FAILED as explained [here](https://playstationdev.wiki/psvitadevwiki/index.php?title=Error_Codes). I don't know what auto connect is, but it seems related to your vita's configuration. Does your browser work?

**Comment by admz0r** [comment]
solved. had wifi signal but no internet somehow. opened a 3g hotspot, worked instantly. thanks for your reply
