### ISSUE TITLE
[bug] Missing Korean font

### ISSUE THREAD

**Issue by Yoti** [blastrock/pkgj#262]
How it must be:
루프란의 지하미궁과 마녀의 여단 추가퀘스트 [뭐! 인벤이라고!?]
루프란의 지하미궁과 마녀의 여단 추가퀘스트 [사랑을 담아서, 게임포커스!]
루프란의 지하미궁과 마녀의 여단 추가퀘스트 [사랑과 정열의 게이머즈]
루프란의 지하미궁과 마녀의 여단 추가퀘스트 [루리웹의 지하미궁]
루프란의 지하미궁과 마녀의 여단 추가퀘스트 [김소림의 선물]

How we see it:
![2019-01-26-022539](https://user-images.githubusercontent.com/1880088/51778439-ae5d7880-2112-11e9-83b0-8123927916de.jpg)

**Comment by Yoti** [comment]
Same for v0.47.

**Comment by Yoti** [comment]
Same for v0.51.

**Comment by cuevavirus** [comment]
Fixed in https://github.com/blastrock/pkgj/commit/785978fb903187622046ce3d19182aa3861814ee.
![2020-01-04-211912-138046](https://user-images.githubusercontent.com/53134627/71774239-41b14780-2f39-11ea-8f62-938bc879749e.png)
