### ISSUE TITLE
Download games error 0x80410141

### ISSUE THREAD

**Issue by JorgeAndres2** [blastrock/pkgj#265]
Version of firmware: 3,65
Version of PKGj: 0.47

I put to download a game and show:

Failed to install XXX game : SceDownload change_state DC0 failed 0x80410141

**Comment by blastrock** [comment]
Sadly, we don't know yet what the error code mean. Check that you have enough available space, that your internet connection work, etc. If you find out what is the issue, please tell me.

**Comment by Juliankyo** [comment]
JorgeAndres2, 
I have also encountered the same error for almost a week now. 
What I did was going back to version 0.43, and seemed to have fixed the issue. However, I am now unable to see DLCs or PSX games and stuff, only games.

**Comment by jlee597** [comment]
It was an internet connection issue for me. Check your DNS settings. I had mine set to 212.47.229.76 which was causing the issue.

**Comment by p16774** [comment]
Would be good to update the errors with valid text in the pkgj message, if possible, once we know (or test) what they are. I just found this error and realized it was because I didn't have an internet connection

0x80410132 = No Internet Connection (fw 3.68, US)

**Comment by ushilives** [comment]
I sorted out someones ps vita and has the same issue. He is on 3.65 Enso with latest version of pkgj. If the ps vita game is under 1gb it works, if it is over 1gb it comes up as the same error

**Comment by Xeddius** [comment]
> I sorted out someones ps vita and has the same issue. He is on 3.65 Enso with latest version of pkgj. If the ps vita game is under 1gb it works, if it is over 1gb it comes up as the same error

This sounds like a storage issue, make sure there's enough memory to download the games, keep in mind even if the game is 2G and you have 2.3G of free space, it might still error out. I had similar issues and resolved it by clearing up free space.

**Comment by nivardojr** [comment]
> > I sorted out someones ps vita and has the same issue. He is on 3.65 Enso with latest version of pkgj. If the ps vita game is under 1gb it works, if it is over 1gb it comes up as the same error
> 
> This sounds like a storage issue, make sure there's enough memory to download the games, keep in mind even if the game is 2G and you have 2.3G of free space, it might still error out. I had similar issues and resolved it by clearing up free space.

yes it is, I found out that I was out of memory and that's why that error appears, to solve it, we just need free space

**Comment by cuevavirus** [comment]
0x80410141 is SCE_NET_ERROR_EHOSTUNREACH and not a problem of pkgj.

**Comment by nowhereman87** [comment]
Turning off wifi energy saving mode worked for me ;)
