### ISSUE TITLE
Request PSV update support for games not included in PKGj PSV game list

### ISSUE THREAD

**Issue by Honeylife77** [blastrock/pkgj#267]
Version of firmware: 3.68
Version of PKGj: 0.47

Request PSV update support for games not included in PKGj PSV game list

Ex) Mai dump

Previously, MAI dump game can be applied and executed by PSV game updating it on PKGj, but it is not listed anymore, so it is inconvenient because game update is not possible.

Or tell me how to update games that are not on the PKGj game list through PSV_UPDATES.tsv.

**Comment by f150fordspecs** [comment]
Well this time everyday games come in a market but where to find the best game reviews my recommendation this is the best site but if you want to know more news about game review then click the link below 
[https://ibixion.com/4gb-ram-game-list.html](url)
