### ISSUE TITLE
[Feature Request] Live Area downloader for PSP, PSX games

### ISSUE THREAD

**Issue by EriolGaurhoth** [blastrock/pkgj#269]
On the heels of the most excellent new version that allows PSV games to be downloaded via Live Area and automatically installed into bubbles, doing the same for PSP and PSX titles would be fantastic.  Unless I'm missing something, these types of games still download the old way and are only playable via Adrenaline instead of using the Vita's built-in mechanism for playing PSP and PSX games that are conventionally downloaded from PSN.

**Comment by TheRadziu** [comment]
psp/psx requires more research, especially something like nopspemudrm to exist, since adrenaline can't do it on its own.

**Comment by dicelander** [comment]
Does anyone know where the PSX digital software manuals that show up in officially installed bubbles come from? It would be pretty nice to have support for that too.

**Comment by KuromeSan** [comment]
> Does anyone know where the PSX digital software manuals that show up in officially installed bubbles come from? It would be pretty nice to have support for that too.

DOCUMENT.DAT
