### ISSUE TITLE
Can't install game updates Error code: C0-12574-9

### ISSUE THREAD

**Issue by ShineNee** [blastrock/pkgj#270]
Version of firmware: [3.68]
Version of PKGj: [v0.47]

## Steps to reproduce the issue

PS Vita Status: Spoofed Version: 3.69
- Open pkgj v0.47
- Search "The Legend of Heroes: Sen No Kiseki II (CHI)" (GameID: PCSH00075, Region: ASA)
- install the game
- Close pkgj and then find the game bubble (game runs perfect without updates)
- tap the refresh icon, and then system will tell you that updates are available, download game updates through LiveArea.
- Wait untill game updates downloaded.
- Install game updates.
- Get error: Can't install updates, Error code: C0-12574-9

PS: I've tried to install plugin reF00D.skprx to try to run the game with updates, but failed to fix the problem. Also tried to change spoofed version to 3.70, but also failed.

Obtained result: [Can't install updates, Error code: C0-12574-9]
Expected result: [game runs perfect with installed updates]

**Comment by DYRM3006** [comment]
Same here I've been looking for this I'll post up if I find anything NEW**

**Comment by ShineNee** [comment]
I've tried this patch on both PSV & PSTV, but it  seems that I just can't install it.

**Comment by ShineNee** [comment]
Pls. close file. I've got the problem fixed by redownload game via PKGJ, and amazingly patch 1.03 was installed successfully. Thanks.
