### ISSUE TITLE
Can't download themes

### ISSUE THREAD

**Issue by DodoDudus** [blastrock/pkgj#275]
Version of firmware: 3.65
Version of PKGj: 0.48

## Steps to reproduce the issue

- Open PKGj v0.48
- Try to download any theme 
- Get error: "Failed to install [example: Uncharted: Golden Abyss] theme: SceDownload change_state DC0 failed: 0x80103a19

Same error appeard in PKGj v0.47 EDIT: and PKGj v0.49 too

Obtained result: Can't download themes
Expected result: Download and install themes

**Comment by TheRadziu** [comment]
Update pkgj to latest (0.52) and make sure you have nonpdrm installed.
