### ISSUE TITLE
PSP DLC installation doesn't follow adrenaline installation.

### ISSUE THREAD

**Issue by yatsukiko** [blastrock/pkgj#277]
Version of firmware: [3.60]
Version of PKGj: [0.48]

## Steps to reproduce the issue

- Launch pkgj
- Look up any psp dlc 
- Try to install

Obtained result: Installs in default adrenaline location, ux0:pspemu/psp/game/<titleid>
Expected result: Installs in custom adrenaline location, <specified location>/pspemu/psp/game/<titleid>

This happens only with psp dlcs, any psp dlc.

**Comment by cuevavirus** [comment]
Fixed in https://github.com/blastrock/pkgj/commit/fdee8b3b5b6dbc951a0f77f99abf68f542f3fffc.
