### ISSUE TITLE
Error 0x80871007

### ISSUE THREAD

**Issue by limonetas** [blastrock/pkgj#279]
Version of firmware: [3.68] + H-encore 2.0 (already new)
Version of PKGj: [v0.48]

## Steps to reproduce the issue

downloading the new version pkgj v0.49, trying to install by VitaShell and kbum error 0x80871007, trying restarting and re-downloading the file ... nothing.

![img_20190219_162709](https://user-images.githubusercontent.com/47794002/53042229-8be62300-3464-11e9-90a9-9d73434af3d8.jpg)

**Comment by blastrock** [comment]
Try restarting your vita?

**Comment by limonetas** [comment]
> 
> 
> Try restarting your vita?

I already said it and it's very clear you see in the op.
"trying restarting and re-downloading the file ... nothing"

**Comment by limonetas** [comment]
> Try restarting your vita?

Well, I already solved it, the problem was the new H-Encore 2.0, regards
