### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by Darkau** [blastrock/pkgj#280]
Version of firmware: 3.60
Version of PKGj: 0.49

## Steps to reproduce the issue

- Hack of the vita
- Install SD2VITA+NoNpdrm
- Try to install a game

Obtained result: Failed to install: SceDownload change_state DC0 failed: 0x80103a0e
Expected result: The download should be starting.

The second time I try to download anything I get: Failed to intall: SceDownload change_state bgdlid failed: 0x000000.

**Comment by DYRM3006** [comment]
Probably  the way u installed Sd2vita u need to look at setting I'll upload my config.txt so u can see how I did it*

**Comment by AragamiLaw** [comment]
so, how the right config?

**Comment by aueoaueo** [comment]
So whats the fix???
