### ISSUE TITLE
Error "Game not found"

### ISSUE THREAD

**Issue by astrave** [blastrock/pkgj#281]
Version of firmware: 3.65
Version of PKGj: 0.49

- Install games. eg. Little Big Planet, Ridge Racer, Uncharted
- Install last patch for games
- Run

Obtained result: after 5-10 loading sec i have infinite errors "Game nor found| and freez vita

Another gamer run correct. ux0 is sd2vita with 128GB Microsd

**Comment by DYRM3006** [comment]
Don't install patch try that*

**Comment by astrave** [comment]
> Don't install patch try that* install game then refresh live
Ridge Racer dont have patch. Only game... and have same error. And i found one more game with this problem. Unit 13

**Comment by astrave** [comment]
Problem solving. It consisted in the fact that I deleted the standard applications of the system. It was probably a matter of removing parental control.

**Comment by DYRM3006** [comment]
Any Pcontrol will have to be enable or bypassed.. will have affect on any installations

**Comment by DYRM3006** [comment]
Or backup card an reinstall fresh copy

**Comment by astrave** [comment]
The whole thing was not in parental control. In the "near" .. not even in the application itself, but in its services (vs0: app / NPXS10024-25-32).
