### ISSUE TITLE
pending instalations

### ISSUE THREAD

**Issue by inlinealex** [blastrock/pkgj#282]
Version of firmware: [3.68]
Version of PKGj: [v0.49]

## Steps to reproduce the issue

- [download a lot of games]
- [then warning starts to appear]

Obtained result: [i get an error message]
Expected result: [to download the game]

now any game i try and download it tells me "there are too many pending installation on your device, install from live areas notifications or delete them to be able to download more." 

i have no pending downloads i have deleted all notifications. i have removed pkgj completely and reinstalled im not sure what has happened is there any way to recover this without starting from scratch?

**Comment by blastrock** [comment]
You have too many folders in ux0:bgdl/t, you can delete them manually, but they should be deleted automatically when you remove a download from livearea

**Comment by NERDforeverNF** [comment]
Thank you blastrock I had this issue and couldn't find where to manually remove them but I'm all good now thank you really. AND THANK YOU SO MUCH FOR YOUR WORK IN THIS COMMUNITY you've done so much for us all really
