### ISSUE TITLE
[BUG] Psp download error (Download failure : pkg is not supported, files are in wrong order)

### ISSUE THREAD

**Issue by animekai** [blastrock/pkgj#286]
Version of firmware: [3.60]
Version of PKGj: [0.50]
When i want to download a psp game, gives me error

Download failure: pkg is not supported, files are in wrong order, expected: 569312,actual: 569008

Minis and pc engine looks fine just psp games isos wont work.

Edit: pc engine doesnt work either

**Comment by blastrock** [comment]
Please give the title id of the package that doesn't work

**Comment by animekai** [comment]
i tried as much psp and pc engine games, everyone doesnt work, just minis, i tried at least 20 of them from top to bottom, is a large list to test every game, but i assume is all psp and pc engine games

**Comment by liraman** [comment]
I have the same problem 

i've tried Capcom Classic Collection USA  and  Europe
Capcom Classic Collection Deluxe  USA and Europe ( i dont remember the exact name)

and Final Fantasy IV complete Collection JAPAN

all of them give me the same message, wrong order (some number) should be (some number)

i know there are other means for aquire those games , i just want to point it out

Regards

**Comment by blastrock** [comment]
Retry with pkgj 0.51
