### ISSUE TITLE
Game patch download error 0x80871c04

### ISSUE THREAD

**Issue by Slowyata** [blastrock/pkgj#288]
Version of firmware: henkaku 3.68
Version of PKGj: 0.51

## Steps to reproduce the problem 

- downloading a patch for a game I already  have installed on my psvita I'm getting an error at the end of the download. The download will go to 99% and throw this error. But if I install a game and patch together from pkgj the patch will download fine. 

download failure scepromoterutilitypromotepkgwithrif failed: 0x80871c04

**Comment by Slowyata** [comment]
Pkgj version .51

**Comment by Originalimoc** [comment]
Same

**Comment by billybob2010** [comment]
same

**Comment by Xyphoseos** [comment]
same

**Comment by AragamiLaw** [comment]
up

**Comment by ryanzb** [comment]
same. trying to d/l umvc3 patch 1.02

**Comment by imedox** [comment]
same

**Comment by EpicLPer** [comment]
Same right now...

**Comment by cuevavirus** [comment]
Please update through the livearea instead of through pkgj. This method of installing patches was only to support PSTV users using antiblacklist/whitelist. But now that we have [DolcePolce](https://github.com/KuromeSan/DolcePolce) this feature is no longer needed and will be removed per #324.

**Comment by EpicLPer** [comment]
> Please update through the livearea instead of through pkgj. This method of installing patches was only to support PSTV users using antiblacklist/whitelist. But now that we have [DolcePolce](https://github.com/KuromeSan/DolcePolce) this feature is no longer needed and will be removed per #324.

Oh? Didn’t even know there’s a new way. Had my Vita laying around basically since the very first SD2Vita adapter came out 2 or so years ago and haven’t looked much into new stuff yet :)
If you have any more awesome new things like this to share I’d be more than happy ;)

**Comment by cuevavirus** [comment]
Patch download button removed in version 0.55.
