### ISSUE TITLE
ERROR 0x80103a01

### ISSUE THREAD

**Issue by Orixah** [blastrock/pkgj#289]
Version of firmware: 3.68
Version of PKGj: .51
I was using sd2vita and this happened to me twice i did looked it upon google but it was showing the older version of the app so its irrelevant and i try those and none work

1,Download a game and it will download via 
2,Then shut down the vita and open it again and when you go to pkgj again it gives you the SceDownload change_state DC0failed:error 0x80103a01

Obtained result: the data is eaten and i dont know where it went 
Expected result: automatically delete the data

Please help

**Comment by Xeddius** [comment]
Make sure there are no downloads currently active in your notification panel. If they are, cancel them and retry.

**Comment by MrWingie** [comment]
Can confirm.
Version of firmware: 3.60
Version of PKGj: .51

If SD2VITA is set as ux0 I get the errors described above. When switching back to my Sony Memorycard as Ux0 with the exact same setup no errors appear.
There´s definately enough space on my SDcard and everything is set up the right way.

**Comment by Xeddius** [comment]
@MrWingie Make sure the SD2VITA is actually functioning, I've had issues with mine not becoming active and everything still using the VITA memory card.

**Comment by MrWingie** [comment]
Mine is working properly, I made sure.

**Comment by MrWingie** [comment]
One more note:
I found, that not the SD2Vita was the problem, but the microSD. I bought a cheap one which was supposed to be 256GB, but only had 32GB. Hope this helps anyone.

**Comment by j1r2m3** [comment]
Tengo el mismo error alguien que me ayude
