### ISSUE TITLE
New LiveArea design of PKGj

### ISSUE THREAD

**Issue by JesterIOS** [blastrock/pkgj#29]
My view on how **PKGj** might look in LiveArea:

- App icon [icon0]

![icon0](https://user-images.githubusercontent.com/30769120/38164889-88aaa276-3535-11e8-9ec9-bafa1547dc53.png)

- StartUp button [startup]

![startup](https://user-images.githubusercontent.com/30769120/38164898-b122dce6-3535-11e8-9c32-1cd93678eff3.png)

- LiveArea background [bg]

![bg](https://user-images.githubusercontent.com/30769120/38164904-c7fb687a-3535-11e8-9732-5be04c9a099b.png)

**Comment by blastrock** [comment]
Wow, thanks! I'll integrate these soon enough

**Comment by edale2** [comment]
Nice! Looking forward to the upgrade!

The [bg] one might make a good background for while PKGj is running as well, imho.

**Comment by JesterIOS** [comment]
Maybe we should change name of the project? I mean, "PKGj" so strange...

**Comment by edale2** [comment]
"PKG" because it works with PKG files, "j", because it's the version after "PKGi".

Makes sense to me.

**Comment by blastrock** [comment]
I tried putting your images in pkgj but when I do, it fails installing with the error 0x8010113D. I don't have the time to investigate it right now.

**Comment by edale2** [comment]
https://github.com/TheOfficialFloW/VitaShell/issues/312

Looks like you just need to convert all the images to 8-bit PNG.

**Comment by edale2** [comment]
https://pngquant.org/

Apparently running the images through that program can help.

**Comment by edale2** [comment]
I converted them to 8-bit PNG, try these ones:
[8-bit-pkgj.zip](https://github.com/blastrock/pkgj/files/1866812/8-bit-pkgj.zip)

**Comment by edale2** [comment]
And looks like it worked.

From what I found, images from the src_sys folder have to be 8-bit PNG, while pretty much every other image on the Vita can be 24-bit PNG.

**Comment by blastrock** [comment]
Yup, thanks for for your help on that! :)

**Comment by edale2** [comment]
Yep. I tend to not have the skills to do any real hacking/modding, but got plenty of skills to help on the periphery of projects, especially the most precious of all... Free time, lol.
