### ISSUE TITLE
C2-12828-1 only on PSVita games 

### ISSUE THREAD

**Issue by fellipechagas** [blastrock/pkgj#290]
Version of firmware: 3.60
Version of PKGj: 0.51

## Steps to reproduce the issue

- Opens my PKGj
- Click to download any PS Vita game
- App gets an error and shutdown

It just happens with PSVita games, PSP/PSX download correctly.

Obtained result: c2-12828-1 and my app closes.
Expected result: Download my PSVita games.

**Comment by fellipechagas** [comment]
The error was that i do not uptaded properly my HENkaku, sorry for bothering y'all folks.

**Comment by idoyski** [comment]
how did you fix the problem mate?
