### ISSUE TITLE
Games won't load but patches do.

### ISSUE THREAD

**Issue by Dimonamik** [blastrock/pkgj#292]
Since my vita crashed while downloading a game i can't download any games anymore, but strangely patches download without any issue. I tried using other versions of pkgj, but it just wont work again. Help pls.

**Comment by TheRadziu** [comment]
most likely nonpdrm not being loaded, check it and report back.

**Comment by ElKrapulito** [comment]
I had a similar problem, only the patches were downloading so i did what @TheRadziu recommended and right now it seem that is working, the download started of a  vita game, hopefully the game will work too.
