### ISSUE TITLE
Problem with PSX list PKGJ 0.51(can't reload list: failed to parse line 902: stoll)

### ISSUE THREAD

**Issue by Tonykcs** [blastrock/pkgj#293]
Version of firmware: 3.68
Version of PKGj: 0.51
can't reload list: failed to parse line 902: stoll

Whe I installed the 0.51 version of PKGJ and I refreshed the complete list of games I had a problem with PSX games, I can´t refresh correctly, all PSX EUR games disappeared and appears this error: can't reload list: failed to parse line 902: stoll

**Comment by tattyapollo** [comment]
I personally found that using a text editor (not the one on the vita) and removing that line (line 902 in you case) works fine when i got this issue

**Comment by Tonykcs** [comment]
how kind of program to edit?

**Comment by tattyapollo** [comment]
Literally, move ux0:pkgj/titles_psxgames.tsv to your computer, use your favorite text editor, and remove line 902 completely. I personally recommend notepad++ for a text editor, makes finding what line number your on easy without word wrapping.

**Comment by Tonykcs** [comment]
This works. THANKS!
