### ISSUE TITLE
[bug] Show PSM games not shown while using search

### ISSUE THREAD

**Issue by Yoti** [blastrock/pkgj#294]
Version of firmware: 3.60
Version of PKGj: 0.51

## Steps to reproduce the issue

- Use search option
- Open PKGj menu
- Show PSM games is under screen

Obtained result: menu entry not shown
Expected result: menu entry must be shown

I think it's right time to reorganize menu.

**Comment by cuevavirus** [comment]
PSM games and search are working normally. If PSM games are not showing, please carefully read the PSM section in the readme.

**Comment by RealYoti** [comment]
@cuevavirus did you see that's opened by me? When you using search option you will get one additional menu line with search text. So, last option (psm games) is moved under the visible part of screen.

**Comment by Yoti** [comment]
@cuevavirus did you see that's opened by me? When you using search option you will get one additional menu line with search text. So, last option (psm games) is moved under the visible part of screen.

**Comment by cuevavirus** [comment]
Sorry I see the problem now

**Comment by cuevavirus** [comment]
Fixed in https://github.com/blastrock/pkgj/commit/53cd84dd2f38ae336788970221f891d79b2c12dd
