### ISSUE TITLE
Updates and DLC downloading, but not installing

### ISSUE THREAD

**Issue by QThatoneguy** [blastrock/pkgj#295]
Version of firmware: 3.65
Version of PKGj: 0.51

## Steps to reproduce the issue

- Begin installation of game/DLC
- Go to livearea to wait for completion and installation
- After waiting to install message, attempt to boot game and it doesnt add content
Obtained result: Data installs on the livearea, doesnt add content just downloaded
Expected result: Use pkgj to download files, start game up and play new content

I just opened my PSTV up with wifi again after having it disconnected for a month, so I updated to the more recent version of apps. Went from 0.46 to 0.51 in pkgj. After file gets to 100% download the message always changes to waiting to install in the livearea. After that, I boot the game that I got the DLC for. It checks the content and proceeds like normal. I tried this for PSP DLC too with Dissidia 012 Final Fantasy with all of the characters and costumes, but that doesnt work either. That just pops up as corrupted data. I know nonpdrm works because PSX games still download and work.

**Comment by H0R1Z0N** [comment]
PS TV 3.60, PKGJ 0.51, same error.

**Comment by H0R1Z0N** [comment]
It seem we are not alone https://www.reddit.com/r/VitaPiracy/comments/b8r99m/help_with_installing_dlc_from_pkgj_not_installing/

**Comment by Seannor** [comment]
PSP DLC downloaded through pkgj all 0 sized.  3.68 Henkaku/0.51 pkgj.

**Comment by H0R1Z0N** [comment]
I am willing to beta test your fix attempt, just notify us here when you compile new alpha test. At less, if you don't own a PS Vita TV. I was downloading with wifi btw.

**Comment by QThatoneguy** [comment]
Someone suggested rebuilding the database on another site, but unfortunately my PSTV is at my moms place out of town so I currently cant test it out.

**Comment by H0R1Z0N** [comment]
Well, i did not rebuild it but had problem mounting the drive, so it kinda updated the database with nothing and full of game multiple time. Not happening on my vita 1K, i was using a very old version before which was working on my Vita TV.

**Comment by QThatoneguy** [comment]
Alright so I finally got back to my system and I can say I successfully fixed it by rebuilding the database, everything is smooth as far as I can tell.

**Comment by Yamada-Tech** [comment]
Trying unpatch AntiBlackList

**Comment by NeoTechni** [comment]
It is the antiblacklist, but removing it/reapplying it is a real pain. Could you add an option to go back to the old method of downloading? I'm staying on 0.46 because of it, but it keeps getting an SceIODread error...

**Comment by TheRadziu** [comment]
Completly undo and remove antiblacklist, then install new plugin DolcePolice, it's complete replacement for antiblacklist, of course without issues like this one.

https://forum.devchroma.nl/index.php/topic,58.0.html

Plugin will be added to readme under Q&A and legacy update downloading method will be removed from next pkgj update (since from now on, thanks to that plugin, its considered obsolete)
