### ISSUE TITLE
can't get list

### ISSUE THREAD

**Issue by lanner** [blastrock/pkgj#297]
Version of firmware: 3.65 
Version of PKGj: 0.51

 using REFRESH

"can't get list: failed to parse line
patch/PCSGO1249/PCSGO1249---.ppk
regex didn't match"

i have install in lot of PS VITA and it's the first time i have this error

**Comment by fettesb** [comment]
Version of firmware: 3.68
Version of PKGj: 0.51

same happened to me

**Comment by lamlam77777** [comment]
Seems pkgj is not support NPS 3.0 yet

**Comment by lanner** [comment]
i see that in nps discord yep

**Comment by Phyton69** [comment]
Version of firmware: 3.68
Version of PKGj: 0.51

same happened to me, what can I do to fix it

**Comment by TheRadziu** [comment]
Make sure that:
- pkgj is updated to latest version (0.52)
- `/pkgj/config.txt` has no custom url overrides 
- NoPayStation domain is accessible on the other devices, as for now russian citizens can't access it due to server range being blocked (some anti-homo law, idk)
