### ISSUE TITLE
Error code C0-9250-5

### ISSUE THREAD

**Issue by Kasarisenpai** [blastrock/pkgj#303]
Version of firmware: 3.68
Version of PKGj: 0.51

## Steps to reproduce the issue

- Find game in PKGj and install it
- After selecting install, a message shows saying it's queued on LiveArea
- Immediately get an error message with the error code C0-9250-5
- Refresh LiveArea on Vita Shell, but it says 0 items were refreshed

Obtained result: Game doesn't install
Expected result: Game to install

So I tried to install multiple games just to test, and every single time that error comes up. A bubble doesn't even show on the main screen. I used AutoPlugin (v3.92) to install NoNpDrm and NoPsnDrm in ur0 so I'm not sure what the problem could be since I don't really understand any of this. Is there any way to fix this?

**Comment by cuevavirus** [comment]
Please install the newest version of pkgj and confirm that nonpdrm is active.
