### ISSUE TITLE
PKGj is Sayig Games are installed that actually aren't

### ISSUE THREAD

**Issue by takuhii** [blastrock/pkgj#305]
Version of firmware: 3.65
Version of PKGj: 0.51

## Steps to reproduce the issue

Try to Install a Game
Obtained result: Game Downloads but doesn't install, but also I can't remove it
Expected result: Game downloads and installs

So I pick a game, in this instance Crazy Taxi Fare Wars, it downloads then does nothing, when I try to interact with the game in the PKGj menu, it tells me that is is already installed... What is odd is that it is telling me I have game installed that I don't, one in particular "Adventures to Go", I have checked the PKGj folder and there are no directories or any files that match what I have downloaded... Any ideas?

**Comment by VaterlandsGarde** [comment]
Download Adrenaline and press memory card there u will see all psp psx games ant press triangle to option/delete
