### ISSUE TITLE
can't get list: failed to parse line patch/PCSG1035/PCSG1035--.ppk regex didn't match

### ISSUE THREAD

**Issue by Safio1** [blastrock/pkgj#306]
Version of firmware: [3.68]
Version of PKGj: [0.51]

## Steps to reproduce the issue

- Refresh

Obtained result: can't get list: failed to parse line patch/PCSG1035/PCSG1035--.ppk regex didn't match
Expected result: refreshing

i tried to delete the app and reinstall it and that didn't work ?

**Comment by lanner** [comment]
Hi same error today, maybe it's her link's who have a problem

**Comment by felysu** [comment]
Same exact issue that happened with a fresh install of pkgj on a PSTV.
