### ISSUE TITLE
Exactly what parameters does config.txt suuport?

### ISSUE THREAD

**Issue by hgdagon** [blastrock/pkgj#308]
According to the readme the tsv update urls can be modified. However it doesn't state the following:

PSV Demos
PSV Updates
PSV Themes
PSP Updates
PSP Themes

Can these be configured/downloaded?

**Comment by blastrock** [comment]
Yes they can and the README is incomplete. An accurate list of the options can be found [here](https://github.com/blastrock/pkgj/blob/557a5ccadfea5663d66194a99b117a59904e6210/src/config.cpp#L226)

**Comment by hgdagon** [comment]
Oh, nice! That's what I've been looking for, however, I don't see PSP Themes (not important), PSV Updates and PSP Updates.

**Comment by blastrock** [comment]
pkgj doesn't support psp themes and psp updates. As for psv updates, the list from nps was outdated so it's not supported either, you can just download them normally from the livearea.

**Comment by hgdagon** [comment]
Got it. Thank you!
