### ISSUE TITLE
Everything else works except for updates

### ISSUE THREAD

**Issue by BlackRabbit22** [blastrock/pkgj#31]
Updates used to work fine a day ago but now they don't.

DLC, games, and everything else works except for updates.

**Comment by edale2** [comment]
If you're on Enso 3.65, you can just turn on PSN spoofing and log into your (preferably throw-away) PSN account, and you can get the updates directly from the PSN network.

On the start page of a game along the top an icon with an orange circle with a downwards facing arrow will pop up after a few seconds on Vita's that are logged into PSN and online. Clicking that icon will download the updates (after the update is done downloading, it'll install on the first run of the game).

If you're still on 3.6, I don't think PSN spoofing works (so you'd have to get this program working), but I'm not sure.

**Comment by BlackRabbit22** [comment]
@edale2 I am on 3.60 and the method you described works. 

Yeah I am using a throwaway.

**Comment by blastrock** [comment]
Can you give the titleid of the game you tried to update?

**Comment by BlackRabbit22** [comment]
It's not specific to a certain game, it happens to every game.
I'd get a list for updates available for every single game, but now I don't.

And I can give you the titleid of two games I tried to update:

Titan souls, and shovel knight.

**Comment by blastrock** [comment]
The titleid is the string on the left column. It also include the region of the game so that I can test the same thing as you.

**Comment by BlackRabbit22** [comment]
Sorry.
The title id is:
PCSB00720 EUR
PCSB00743 EUR

**Comment by edale2** [comment]
If you're not getting a list of updates at all anymore, you might want to check your config file to make sure the TSV link for updates is correct.

https://sites.google.com/site/theleecherman/vitagameupdatechecker
You can use that program to check a game's updates before you grab them, to make sure they won't require firmware past 3.6.

**Comment by N3evin** [comment]
Yup, same thing happen to me. Updates has no items. I am on enso 3.65, the link is correct.

**Comment by edale2** [comment]
Wow, I just checked, my list of updates is gone as well...

**Comment by edale2** [comment]
Verified the TSV is still up and populated on the NPS website, so it's not a problem on that end.

Also got hit by TheFlow's little April Fool's prank in VitaShell (protip, don't have a heart attack, just leave the error message... with a PS4 error code... up for a minute or two).

**Comment by edale2** [comment]
Went back to PKGj v0.08 and checked, Updates list is empty there as well.

There are some _slight_ formatting differences in the first line of the current PSV_Updates.TSV compared to one I grabbed a few days ago:

old one:
````Title ID	Region	Name	Update Version	FW VERSION	PKG direct link	NoNPDRM mirror	Last Modification Date	File Size	SHA256

New one:
````Title ID (2)	Region (1)	Name	Update Version (3)	FW VERSION (4)	PKG direct link (5)	NoNPDRM mirror	Last Modification Date	File Size	SHA256

**Comment by blastrock** [comment]
Oh I didn't understand that the list was completely gone, I'll make a release quick with the fix, thank you all.
