### ISSUE TITLE
Trying to update to latest version

### ISSUE THREAD

**Issue by Deadkid0** [blastrock/pkgj#310]
Version of firmware: [3.68]
Version of PKGj: [0.37]
 I haven't messed with my vita in a while and I noticed that I am using an outdated version of PKGJ and I was very curious on how to update it. I was gonna just install the latest vpk file but I didn't want to cause any issues as I couldn't even find a solution to my question online.

How can I update to the newest version? {tldr}

**Comment by RuggeDX** [comment]
Just install the newest VPK and make sure your config.txt is up-to-date as well

**Comment by Deadkid0** [comment]
> 
> 
> Just install the newest VPK and make sure your config.txt is up-to-date as well

How do I know to make sure my config file is up to date? I tried the vpk and now I get a can't get list error when refreshing the pkgj app.

**Comment by bombsimon** [comment]
@Deadkid0 It's been a temporary issue listing the files, see [this Reddit post](https://www.reddit.com/r/VitaPiracy/comments/e18tq0/psa_temp_solution_for_pkgj_issue/).

After applying that fix you should be able to refresh the list with PKGj 0.51. This is my current (working) content of `config.txt`:

```
url_comppack http://gateway.fast.sheridanc.on.ca/
install_psp_psx_location ux0:
```
