### ISSUE TITLE
can't reload list

### ISSUE THREAD

**Issue by teabarley** [blastrock/pkgj#313]
Version of firmware: 3.68
Version of PKGj: 0.51

## Steps to reproduce the issue

1. Open the app.

Obtained result: 
can't reload list: failed to parse line 2: vector::_M_range_check: _n(which is 10) >= this->size() (which is 10)

Expected result: 
launch successful or something

**Comment by TheRadziu** [comment]
Update your pkgj to latest version and then make sure that your `/pkgj/config.txt` has no custom url overrides
