### ISSUE TITLE
PKGI Livearea download interrupted

### ISSUE THREAD

**Issue by Edmarkson** [blastrock/pkgj#314]
Version of firmware: [3.65 enso]
Version of PKGj: [0.51]

So I was downloading Ys VIII a while ago when I accidentally rebooted my psvita while downloading. After that, download failed due to interruption. I cancelled the download on the livearea and deleted it but the space used by the download is still there.

I’ve search Vitashell including PKGI folder but I can’t find the failed download folder of the game. It’s not in the pkgi folder of ux0. I’m using SD2Vita

Please help me @blastrock as  it’s been eating my storage

**Comment by TheRadziu** [comment]
it's in `ux0:bgdl/t/` if i recall correctly.
