### ISSUE TITLE
Some DLC just won't download

### ISSUE THREAD

**Issue by metalPiko** [blastrock/pkgj#32]
Version of firmware: 3.65 enso
Version of PKGj: 0.11 (shows as 0.10)

Just trying to download the dlc of Digimon: Hackers memory, while some download fine, others won't even start at all. Like clicking into nothing. This being Omnimon NX and a few others. Haven't check if this problem is also present in other game dlcs but I'll assume its possible. What could possibly be the iddue? This persisted from 0.8 and seems the issue is still present on the latest release too.

**Comment by blastrock** [comment]
What is the region of the game?

**Comment by phonzeh** [comment]
I find you can only queue/download up to 4 titles and then it refuses to install anything else or refresh categories.

**Comment by metalPiko** [comment]
Sorry for the late reply but the only one available. US version.

**Comment by blastrock** [comment]
Please retry with the latest version, it should show you an error.

**Comment by ABDOULemul** [comment]
I have the same problem with dlc too.
Message is popping : 
ERROR
Download failure : cannot send HTTP request 
after few successfully downloads.

**Comment by blastrock** [comment]
Does it work if you retry the download?

On my part, I will improve these error messages with more detail and an error code.

**Comment by ABDOULemul** [comment]
No, same here.
Any Dlc or games can't be downloaded.
I close pkgi and relaunch.
After maybe 2 or 3 downloads, the bug appears.

**Comment by phonzeh** [comment]
After downloading exactly 4 titles via pkgj (ver 0.11 and 0.12) pkgj refuses to download anymore titles.
"ERROR Download failure: cannot send HTTP request"

ver 0.09 works fine for me though.

**Comment by blastrock** [comment]
I have fixed the 4-titles bug and I'm closing this since there are too many bugs in this thread. If you still have issues with v0.13, please open a new issue describing your bug.

**Comment by barbabarros** [comment]
thank you so much for your time and your work...

also, thank you for your feedback! 😊


________________________________
De: Philippe Daouadi <notifications@github.com>
Enviado: quarta-feira, 11 de abril de 2018 15:29
Para: blastrock/pkgj
Cc: barbabarros; Comment
Assunto: Re: [blastrock/pkgj] Some DLC just won't download (#32)


I have fixed the 4-titles bug and I'm closing this since there are too many bugs in this thread. If you still have issues with v0.13, please open a new issue describing your bug.

**Comment by ABDOULemul** [comment]
Thanks you for your work.
