### ISSUE TITLE
Face Buttons continue input in background while trying to use search function

### ISSUE THREAD

**Issue by SmokeyPSD** [blastrock/pkgj#321]
Hardware: [Both PSV and TV]  
Version of firmware: [3.60]  
Version of PKGj: [0.52]  

- Open Search, try to type a query with physical buttons
- multiple random downloads will be randomly queued up from all the input that has happened

Reverting to the last version solves this issue so I have kept it at that on my TV as can't work around this issue at all on it. I am new to the CFW scene for the Vita so please bare with me and ask for whaterver info I haven't given here that's needed. 
Could be related but PSVShell is also exhibiting the same behaviour for me, tried removing that plugin to see if there was a conflict but it didn't change pkgj.

**Comment by cuevavirus** [comment]
This bug was introduced in 0.52 and fixed in https://github.com/blastrock/pkgj/commit/232e2fea0b5ea4aa6466e6e562395d852a52a500. The next release 0.53 will include the fix.
