### ISSUE TITLE
TLS 1.2 on 3.68

### ISSUE THREAD

**Issue by calos9999** [blastrock/pkgj#323]
Hardware: PSV
Version of firmware: 3.68
Version of PKGj: 0.53

## Steps to reproduce the issue
Refresh database

Obtained result: iTLS Enso 1.2 error
Expected result: Database refreshes normally because TLS is supported on firmwares >= 3.67

**Comment by cuevavirus** [comment]
The TLS 1.2 error message will show for any SSL error. Nopaystation recently underwent some configuration changes which may cause an SSL error. Please report back if the error persists after 24 hours.
