### ISSUE TITLE
Deprecate "Download update" feature.

### ISSUE THREAD

**Issue by TheRadziu** [blastrock/pkgj#324]
Hardware: Both
Version of firmware: all
Version of PKGj: all

In the past antiblacklist was a single method of using PSV only titles on PSTV, but it broke livearea's update feature [set all apps as system apps, which can't be updated], this is why this download update feature was left despite moving to bgdl download method.

Due to the progress on blacklist and release of DolcePolce this feature is not needed anymore and will be removed in future update.

**Comment by Yoti** [comment]
+1

I need "download game only" option.

**Comment by cuevavirus** [comment]
Removed in version 0.55. A "download game only" button may not be possible with how bgdl works.
