### ISSUE TITLE
Vita Randomly Turns off During Game Download from PKGJ

### ISSUE THREAD

**Issue by Deadkid0** [blastrock/pkgj#327]
Hardware: [PSV ]
Version of firmware: [3.68]
Version of PKGj: [0.52]

## Steps to reproduce the issue

- [Used an extra micro sd to download games from PKGJ]
- [Deleted unwanted games and freed up about 13gbs, queued up a few games to be downloaded]
- [Had put vita into rest mode like usual and when trying to turn back on a few hours later, it randomly shut off. Games not downloaded, space still being taken up.]

Obtained result: [Memory still being allocated by games that did not download, checked the PKGI folder and deleted unwanted folders but no freed up space]
Expected result: [Hoping the games at least downloaded]

[please make sure to add all possible details, like the title id (the 9-chars string in the left column) of the game you are talking about]

**Comment by cuevavirus** [comment]
This is likely to be an sdcard issue or issue with other plugins. Please make sure the sdcard is not defective and properly formatted, and try downloading games with plugins disabled aside from Nonpdrm.
