### ISSUE TITLE
Download failure PsOne , Psp game and dlc

### ISSUE THREAD

**Issue by eze92** [blastrock/pkgj#328]
Hardware: pch- 1001
Version of firmware: 3.68
Version of PKGj: 0.54 
## Steps to reproduce the issue

When downloading the game you get error sceloDopen (uxO: pkgj / game name)

**Comment by cuevavirus** [comment]
Delete ux0:pkgj and try again please.

**Comment by eze92** [comment]
Delete the folder and now working , tranks
