### ISSUE TITLE
How to install PSM Runtime from PKGJ - won't install from system ever

### ISSUE THREAD

**Issue by hansolboy** [blastrock/pkgj#329]
Hardware: PSV
Version of firmware: 3.68
Version of PKGj: 0.54

I get an error when i try to install from system, but in the latest release it was mentioned "PSM runtime can be installed directly in PKGJ without Henkaku DNS"

Please advise.

**Comment by cuevavirus** [comment]
This 30 second video will show it very clearly.

https://www.youtube.com/watch?v=FJTPxdmIvAw

**Comment by hansolboy** [comment]
Thanks @cuevavirus   ;)
