### ISSUE TITLE
C0-9250-6

### ISSUE THREAD

**Issue by random-idiot** [blastrock/pkgj#333]
Hardware: ps vita 1000
Version of firmware: 3.60 spoof to 3.73
Version of PKGj: V0.54

## Steps to reproduce the issue
- I try to download some game or anything 
- C0-9250-6 shows up on notifications 

Obtained result: didn't download the game i wanted
Expected result: download a game

i was trying to download metal gear solid hd collection ,the only thing i was able to download was psm

**Comment by Yoti** [comment]
https://github.com/blastrock/pkgj/blob/master/README.md

**Comment by cuevavirus** [comment]
Are you sure you have nonpdrm loaded? Due to a bug in nopsmdrm, it will also be detected as nonpdrm, so make sure you actually have nonpdrm.
