### ISSUE TITLE
Downloading compatibility packs throws a 404 error

### ISSUE THREAD

**Issue by VSuhas22** [blastrock/pkgj#335]
Hardware: PSVita Fat
Version of firmware: 3.60 HENkaku
Version of PKGj: 0.54

##  The issue

When I try to download any compatibility packs it throws the error:  
<span style="color:red">`Download failure: HttpError: bad http status: 404`</span>

I think this might be because the default URL for comppacks is https://gitlab.com/nopaystation_repos/nps_compati_packs/raw/master/, but trying to access that site throws a 404 error, but I'm not sure about it, and it might be an error on my end.

Any help would be appreciated.

**Comment by cuevavirus** [comment]
The default URL for compat packs was changed in 0.54 to a proxy which seems to have problems. If the gitlab url was working for you before then you can set it again the config.

In the next release the default url will be reverted to the gitlab url and implement curl to avoid problems with tls 1.2.

**Comment by VSuhas22** [comment]
But why did you change it to a proxy?

**Comment by cuevavirus** [comment]
to avoid problems with tls 1.2

**Comment by VSuhas22** [comment]
Oh, okay.
