### ISSUE TITLE
Failed to install PlayStation Mobile Runtime Package: SceDownload change_state DC0 failed: 0x80431068

### ISSUE THREAD

**Issue by gravelydesired** [blastrock/pkgj#336]
Hardware: PSV
Version of firmware: 3.68
Version of PKGj: 0.54

## Steps to reproduce the issue

- Open PKGj
- Search 'runtime'
- Click 'PlayStation Mobile Runtime Package'
- Click 'Install game and patch'

Obtained result: Failed to install PlayStation Mobile Runtime Package: SceDownload change_state DC0 failed: 0x80431068
Expected result: Successfully install the runtime package.

This was achieved trying to install PCSI00011. I have 2.33 GB free on my system, other games install fine, and I have the Henkaku DNS set correctly.

**Comment by cuevavirus** [comment]
0x80431068 is SCE_HTTP_ERROR_TIMEOUT. Please set DNS to default, restart, and try again. If you have refreshed the game lists recently, you do not need henkaku dns for psm runtime.

**Comment by gravelydesired** [comment]
That worked, thank you very much.
