### ISSUE TITLE
theme

### ISSUE THREAD

**Issue by elmanortega** [blastrock/pkgj#337]
hi how are you, awesome work, i can't seem to be able to install themes in my vita, everytime i try it gets stuck and gives error

Hardware: [PSV or PSTV]
Version of firmware: [insert version]
Version of PKGj: [insert version]

## Steps to reproduce the issue

- [insert the steps to reproduce the issue here]
- [insert the steps to reproduce the issue here]
- [insert the steps to reproduce the issue here]

Obtained result: [insert the result you got here]
Expected result: [insert what you expected here]

[please make sure to add all possible details, like the title id (the 9-chars string in the left column) of the game you are talking about]

**Comment by cuevavirus** [comment]
the error is?
