### ISSUE TITLE
Just another bad http issue

### ISSUE THREAD

**Issue by Lockuy** [blastrock/pkgj#338]
Hardware: PSV
Version of firmware: 3.65
Version of PKGj: 0.54

## Steps to reproduce the issue

- launch pkgj
- install Stardew Valley succesfully 
- try to install base comppack to Stardew Valley
 

Obtained result: Download failure: Http error: bad http status: 404
Expected result: install of comppack

Sorry if this is FAQ type question or too obvious one, I'm newbie. Also sorry for bad English.

**Comment by cuevavirus** [comment]
Seems like the proxy is having some trouble. I will fix this in the next release. In the meantime, you can use ref00d or 6syscall0 instead of compat packs.

**Comment by Lockuy** [comment]
Got it, thanks.
