### ISSUE TITLE
PKGj ver 0.11 still shows 0.10

### ISSUE THREAD

**Issue by ginkuji** [blastrock/pkgj#34]
Version of firmware: [3.65]
Version of PKGj: [ 0.11]

## Steps to reproduce the issue

- Install vpk via vitashell

Obtained result: PKGj ver 0.11 still shows 0.10
Expected result: PKGj ver 0.11

**Comment by blastrock** [comment]
Indeed, that's a fail. I reuploaded the package.

I will try to setup releases by travis if it's at all possible to avoid this kind of mess-up in the future.

**Comment by animekai** [comment]
the 0.12 still shows as 0.10, i've download it from vitadb and from here github, but still shows as 0.10
