### ISSUE TITLE
0.54 won't download PSP games

### ISSUE THREAD

**Issue by heyuimintojsus** [blastrock/pkgj#341]
Hardware: PSV
Version of firmware: 3.65 enso etc.
Version of PKGj: 0.54

It will download PS Vita and PS1 games fine. PSP I get the error after a couple minutes, maybe about 2 pct downloaded (see attached photo). But something shows up in Vita Shell with a game folder, however, I don't know if there's anything there, so I deleted it. Hope this is enough info to know why this is happening, especially since it downloads the PS Vita and PS1 games no problem.
![IMG_1147](https://user-images.githubusercontent.com/18518992/75403972-c9c72400-58ce-11ea-986f-7b2d76291892.jpg)

**Comment by cuevavirus** [comment]
If you are using anything that modifies network behaviour ITLS or henkaku DNS, uninstall those and try again please.

**Comment by heyuimintojsus** [comment]
Thank you for the reply. I think I have the ITLS but not sure on the other. So, I’ve done some other stuff that makes me wonder. 

So I downloaded two test PSP games, both under 100mb and they did fine. The PS1 Castlevania SOTN is 345 mb and it downloaded fine. I was trying to get the NCAA Football 10 on the PSP, which is 373 mb. I get that error but there’s a folder inside the uxo pkgj folder for it and an eboot and couple other things in that. I moved the eboot to the pspemu and game folder maybe and when Adrenaline started up, the game was there. I started it but nothing else would happen. Just stuck at the opening screen playing the background music of the game. 

Does that all make sense to understand? I can take pics and put them in here too if you need that to help me. Thank you for trying to help. I’m new to all of this so I’m trying to learn too.

**Comment by cuevavirus** [comment]
Yes NCAA Football 10 did not download completely so you were able to start the game but it did not work beyond that. If you look in the screenshot you posted above, the size is suppose to be 723 MB.

If you tried my suggestions but still failed to download, it is likely an error with your network setup. Try downloading on the computer with NPS browser in that case.

**Comment by heyuimintojsus** [comment]
What are the specific names to try and uninstall? Are they plugins? I’m still trying to figure out what’s what. Sorry for not knowing more about all this.

And do you mean this for pc when you say try computer? If so, then I’d ftp to move it if it downloaded?
https://nopaystation.com/

**Comment by cuevavirus** [comment]
Please refer to these to uninstall ITLS and remove henkaku DNS:

https://github.com/SKGleba/iTLS-Enso
https://vita.hacks.guide/blocking-updates.html (set DNS to auto)

Yes NPS browser can be downloaded on that web page. Then you can transfer with FTP.

**Comment by heyuimintojsus** [comment]
Ok. I found the ITLS and uninstalled it before I saw your post. Tried again and same thing.

So when I hacked it, it said to set that to manual instead of auto. What does that actually do and would it mess up the hack etc by changing it to auto?

**Comment by cuevavirus** [comment]
no

**Comment by heyuimintojsus** [comment]
Ok. Thank you. I greatly appreciate if. I’ll go do that now and try it. I’ll let you know.

Just a quick question so I can understand. So the PSP game was the 700mb+ and it wouldn’t fully download. But I just got a 700mb+ PS1 game to download. Do you know why it would so one system’s game and not the other with similar size?

**Comment by cuevavirus** [comment]
Error not related size.

**Comment by heyuimintojsus** [comment]
Ok so I made both changes and it didn’t work. I had changed the thing in pkgj to download as eboots and it downloaded it completely. But then I would get an error trying to start up. So I changed it all back to what I had and tried another game that was bigger and it downloaded. So what could be the problem with this partic game doing this? (NCAA Football 10)

**Comment by cuevavirus** [comment]
I cannot reproduce this problem. If you want to run games as eboots, then you need [npdrm_free](https://github.com/qwikrazor87/npdrm_free).

**Comment by heyuimintojsus** [comment]
So the game downloads fine for you in pkgj? I already have that plugin.

**Comment by cuevavirus** [comment]
Downloads fine.

**Comment by heyuimintojsus** [comment]
I’m new to this and don’t understand it all. I don’t understand how it can download a 1.2 gb psp game no problem and can’t the football game. How is that even possible? Idk what else to do and I’m trying to understand all this and why etc. Seems like there would be a reason it wouldn’t??

**Comment by heyuimintojsus** [comment]
Is there pics of things I can send that can help you help me figure out what is going on?

**Comment by cuevavirus** [comment]
> Try downloading on the computer with NPS browser

**Comment by heyuimintojsus** [comment]
I followed this but when I restarted the browser nothing happened. 

https://www.cfwaifu.com/nopaystation/
