### ISSUE TITLE
Location of failed download update

### ISSUE THREAD

**Issue by PowoFR** [blastrock/pkgj#342]
Hardware: [PSV]
Version of firmware: [3.60 with enso]
Version of PKGj: [0.54]

Hi,
I just want to know the location of game update files that couldn't finish download because of lack of space.

_I downloaded Ys:Origin with "Install game and patch" but the game I got was only ver1.00
I went back to PKGj and used "Install patch 01.02"
I had no idea that the patch would be bigger than the 550MB I had left._

The download obviously failed and my problem is that even after deleting the whole game, I still miss the 550MB used by the half downloaded patch.

**Where is it so I can delete it?**

**Comment by cuevavirus** [comment]
Read the readme
