### ISSUE TITLE
Feature Request: Show DLC for a specific game

### ISSUE THREAD

**Issue by andrew-stclair** [blastrock/pkgj#343]
Is it possible to show the available DLC for a single game? i know the desktop application for NoPayStation can do this.

**Comment by MegaPramuk** [comment]
Can't you just enter the title ID in the search function? Or does it only look at the name?

**Comment by andrew-stclair** [comment]
I tried that but the result was an empty list

**Comment by Oaklee91** [comment]
Hello, could somebody please upload DLCs for both Utawarerumono games? Thank you.

**Comment by deadair3210** [comment]
You could always buy it and upload it yourself if you really need it.

Also wrong place, this is just a client for nopaystation

**Comment by cuevavirus** [comment]
Resolved by #381
