### ISSUE TITLE
Error C2-12828-1 when clicking install game and patch

### ISSUE THREAD

**Issue by idoyski** [blastrock/pkgj#345]
Hardware: PSV
Version of firmware:3.60
Version of PKGj: v0.54

Error C2-12828-1 when clicking install game and patch..

Whenever I click install game and patch. pkgj will show error.
but when i only install patch, it is okay, the same as psp games and psx games. all are working.
Vita games are only giving me an error,. I only use gamesd plugin

**Comment by DeviJoe** [comment]
Error C0-9250-6
Version: 3.65
Version of PKGj: 0.54
