### ISSUE TITLE
HttpError: bad http status: 522

### ISSUE THREAD

**Issue by DJayBlackout** [blastrock/pkgj#347]
Hardware: PSV
Version of firmware: 3.60
Version of PKGj: 0.54

## Steps to reproduce the issue

- Triangle, then Refresh.

Obtained result: can't get list@ HttpError: bad http status: 522
Expected result: List of games appear

Have removed pkgj, reinstalled, removed henkaku DNS and iTLS, still get the error.

**Comment by cuevavirus** [comment]
NPS was down. Back up now.
