### ISSUE TITLE
On game list refresh HttpError: sceHttpSendRequest failed: 0x8041013d

### ISSUE THREAD

**Issue by slifin** [blastrock/pkgj#349]
Hardware: PSV
Version of firmware: not sure
Version of PKGj: 0.54

## Steps to reproduce the issue
 - Refresh the game list 

Obtained result: `can't get list: HttpError: sceHttpSendRequest failed: 0x8041013d`
Expected result: Updated game list

I've uninstalled iTLS and deleted pkgj/config.txt

**Comment by slifin** [comment]
Version of firmware: 3.65, spoofing 3.73

**Comment by slifin** [comment]
Looks like I might not be the only one: https://www.reddit.com/r/VitaPiracy/comments/fzgkqo/pkgj_v054/

**Comment by RendasT6** [comment]
Pal, this change of DNS worked for me to at least have a list (just installed the app on my vita). https://www.reddit.com/r/VitaPiracy/comments/aoeyx4/cant_refresh_pkgj_database_error_0x80436003/?utm_source=amp&utm_medium=&utm_content=comments_view_all

**Comment by fpmweb** [comment]
I have the same problem:

- Error on press Refresh option
- Error msg: "can't got list: HttpError: sceHttpSendRequest failed: 0x8041013d"
- Hardware: PSVITA
- Version of firmware: 3.60 (HENkaku)
- Version for Spoofing: 3.73
- Version of PKGj: 0.54

**Comment by evertonstz** [comment]
I can also confirm this bug and can confirm changing the DNS settings won't help.

**Comment by fpmweb** [comment]
Right!
I also confirm that I have done DNS testing and the bug is not fixed.

**Comment by MindFvck** [comment]
Few weeks ago it was fine I would refresh without error. As the other guy said it still updates the game list. It seems when its refreshing the games compatibility packs its gets the error.

**Comment by eze92** [comment]
the same error , I don´t changed anything and the last week this working good

**Comment by giannaras666** [comment]
check this video guys it helped me u cant download still compatibility packs i think cause i still use refood https://www.youtube.com/watch?v=HFnKPnv8Kn8&list=LLdbFOe4RwpyoUKDfZgEqxWg&index=3&t=0s   but   u wont wait  for refresh a lot

**Comment by cuevavirus** [comment]
Compatibility packs are disabled by default as of version 0.55. Please remove `url_comppack` from the config file and use ref00d or 0syscall6.
