### ISSUE TITLE
Pressing an option in the menu doesn't stay when pressing back

### ISSUE THREAD

**Issue by TheDogHog** [blastrock/pkgj#350]
Hardware: PSV
Version of firmware: 3.60
Version of PKGj: 0.54

## Steps to reproduce the issue
1. Open the menu in PKGJ
2. Press an option, and the applied option will change the listings
3. Press back, and the listings will revert back to the config standard, with the selected option becoming unselected automatically

Obtained result: Can't search by region, or any of the other criteria like size or date
Expected result: Being able to use the menu to actually pin down a title

I have deleted and replaced many a config.txt, as well as uninstalling and reinstalling, but the issue remains. I was trying to find a JPN DLC, but that was basically impossible due to this issue.

**Comment by deadair3210** [comment]
I believe you have to press the menu key again to save the settings

**Comment by TheDogHog** [comment]
Holy shit, you're right. How did I not think of that?

Thanks!

**Comment by deadair3210** [comment]
Don't feel bad, I had the same issue lol
