### ISSUE TITLE
Can’t get list: httperror 0x80431068 network timeout

### ISSUE THREAD

**Issue by jhardins** [blastrock/pkgj#351]
Greetings! I get the above error when i refresh the game list on pkgj.

Hardware: PSV
Version of firmware: 3.60 Spoofed 3.69
Version of PKGj: 0.54

DNS set to Auto
Config.txt:
Url_comppack http://gateway.fast.sheridanc.on.ca/
Makes no difference on error whether i add or delete the above line.
Hangs for about 10 seconds on “Refreshing games compatibility packs [9/10]... 100% and gives me error “can’t get list: HttpError: sceHttpSendRequesr failed: 0x80431068 Network timeout”
I uninstalled itls-enso from within app itself and rebooted hoping it would make a difference but it didn’t.

Thank you for your time.

**Comment by giannaras666** [comment]
im having save problem
Hardware: PSV
Version of firmware: 3.60 Spoofed 3.73
Version of PKGj: 0.54
DNS set to Auto
Config.txt:
Url_comppack http://gateway.fast.sheridanc.on.ca/
i have installed itls-enso  uninstalled its the same  and im  having  osyscall6 plug in  i still cant download  compatibility packs  after i changed  config.txt i managed to see them  but after i used autoplugin 2  with refresh triangle  in extras for pkgj i dont see compatibility packs anymore im so confused i tried  to use proxy  i avoided network error  and now im having http error cant get list!!

**Comment by fpmweb** [comment]
the same error

**Comment by UnboundLocalError** [comment]
same to me
I can't even use curl to get some information from that URL.

**Comment by adrianbass360** [comment]
Yeah, same here =/. Not sure what's going on. I tried deleting and reinstalling without avail, same error code. Tried switching wifi's, disabling 0syscall6 plug-in, deleting pkgi/PKGJ folders, and nada...

**Comment by C7kTZwp7** [comment]
+1, same here.

**Comment by Ninoh-FOX** [comment]
same here.

**Comment by DiegooBedin** [comment]
same here. I tried all, nothing work. I tried remove the "s"in https, I tried to put the website that was on Nopaystation as compatibility packages, but nothing too..

 "https://gitlab.com/nopaystation_repos/nps_compati_packs/tree/master"

**Comment by adrianbass360** [comment]
If it can't we fixed the issue, at least we can share the lastest files with each other lol. So who has the lastest update? I'll check the dates on my files when I get a chance

**Comment by giannaras666** [comment]
yo guys i  find  a temporary fix  check this video it helped me at least  this guy is awesome https://www.youtube.com/watch?v=HFnKPnv8Kn8&list=LLdbFOe4RwpyoUKDfZgEqxWg&index=3&t=0s

**Comment by dootles** [comment]
I guess we'll just have to stick with downloading the games on PC.... I hope we get another version update because I'm already fed up with how many attempts I've tried to refresh the list.

**Comment by cuevavirus** [comment]
Compatibility packs are disabled by default as of version 0.55. Please remove `url_comppack` from the config file and use ref00d or 0syscall6.
