### ISSUE TITLE
weird error when trying to refresh

### ISSUE THREAD

**Issue by djentyniji** [blastrock/pkgj#352]
Hardware: PSV
Version of firmware: 3.68 enso
Version of PKGj: 0.54

the error is:

`` can't get list: failed to parse line <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN""http://www.w3.org/TR/html4/loose.dtd"> failed to split line ``

I've tried to reinstall pkgj, delete the pkgj folder, check that NoNpDRM was installed, but nothing worked.

help me please, thanks

**Comment by dootles** [comment]
don't worry. literally, everyone is having the same problem with refreshing.
I went to Reddit to look up for possible solutions and one has said that it worked for them when using previous versions of the app. have iTLS uninstalled too if you have it.

**Comment by djentyniji** [comment]
Thanks for the answer ! I downgraded my console to 3.60, installed HENkaku and reinstalled everything else and now everything works !!
