### ISSUE TITLE
Error  80010087 in psp game NPJH50258

### ISSUE THREAD

**Issue by developer-sp** [blastrock/pkgj#353]
Hardware: [PSV slim]
Version of firmware: [3.60]
Version of PKGj: [v0.55]

## Steps to reproduce the issue

- [open pkgj ]
- [triangule, select psp games]
- [search for king of fighters]
- [download NPJH50258 ]
- [open adrenaline and run game]

Obtained result: [erro after boot 80010087]
Expected result: [game running]

- [Im using npdrm free for psp]
- [plugins in ur0, there isn't ux0:tai folder :) , ps vita plugins are in ur0:tai/]
- [ Im using Enso]

**Comment by Yoti** [comment]
Adrenaline errors are not related to the PKGj.
