### ISSUE TITLE
PKGj crashes on startup

### ISSUE THREAD

**Issue by Ben569483** [blastrock/pkgj#356]
Hardware: [PSVita]
Version of firmware: [3.73]
Version of PKGj: [v0.55]

## Steps to reproduce the issue

Just try to start the app

Obtained result: [Crashes on startup]
Expected result: [Some sort of menu]

So when I open PKGj I get an error. (C2-12828-1) so any help?

**Comment by Yoti** [comment]
Downgrade your Vita

**Comment by Ben569483** [comment]
I have downgraded my Vita to 3.65 and everything works fine now.
