### ISSUE TITLE
[Feature request] Please add refresh from localhost or local file folder

### ISSUE THREAD

**Issue by omikron24** [blastrock/pkgj#363]
Hardware: PSV
Version of firmware: 3.60
Version of PKGj: 0.55

## Steps to reproduce the issue

- Being in a country with controlled internet traffic
- Requests to certain IP adresses and domains are being blocked by all internet providers
- Refresh function is not working because of it, it requires either paid vpn connection or manual tsv swap each time an update is available

Obtained result: program hangs up for couple of minutes and then giver timeout error
Expected result: refreshed the available list of games/dlcs

Please add an option to refresh from localhost or any web adress or local folder since a lot of countries are under internet censorship and unfortunately NPS catalogs could not be accessed without vpn. I can run a script to fetch tsv files every week and upload them to my web server but PKGJ has hard-coded adresses for the files and it cannot be manually updates via config or any other means which is big issue. If tsv file or NPS is no longer hosted - program becomes useless in terms of new content

**Comment by cuevavirus** [comment]
see readme
