### ISSUE TITLE
Menu issue pkgj v0.55

### ISSUE THREAD

**Issue by baileyscream** [blastrock/pkgj#365]
Hardware: [PSV]
Version of firmware: [3.60]
Version of PKGj: [0.55]

## Steps to reproduce the issue

- press triangle to open side menu.
Under filters.
Un-mark all that you do not want to see.
As your un-selecting the list actively removes them.
Exit side menu.
Nothing changes the list goes back to showing all regions again.
Try again and then select
Show games.
Still does not save game region selection.

Also.
- can there be a default set to refresh when the app starts. Its not obvious that you need to do that to show download able games when you first install the app
Would also make sure that you have the latest list when you go into the app without remembering to find and click refresh 😉

**Comment by frogcrush** [comment]
Make sure you're hitting triangle to close the menu, otherwise it doesn't save your selection and reverts to what it was displaying before.

**Comment by Demontion** [comment]
> 
> 
> Make sure you're hitting triangle to close the menu, otherwise it doesn't save your selection and reverts to what it was displaying before.

Thanks brotha, I knew what I was doing was an obvious oversight on my part. This did the trick.
