### ISSUE TITLE
PCSB00442 Mahjong World Contest EUR

### ISSUE THREAD

**Issue by planagames** [blastrock/pkgj#371]
Hardware: [PSV]
Version of firmware: [3.60]
Version of PKGj: [0.55]

The game seems not to be complete, it does not install trophies and the levels are locked, when you hit a locked level a message appears to unlock the full game that sends you to ps store
![20210123_191701](https://user-images.githubusercontent.com/77895878/105610531-51076b00-5db0-11eb-88e5-cb948cff0e10.jpg)
![20210123_191709](https://user-images.githubusercontent.com/77895878/105610532-52d12e80-5db0-11eb-8080-91554c0e2efc.jpg)

I'm interested in the European version, not the American, thanks

**Comment by Masamune3210** [comment]
this is not a issue with pkgj, either you didn't download the correct title or you didn't download the dlcs for the correct title. all PKgj does is download and install the game, if you want dlc you have to download them seperately

**Comment by planagames** [comment]
> this is not a issue with pkgj, either you didn't download the correct title or you didn't download the dlcs for the correct title. all PKgj does is download and install the game, if you want dlc you have to download them seperately

no, there is no dlc of this game, try yourself, the game appears without trophies, before you speak to speak check yourself ...

**Comment by Masamune3210** [comment]
Ok, but it still has literally nothing to do with pkgj. It's up to the game to register it's trophy set

**Comment by planagames** [comment]
> Ok, but it still has literally nothing to do with pkgj. It's up to the game to register it's trophy set

the game in pkgj is incomplete, once again check it yourself

**Comment by Masamune3210** [comment]
Incomplete as in how? Missing files? Missing DLC? Once again, this program only installs the games. Most games on the Vita handle trial unlocks as a DLC package, if that is missing then it's likely that nobody has dumped it

**Comment by planagames** [comment]
> Incomplete as in how? Missing files? Missing DLC? Once again, this program only installs the games. Most games on the Vita handle trial unlocks as a DLC package, if that is missing then it's likely that nobody has dumped it

forget it, it was a mistake to write here thinking that someone would fix it, thanks for nothing ...

**Comment by Masamune3210** [comment]
No problem! Not once did you answer a question correctly, or try to install the game manually to make sure that anything I said was correct but sure, have fun. 

For what I can imagine will not be the last time I say it, all PKgj does is download the PKG from the link provided by the list, unpack it, and move it to the correct spot for the system to see the game. Literally almost anything that happens after the game is installed is not a problem with this app

**Comment by planagames** [comment]
> No problem! Not once did you answer a question correctly, or try to install the game manually to make sure that anything I said was correct but sure, have fun.
> 
> For what I can imagine will not be the last time I say it, all PKgj does is download the PKG from the link provided by the list, unpack it, and move it to the correct spot for the system to see the game. Literally almost anything that happens after the game is installed is not a problem with this app

very easy to judge when you didn't even play the game, typing is very easy... bye

**Comment by lukeacat** [comment]
my brudda plz close this horrible issue.
thanks
