### ISSUE TITLE
What will happen when/if the ps vita store shuts down?

### ISSUE THREAD

**Issue by Bounceysteve99** [blastrock/pkgj#374]
Multiple news outlets have reported that it will shut down, what will happen to pkgj?

**Comment by RinMaru** [comment]
> Multiple news outlets have reported that it will shut down, what will happen to pkgj?

It won't work anymore unless the files are still accessible on the server. Depends on if Sony shuts down the server or just no longer allows users to purchase games.

**Comment by Bounceysteve99** [comment]
> > Multiple news outlets have reported that it will shut down, what will happen to pkgj?
> 
> It won't work anymore unless the files are still accessible on the server. Depends on if Sony shuts down the server or just no longer allows users to purchase games.

Well, set your pkgj death clocks then.

**Comment by VictorGamer072YT** [comment]
Look at PSM, Sony killed it in 2015, but the files are still in the CDN, Sony has a long history of doing this, PT is yet another example.

**Comment by eze92** [comment]
I leave the news https://www.playstation.com/en-gb/support/important-notice/
