### ISSUE TITLE
Can't install anything

### ISSUE THREAD

**Issue by no3247** [blastrock/pkgj#377]
Hardware: PS Vita Fat
Version of firmware: 3.65
Version of PKGj: 0.55

Its cant download anything in pkgj, i use sd to vita and memory sandisk 128GB
![IMG_20210406_185655](https://user-images.githubusercontent.com/60257576/113715686-fecdb900-9713-11eb-8524-82e2761fb38d.jpg)
![IMG_20210406_185631](https://user-images.githubusercontent.com/60257576/113717702-160da600-9716-11eb-87af-f33a38ff0a20.jpg)

**Comment by eze92** [comment]
Did you try searching reddit?https://www.reddit.com/r/VitaPiracy/comments/aykr1z/ran_into_a_problem_trying_to_download_games_off/

**Comment by PandasaurusMaximus** [comment]
Same problem here, it was working perfectly for 2 days, I had just freshly modded my vita, followed set up tutorials stringently, applied all the nessesary plugins, removed ux0 Tai folder (I am using SD2Vita method) and out of no where Pkgj just stopped working, everything it does download is corrupted, PSVitas won't download at all I get "can't download" or red text errors in the application all the time, I have tried resetting the config txt, uninstalling and reinstalling all plugins, installing additional recommended plugins from YouTube tutorials, refreshing the live area, deleting all Pkgj related things uninstalling and reinstalling the VPK twice, and no luck I really hope that the creators plan to fix this bug but I hear support for Pkgj might be being dropped? I hope this isn't the case :(

**Comment by cuevavirus** [comment]
There are various reasons this error could occur even with the Store app. Not likely to be a problem with pkgj.
