### ISSUE TITLE
can't DL on pstv

### ISSUE THREAD

**Issue by nictse2013** [blastrock/pkgj#380]
Hardware: [PSTV]
Version of firmware: [3.65]
Version of PKGj: [0.55]

after updated to pkgj 0.55
only can dl psx game
display "failed to install xxx: sce download change_state dc0 failed 0x80103a23" when dl psv game
how to fix it?

**Comment by cuevavirus** [comment]
There are various reasons this error could occur even with the Store app. Not likely to be a problem with pkgj.
