### ISSUE TITLE
PKGj report to install ref00d on new ref00d 1.1

### ISSUE THREAD

**Issue by u4113057** [blastrock/pkgj#382]
Hardware: [PSV or PSTV]
Version of firmware: 3.60
Version of PKGj: 0.55

## Steps to reproduce the issue
when try to install game with version 3.60+

Obtained result: PKGj report to install ref00d on new ref00d 1.1
Expected result: to report that plugin is correct

**Comment by Yoti** [comment]
Use 0syscall6 instead.
