### ISSUE TITLE
PKGJ error "Download failure: wrong pkg header"

### ISSUE THREAD

**Issue by JooJ7475** [blastrock/pkgj#384]
Hi guys I'm having this error when I try to download a ps1 game through PKGJ, anyone knows to solve that problem?

![2021-06-15-104952.jpg](https://user-images.githubusercontent.com/62492125/122074686-cca19d00-cdcf-11eb-99d9-a13f441ae52a.jpg)

**Comment by Masamune3210** [comment]
It also happens in the NPS Downloader on PC iirc so it might be more of a issue with either NoPaystation or the pkg files themselves are being mishandled somehow

**Comment by JooJ7475** [comment]
2 months passed and I didn't got a solution of this problem and I still having this problem
