### ISSUE TITLE
corrupted data when attempting to install psp dlc

### ISSUE THREAD

**Issue by Lunatik650** [blastrock/pkgj#386]
Hardware: [PSV]
Version of firmware: [3.68]
Version of PKGj: [0.55]

## Steps to reproduce the issue

- [set pkgj to install psp, psx games to uma0 through ux0/pkgj/config.txt]
- [going to psp dlc screen shows that it is still trying to install psp dlc to ux0. psp and psx games install fine into uma0.]
- [attempting to install psp dlcs shows that it downloads.]

Obtained result: [when going to adrenaline, it shows there is corrupted data under the game/memory stick menu in adrenaline and the dlc's are not installed when running game. this occurs with all the games i have attempted to install dlc's for, which is at least 5 different games.]
Expected result: [psp dlc's to be installed.]

[please make sure to add all possible details, like the title id (the 9-chars string in the left column) of the game you are talking about]

**Comment by Yoti** [comment]
Duplicate https://github.com/blastrock/pkgj/issues/325
