### ISSUE TITLE
the games are in spanish? dont have all games in psp like "crisis core"

### ISSUE THREAD

**Issue by NMachinne** [blastrock/pkgj#388]
Hardware: [PSV or PSTV]
Version of firmware: [insert version]
Version of PKGj: [insert version]

## Steps to reproduce the issue

- [insert the steps to reproduce the issue here]
- [insert the steps to reproduce the issue here]
- [insert the steps to reproduce the issue here]

Obtained result: [insert the result you got here]
Expected result: [insert what you expected here]

[please make sure to add all possible details, like the title id (the 9-chars string in the left column) of the game you are talking about]

**Comment by Masamune3210** [comment]
Please fill in the issue template, but if the game is in Spanish and doesn't have a language option in-game, either you downloaded the wrong version of the game or a setting is messed up inside the virtual psp. Try booting into adrenaline and checking to see what language is set as the system language

**Comment by Masamune3210** [comment]
As for the missing games, if they are truly not in the database then the only solution is for someone to purchase it and add it which isn't part of this project, it's part of whatever database you are using. Likely NPS
