### ISSUE TITLE
PKGJ Error. "Failed to install "insert app name here": Sce Download change_state DCO failed:0x80410136

### ISSUE THREAD

**Issue by purupuruninja** [blastrock/pkgj#390]
I got this problem when im trying to download a game from pkgj this morning, i already made sure that my memory card (SD2vita)has enough space and my internet connection is functional. I also already got  Osyscall6 installed, and yet, when i was trying to dowload a game from PKGJ, i got this error notification. Does anyone has any ideas how to resolve this problem?
![20211025_120626](https://user-images.githubusercontent.com/93112294/138637586-18178466-4ccd-4178-bf58-601f4a9abdb2.jpg)

**Comment by foxyfinder1019** [comment]
ur not alone i keep getting this error message on mine as well i wanna know what's causing this and i hope it gets fix soon cause i wanna play other games

**Comment by BourgeoisDirk** [comment]
Is there a fix yet for this ?

**Comment by purupuruninja** [comment]
Hi there, sorry for the really late reply. Anyway, it turns out the issue was on my house wifi connection, the problem was fixed after i restarted the router,which is odd considering i can access the internet via my laptop and phone just fine with the wifi connection. Anyway its fixed.
