### ISSUE TITLE
c2-12828-1

### ISSUE THREAD

**Issue by ZyvTheBatchCoder** [blastrock/pkgj#391]
c2-12828-1 PKGj is instantly crashing when i try opening and give me the (c2-12828-1) error message please help.

**Comment by Masamune3210** [comment]
Unfortunately 12828-1 seems to basically just be general error, so it isn't super helpful for a error code. Try making sure your memory card or sd has space and isn't corrupted or damaged filesystem wise, and clean out any pkgj folders on the card other than the installed app.

**Comment by ZyvTheBatchCoder** [comment]
i had to completly reset my vita which is fine
