### ISSUE TITLE
Ps vita pkgj refresh issue 503

### ISSUE THREAD

**Issue by Slav99** [blastrock/pkgj#401]
Hardware: psvita
Version of firmware: 3.60
Version of PKGj: v0.54
pkgj can't get list httperror bad http status 503. after refreshing pkgj 
i deleted and download over and over. my config.text ux0 is empty.

**Comment by svj3ist** [comment]
same problem in version 0.55

**Comment by Masamune3210** [comment]
HTTP 503 comes from the remote server, if you are getting this, the connection has already been established to the remote server and the remote server actually refused the connection itself. Nothing to do with pkgj, check to make sure PSN isn't down by trying to download something from the PS Store

**Comment by Masamune3210** [comment]
Oh, it's trying to get the list and failing. You have to either supply tsv files or point pkgj to a place where it can find some. Either make a config manually or use AutoPlugin2 to set pkgj up
