### ISSUE TITLE
SOUL SACRIFICE DELTA

### ISSUE THREAD

**Issue by DustCeniza** [blastrock/pkgj#403]
Hardware: [PSV]
Version of firmware: [The last]
Version of PKGj: [the last]

You can add soul sacrifice delta US to download the "dlc", i don't mean the voice change, i mean the pacts from another world, new bosses, skins.
They were free "dlc" that are downloaded from the game interface itself, if they could get them through a save or something like that and put it to download as a dlc, since currently if it is done from the game itself it is impossible to obtain them.

**Comment by Masamune3210** [comment]
Pkgj does not offer files to download, it is just a client to download things offered by NoPayStation

**Comment by DustCeniza** [comment]
do you know if there is any client to download this soul sacrifice delta stuff?

> Pkgj does not offer files to download, it is just a client to download things offered by NoPayStation

**Comment by Masamune3210** [comment]
Nope, ask around on the internet. All I know is it's not a issue with pkgj
