### ISSUE TITLE
PS1 games get installed to the wrong folder

### ISSUE THREAD

**Issue by LiEnby** [blastrock/pkgj#407]
Hardware: PSV and PSTV
Version of firmware: 3.600.0011 DEX
Version of PKGj: v0.55

Steps to Reproduce:

- Download a PS1 Game from PKGJ (Eg; Crash Bandicoot 2: Cortex Strikes Back)

Obtained result:
- Game is installed into folder based on its Content ID: ms0:/PSP/GAME/NPUI94154
- "Cannot Access the Memory Card" error upon starting the game in official psp emulator

Expected result: 
- Game is installed into folder based on DISC_ID in param.sfo; of EBOOT.PBP ms0:/PSP/GAME/SCUS94154
- This is what would happen if you installed the game from the PS Store.
- Game runs; doesn't give "Cannot access the Memory Card" error .

**Comment by KuromeSan** [comment]
you also extract 
file ms0:/PSP/GAME/SCUS94154/sce_sys/package/head.bin ext .BIN
file ms0:/PSP/GAME/SCUS94154/sce_sys/package/tail.bin ext .BIN
file ms0:/PSP/GAME/SCUS94154/sce_sys/package/ ext
file ms0:/PSP/GAME/SCUS94154/sce_sys/

these are not supposed to be there, but it doesn't break anything
