### ISSUE TITLE
PKGj Download failure: failed to rename: 0x80010016

### ISSUE THREAD

**Issue by debaser0x** [blastrock/pkgj#414]
Hardware: [PSV]
Version of firmware: [3.65]
Version of PKGj: [0.56]

## Steps to reproduce the issue

- Downloading any non-vita game. 

Obtained result: Error message Download failure: failed to rename: 0x80010016
Expected result: Download and run the desired game. 

When downloading PS1 games I receive this message when it finishes downloading: Download failure: failed to rename: 0x80010016. I've made sure everything is updated, but I'm not sure where to go from here.

**Comment by LiEnby** [comment]
what game are you trying to download?

**Comment by ONElua** [comment]
Fail with any PSP and PSX game
when you have the download options as eboot.pbp "install_psp_as_pbp 1"
And dont have plugin NoPspEmuDrm

The download remains in ux0:pkgj
upxxx-gameid_xx-xxxxx/eboot.pbp

**Comment by debaser0x** [comment]
Thanks for responding. My issue was that I didn’t have the right plugins installed to have the files downloaded through liveview. Once I installed the plugins I was good. Thanks again.

**Comment by ONElua** [comment]
> what game are you trying to download?

Fail with any PSP and PSX game
when you have the download options as eboot.pbp "install_psp_as_pbp 1"
And dont have plugin NoPspEmuDrm

The download remains in ux0:pkgj
upxxx-gameid_xx-xxxxx/eboot.pbp

**Comment by LiEnby** [comment]
what the fuckin- this only happens when i build it from the CI, building it manually and it works fine ???

**Comment by LiEnby** [comment]
https://github.com/blastrock/pkgj/commit/8e058aef4191c6aa42247d8c7e86c1b85d62fbfd somehow that fixed it, im not exactly sure why

**Comment by LiEnby** [comment]
Fixed in v0.57
