### ISSUE TITLE
problem with conan when assembling

### ISSUE THREAD

**Issue by goupriver** [blastrock/pkgj#419]
Hello. Sorry for bad english. I want to translation the package. I can't assemble it.

`Your ~/.conan2/settings.yml does not contain PSVita, you must update it manually with ci/conan2/settings.yml`

I don’t quite understand what to do :)

**Comment by blastrock** [comment]
Add [this line](https://github.com/blastrock/pkgj/blob/master/ci/conan/settings.yml#L54) to your ~/.conan2/settings.yml. If you want the fully automated build, you can just run `ci/ci.sh` from the root of the repository, without touching your ~/.conan2. Otherwise, you can fork this repository and let Github Actions do the build.

**Comment by goupriver** [comment]
> Добавьте [эту строку](https://github.com/blastrock/pkgj/blob/master/ci/conan/settings.yml#L54) в свой ~/.conan2/settings.yml. Если вам нужна полностью автоматизированная сборка, вы можете просто запустить ее `ci/ci.sh`из корня репозитория, не трогая файл ~/.conan2. В противном случае вы можете создать форк этого репозитория и позволить Github Actions выполнить сборку.

Thank you. I am able to run github actions. But it doesn’t work on my computer. I run ci/ci.sh - and there is this problem.

**Comment by goupriver** [comment]
> Add [this line](https://github.com/blastrock/pkgj/blob/master/ci/conan/settings.yml#L54) to your ~/.conan2/settings.yml. If you want the fully automated build, you can just run `ci/ci.sh` from the root of the repository, without touching your ~/.conan2. Otherwise, you can fork this repository and let Github Actions do the build.

Thank you. I am able to run github actions. But it doesn’t work on my computer. I run ci/ci.sh - and there is this problem.

**Comment by goupriver** [comment]
> Add [this line](https://github.com/blastrock/pkgj/blob/master/ci/conan/settings.yml#L54) to your ~/.conan2/settings.yml. If you want the fully automated build, you can just run `ci/ci.sh` from the root of the repository, without touching your ~/.conan2. Otherwise, you can fork this repository and let Github Actions do the build.

managed to solve it.

since I have ubuntu - its repository has GCC version 11. I replaced the variables in the ci.sh file:

```
export CC=gcc-12
export CXX=g++-12
```
on
```
export CC=gcc-11
export CXX=g++-11
```

and manually added PSVita to the file $HOME/.conan2/settings.yml

and everything worked :)
