### ISSUE TITLE
大大  我下载了个游戏  PCSH10082 ASA the legend of heroes sora no kiseki the 3rd evolution (3.61+!)[3.67]  这个游戏下载后玩不到，大大试试看下载后玩到吗？

### ISSUE THREAD

**Issue by fooheejie** [blastrock/pkgj#43]
大大

我下载了个游戏

PCSH10082 ASA the legend of heroes sora no kiseki the 3rd evolution (3.61+!)[3.67]

这个游戏下载后玩不到，大大试试看下载后玩到吗？

this game cant not play，help me
and dlc many cant not dowload

**Comment by fooheejie** [comment]
pkgj 里的

**Comment by fooheejie** [comment]
pkgj 里的游戏
其他的我都玩到
就这个玩不到

psv已经是 enso3.65 变革了
vitashell是1.90最新的


PCSH10082 ASA the legend of heroes sora no kiseki the 3rd evolution (3.61+!)[3.67]

这个游戏下载后玩不到，大大试试看下载后玩到吗？

**Comment by fooheejie** [comment]
可以给我这个游戏的档案文件吗？

PCSH10082 ASA the legend of heroes sora no kiseki the 3rd evolution (3.61+!)[3.67]

我的邮件

jack0jack20@yahoo.com

**Comment by guch8017** [comment]
3.67当然玩不到啊

2018年4月18日星期三，fooheejie <notifications@github.com> 写道：
