### ISSUE TITLE
High noon for PSP downloads

### ISSUE THREAD

**Issue by Ziusun** [blastrock/pkgj#46]
Leecherman just updated his AdrenalineBubbleBooter to be compatible with qwikrazor's npdrm_free plugin (boot drm protected PSP eboots). This is /the/ incentive to add PSP functionality to PKGJ imo :).

https://sites.google.com/site/theleecherman/adrbubblebooter/vpkedition

**Comment by blastrock** [comment]
PSP downloads are still a high priority feature, I just didn't have the time to do it. Maybe this weekend or maybe next, no promises though.

Duplicate of #18
