### ISSUE TITLE
failed to download list

### ISSUE THREAD

**Issue by xswqaz** [blastrock/pkgj#47]
Version of firmware: [3.60]
Version of PKGj: [0.13]

## Steps to reproduce the issue

Failed to download list from yesterday
( from nopay)
It success to download non-SSL connection
Server Certificate is valid (expires November 29, 2018 )

Obtained result: [failed to download list]
Expected result: [download list]

[please make sure to add all possible details, like the title id (the 9-chars string in the left column) of the game you are talking about]

**Comment by ShroomKing** [comment]
lol 6.50 firmware

you living in the future, fam.

**Comment by ShroomKing** [comment]
Your isssue isn't related to pkgj and doesn't belong on this repo.

(The domain that's hosting the tsv databases has issues with the secure hypertext transfer protocol right now, the non-secure one works though so use that in the meantime or wait for the respective person/s to fix it.)

**Comment by xswqaz** [comment]
I fixed it 3.60

**Comment by TheRadziu** [comment]
Its because our host disabled TLS 1.0 support. We are trying to bring it back but here is the suggestion for @blastrock -> Implement custom TLS 1.2 support for pkgj.

**Comment by vaekain** [comment]
Sorry A noob here, pkgj says failed to download list what do I do?

**Comment by vaekain** [comment]
Version 3.65 😢

**Comment by vitanoob** [comment]
same problem here, mine is on 3.65 enso , pkgj v 0.13, once I open pkgj it says failed to download list. I hope it'll be fixed soon. thanks

**Comment by yasurio** [comment]
Same error here as @vitanoob

**Comment by blastrock** [comment]
Sorry, I won't have time to look into this before at least saturdayOn Apr 20, 2018 09:16, yasurio <notifications@github.com> wrote:Same error here as @vitanoob

**Comment by vitanoob** [comment]
Woaaah!!!!!! blastrock replied!!! coooool!!!! Thanks Bro! thanks for your work blastrock! no need to say sorry bro! we are the one whose asking for a favor here. .thanks

**Comment by yasurio** [comment]
Don´t worry man just asking for help nice job !!

**Comment by vitanoob** [comment]
Guys problem fixed, in pkgi/config.txt just change https to http, just remove the "s" after u edit, restart ur vita then try opening pkgj

**Comment by yasurio** [comment]
It worked thanks u @vitanoob

2018-04-20 13:05 GMT+02:00 vitanoob <notifications@github.com>:

**Comment by blastrock** [comment]
Implementing custom TLS implies bundling openssl and curl (or something like that) and changing quite some code, so the workaround is to use http instead of https until we can upgrade our vitas' firmwares or the site goes back to supporting some older protocols.
