### ISSUE TITLE
Progress bar request 

### ISSUE THREAD

**Issue by Kojikun1** [blastrock/pkgj#48]
please i installed back pkgi just because the progress bar why you remove that, 
ok can you go back the old progress bar or
implement again percent and download speed please 
also thanks for the great work

**Comment by blastrock** [comment]
What do you mean? There is a progress bar at the bottom of the screen while you are downloading.

**Comment by Kojikun1** [comment]
I know but the progress bar is dont show the percentage and download speed.

**Comment by xPSV** [comment]
Oh! great idea same as I think. Cheer up for this enhancement.

and thanks for your hard work.

**Comment by GravuTrad** [comment]
same thing for me, missing percent for this download bar. thanks blastrock.

**Comment by Kojikun1** [comment]
wow finally Thankyou very much for that is working perfect
