### ISSUE TITLE
pkgj only downloads, but doesn't install in Enso 3.65

### ISSUE THREAD

**Issue by ItaloKnox** [blastrock/pkgj#5]
Hello,

This is the first time I have used pkgj (or pkgi), so I'm not used to the process. I did some reading on Reddit and looks like the app is capable of installing the games, the Github readme seems to imply the same.

So, after upgrading my Vita to Enso 3.65 (the installation seems to be successful, no issues and NoNpDRM works) I installed pkgj and tried to download a few games. I got the ``config.txt`` file configured with the expected links, and it displays all the games and downloads them correctly. After downloading, it seems to unpack everything in the pkgi folder alongside the ``config.txt`` file. After that, the programs idles and doesn't do anything until you start a new download, that results in the same thing. 3.60 games seem to be having the same issue. Clicking on an already downloaded game will result in the app downloading it again from scratch.

Is this the expected behavior? Am I missing something or is it just bugged on 3.65?

Cheers.

**Comment by ItaloKnox** [comment]
I found out the issue was because NoNpDRM wasn't being loaded properly. Fixing the path also fixed pkgj, and it works perfectly now. I'm closing this issue, thanks. 👍

**Comment by darkamon** [comment]
What do you mean by fixed PKGJ?

**Comment by ItaloKnox** [comment]
Fixed the issue that was happening in my first post.

**Comment by darkamon** [comment]
How do you fixed it? Reinstall the vpk and new txt file?

**Comment by ItaloKnox** [comment]
Like I said, if you have the same issue I did in the first comment, check your NoNpDRM because it's the root of the problem. When pkgj doesn't install the game it means NoNpDRM is not loaded.

**Comment by darkamon** [comment]
Where do you put it if not in ur0:tai?

**Comment by ItaloKnox** [comment]
I had a typo in mine that was trying to load it from ux0 instead of ur0, so that's why it wasn't being loaded.
