### ISSUE TITLE
Showing No Items

### ISSUE THREAD

**Issue by adamb32** [blastrock/pkgj#50]
Version of firmware: Henkaku 3.65
Version of PKGj: Tried on .11 and .13

## Steps to reproduce the issue

Load pkgj from home screen

Obtained result: No Items
Expected result: Show list of games

I changed the S in the http in the config file, and changed to thesite, however when i load either the .11 or .13 it says No Items?

**Comment by thienheo** [comment]
me too

**Comment by barbabarros** [comment]
im using 3.65 enso and 0.13 pkgj and nopaystation address without S (http) in config.txt and it is working fine...

**Comment by blastrock** [comment]
It works for me too on 0.13 with http links. Are you sure you changed all URLs in ux0:/pkgi/pkgi.txt?

**Comment by adamb32** [comment]
Got it! Thanks guys, was using thesite instead of nopaystation.
