### ISSUE TITLE
Pkgj failed to download list

### ISSUE THREAD

**Issue by richard1222** [blastrock/pkgj#52]
Version of firmware:  3.65
Version of PKGj: v 0.13

## Steps to reproduce the issue

To be honest i have no idea how to recreate this i got a error out of nowhere and  it said failed to download list and then pkgj stopped responding now every time i get this error it does this it  after that now i can't use it anymore so i'm at a lost of what i should do plus  i have not used my vita for at least a few days and i  opened pkgj and this happened
![20180424_131505](https://user-images.githubusercontent.com/37267569/39203150-efc14c32-47c1-11e8-8a6d-bb2cd06f3e7e.jpg)

Obtained result: a red bar saying failed to download list and the app locked up 
Expected result: ps vita games to load up 
PKGJ00000

PS. sorry if i am making a submission for something that is no big deal never had this problem before

**Comment by pitipuo** [comment]
Make sure the links in your config.txt start with http not https

**Comment by richard1222** [comment]
They are i got everthing setup right i can check again to be sure though

**Comment by barbabarros** [comment]
are you using the nopaystation url without https? just http....

**Comment by richard1222** [comment]
Yea i fixed it can someone close this post

**Comment by 123kennix** [comment]
Where is located the config.txt? I need to fix it as well.

**Comment by barbabarros** [comment]
ux0:pkgi/config.txt

**Comment by richard1222** [comment]
Mine is in ur0 but i use a usb and the storagemgr plugin
