### ISSUE TITLE
List is empty

### ISSUE THREAD

**Issue by richard1222** [blastrock/pkgj#54]
Version of firmware: 3.65
Version of PKGj: v0.13

## Steps to reproduce the issue

- put the url links into a config.txt
- [insert the steps to reproduce the issue here]
- [insert the steps to reproduce the issue here]

Obtained result: no items show then it crahes
Expected result: ps vita showing up

PKGJ00000
No one helped last time and the error is different this time and before you ask i got everything setup right
Says no items show then crashes right after that

**Comment by barbabarros** [comment]
are you using nopaystation urls with http only? not https

**Comment by edale2** [comment]
I was just about to post about this same issue, but barbabarros's suggestion to delete the 's' from 'https' on the links in the config file got PKGj working again.

**Comment by blastrock** [comment]
Please retry with the latest version, error reporting has been improved

**Comment by Smoker1** [comment]
Still not showing anything in the Listings.
Have UTF in .pkg file, File name is as it should be directly from PSN Link. File is in ux0:pkgi Folder. Nothing

**Comment by edale2** [comment]
I'm guessing UTF is an abbreviation for a game's title, and he's trying to install the game by putting the PKG file for that game in the pkgi folder.

**Comment by blastrock** [comment]
Oh, I never tested that feature, and I was thinking of removing it actually...

@Smoker1 if you prefer downloading titles on your computer and then installing them on your vita, you should not use pkgj but something like NPS Browser I think.

**Comment by blastrock** [comment]
Closing since there is no news of OP
