### ISSUE TITLE
PSx and PSP games won't appear on Livearea

### ISSUE THREAD

**Issue by ABDOULemul** [blastrock/pkgj#56]
Version of firmware: [3.60 enso]
Version of PKGj: [0.14]

When I install PSx or PSP games, they won't be in the Livearea.
But they has been install correctly because I Can see it on CMA.
Why?
Thanks for your work, this IS a very useful homebrew.

**Comment by blastrock** [comment]
Games will only appear in adrenaline. You have to use some thing like adrenaline bubbles manager to make bubbles for them. I never used it myself though.

It should be possible to make pkgj make bubbles for games it installs, but I will need to search how to do it.

**Comment by InitialXKO** [comment]
This is what you need
```
https://github.com/ONElua/AdrenalineBubbleManager/
```

**Comment by KuromeSan** [comment]
> Games will only appear in adrenaline. You have to use some thing like adrenaline bubbles manager to make bubbles for them. I never used it myself though.
> 
> It should be possible to make pkgj make bubbles for games it installs, but I will need to search how to do it.

https://github.com/KuromeSan/VitaShell/blob/master/refresh.c#L403
