### ISSUE TITLE
Add support for PC Engine games

### ISSUE THREAD

**Issue by 1jtp8sobiu** [blastrock/pkgj#57]
Version of firmware: [3.65 Enso]
Version of PKGj: [0.14]
Game Title: [ NPJJ30001  Bomberman '94 (PC Engine)] (PSP category)

When I download the PC Engine title with PKGj0.14 and start it with adrenaline,
It does not proceed from loading screen.

When downloading with NPS browser, following two files are created.
Copying them together with pspiso, it works fine.

\PSP\GAME\NPJJ30001\CONTENT.DAT
\PSP\GAME\NPJJ30001\PSP-KEY.EDAT

Please check it when you have time.
Thank you  for your great work.

**Comment by blastrock** [comment]
I didn't test PC Engine games yet. Will do.
