### ISSUE TITLE
Can't get list HttpError

### ISSUE THREAD

**Issue by kazyns** [blastrock/pkgj#59]
Version of firmware: 3.65
Version of PKGj: 0.14

## Steps to reproduce the issue

- [insert the steps to reproduce the issue here]
- [insert the steps to reproduce the issue here]
- [insert the steps to reproduce the issue here]

Obtained result: [insert the result you got here]
Expected result: [insert what you expected here]

I have follow the instructions of the installation (vpk+config.txt with nopaystation url) but when i start the app i get an error message: **can't get list: HttpError: failed to get response lenght.**
How can i fix that please ?

Thank you

**Comment by blastrock** [comment]
Here's a version that will print an error code that should help debugging this: https://github.com/blastrock/pkgj/releases/tag/v0.15

**Comment by Kojikun1** [comment]
This is not a problem with the pkgj, for solve this just remove "s" of https in config.txt, now is just http.

**Comment by blastrock** [comment]
Since there is no more information on the original issue, I'm closing this.
