### ISSUE TITLE
Add option to download psx games to uma0 instead of ux0

### ISSUE THREAD

**Issue by mrdude2478** [blastrock/pkgj#6]
Can you add a percentage downloaded text next to the downloads bar (nice update BTW).

Also, Can you add some code so we can save a downloaded database (from url), we can then save this as pkgi.txt
Can you also add an option so we can switch between pkgi.txt or loading from a url defined in config.txt.

Thanks.

**Comment by blastrock** [comment]
The old pkgi.txt mode is a pain in the neck to maintain, it is more probable that I drop its support than I add features to it. Why do you need that?

I can add a percentage to the download bar though

**Comment by mrdude2478** [comment]
It's just a feature I'd like to see, also the ability to download psx to uma0 instead of ux0 (or an option to change location - maybe in the config file).

I downloaded from the git so I could change myself but couldn't figure out what file to change, I edited 1 file - but changing uxo:psemu to uma0:psemu didn't work for me.

Also when I clone this git - it's like 700+ MB, why so large, it's downloading lots of stuff it doesn't need to???

**Comment by blastrock** [comment]
I can add that with an option in the config file, yes.

If you want to hardcode it for yourself, there are two occurrences in pkgi_vita.cpp
693:    snprintf(path, sizeof(path), "ux0:pspemu/PSP/GAME/%.9s", content + 7);
801:    snprintf(dest, sizeof(dest), "ux0:pspemu/PSP/GAME/%.9s", contentid + 7);

The git clone is very small, but when you build it, it downloads boost in your build directory which is quite big. Boost isn't compiled though. I use only a small part of it, so yes, it downloads tons of useless stuff, but there's no way to only take a part of it...

By the way, next time please open multiple issues for multiple feature requests.

**Comment by mrdude2478** [comment]
Thanks for the reply,

I already tried changing:
693: snprintf(path, sizeof(path), "ux0:pspemu/PSP/GAME/%.9s", content + 7);
801: snprintf(dest, sizeof(dest), "ux0:pspemu/PSP/GAME/%.9s", contentid + 7);

to:
693: snprintf(path, sizeof(path), "uma0:pspemu/PSP/GAME/%.9s", content + 7);
801: snprintf(dest, sizeof(dest), "uma0:pspemu/PSP/GAME/%.9s", contentid + 7);


Once downloaded, the game would extract from the pkg - but would stay in uxo:pkgi folder and not get moved to uma0: that's why I was asking - I thought maybe I was missing something.

**Comment by ShroomKing** [comment]
you cannot move files between partitions.   

you'd have to  **copy** them to the dest folder and delete the files in pkgi afterwards.

**Comment by mrdude2478** [comment]
Thanks that explains that then, I'll have a look on how to do that and make a function that gets called to do that.

**Comment by blastrock** [comment]
Right, I forgot about that detail. This feature is harder to implement than it seemed.

**Comment by mrdude2478** [comment]
Well, i made a call called move under line: 806, then I made this void:

void move()
{
	int result;
  char oldname[] ="ux0:pspemu/PSP/GAME";
  char newname[] ="ux0:pspemu/PSP/GAME2";
  result= rename( oldname , newname );
}

To test that the call was being executed after the download/extraction was competed - and the folder was renamed. I'm not sure what the vita command is to copy a folder from one place to another though - I can just change the last line from rename to a copy command instead, but I'll need to look at some other code on how to do that.

**Comment by mrdude2478** [comment]
Are you sure - how does vitashell do it - you can copy from that? I tried downloading to uma0: already as explained above, but I didn't know what code to edit (apart from those two lines mentioned (693-801), but that didn't work.

**Comment by blastrock** [comment]
Vitashell has probably written its own copy function. We can use that.

> I tried downloading to uma0: already as explained above, but I didn't know what code to edit (apart from those two lines mentioned (693-801), but that didn't work.

Files are first downloaded in a temporary folder, and then moved to the correct path. The two lines you have changed are the destination for the second step.

For the first step, you can change the path of the temporary folder in https://github.com/blastrock/pkgj/blob/master/pkgi_vita.cpp#L644 . Keep in mind that downloading psvita games and stuff will stop working if you change that. Also, do not forget to create the directory manually.

**Comment by mrdude2478** [comment]
OK thanks, I did notice about the tmp dir, I also had a look at the vitasdk wiki and found I can delete folders with: sceIoRmdir

I couldn't find anything about copying directories though - weird, though. How come when the pkg is extracted in the tmp dir it gets moved to psemu/game dir - are you just moving it?

I might end up just using lua to make a little plugin as I know lua language, that way I don't need to mess with your code everytime you update. Thanks for the replies and help though, I do appreciate the time you've taken, also your app is very very good.

**Comment by mrdude2478** [comment]
I ended up making a modded version that you can install alongside your version, they both use different config.txt so they don't mess with each other.

https://mega.nz/#!g1QCyLyK!3VZHCkcFcMwJULPpz7pe_hCwhB1QPJaycx0bUPMFTNs

The one I modded creates a pgki folder in uma0, and downloads to there instead, also only psx data gets loaded. Obviously this is not the best way to do things - but it's a dirty hack in the meantime until you manage to do something better :-) Thanks.

**Comment by blastrock** [comment]
Closed by a0b9368
