### ISSUE TITLE
PSP ISO converting redundant?

### ISSUE THREAD

**Issue by Ziusun** [blastrock/pkgj#60]
Hey,
I'm pretty happy about the PSP addition in v0.14 but don't you think the conversion process is pretty unneccessary. It makes a huge difference in time for the installation to complete and the resulting files are much bigger...can't you make people depend on npdrmfree.prx since Adrenaline is also neccessary anyways?  It also would make copatibility much higher.

**Comment by blastrock** [comment]
I didn't know about that, I'll check it out when I get some time :)

**Comment by blastrock** [comment]
I couldn't find how to make that work on Adrenaline 6.3 with henkaku 3.65... I added the plugin in pspemu/seplugins and added the line in game.txt. The plugin appears as enabled in the vsh menu, yet when I start a game as an EBOOT, it fails with an error 80010087. Did I miss something?

**Comment by Ziusun** [comment]
It is a VSH plugin :).

**Comment by blastrock** [comment]
Oh, I needed to add it in vsh.txt, thanks! Seems to work here :)

**Comment by Ziusun** [comment]
Hey,
since EBOOT decrytion is handled by npdrm_free.prx but Adrenaline still doesn‘t support loading encrypted DLC/PCEngine/Themes (mostly PSP-KEY.EDAT files) wouldn‘t it be a good idea if pkgj could decrypt these too if any DLC files were found after extracting the pkg? There was this tool named pgdecrypt.exe during PSP era. Maybe have a look into it?

**Comment by blastrock** [comment]
If that goes into adding support for PSP DLCs, I will probably have a look into it :)

**Comment by Ziusun** [comment]
Hey,
Thanks for adding PCEngine support so quick. If I was any help your welcome 🙌🏻. So sorry this whole pbp/iso "discussion" made such a noise.

**Comment by Ziusun** [comment]
Hey, there is now an official qwikrazor github with an updated version of npdrmfree :) https://twitter.com/qwikrazor87/status/1010825466347958272

**Comment by blastrock** [comment]
It seems cool, maybe I can remove the PSP-KEY decryption code from pkgj then. Thanks for the link!

**Comment by Ziusun** [comment]
Another maybe important tool for pkgj developement: PSP Depackager
Qwikrazor developed this so one could extract every type of PSP pkg ondevice. It supports games, themes, dlc. The source is included. This should proof very helpful for pkgj :).

https://doc-10-bg-docs.googleusercontent.com/docs/securesc/ha0ro937gcuc7l7deffksulhg5h7mbp1/macpaga8n7fcqgmpsu2ebcm7jec4kpin/1529906400000/07523161675604257471/*/0BwYVUA7ansC5VjNVaDVXZC1oSU0?e=download
