### ISSUE TITLE
Create ISO folder if it doesn't exist - code example

### ISSUE THREAD

**Issue by mrdude2478** [blastrock/pkgj#62]
Version of firmware: [3.60]
Version of PKGj: [0.15]

Currently if the ISO folder doesn't exist when downloading a PSP game, the install will fail.

Here's some updated code, to check if the folder exists - of not it creates it, See pic for code change:

https://imgur.com/a/5FArYCD

**Comment by blastrock** [comment]
Thanks, don't worry, I will do it :)

Duplicate of #58
