### ISSUE TITLE
PSP game Download error

### ISSUE THREAD

**Issue by RealVince99** [blastrock/pkgj#66]
Version of firmware: [3.60]
Version of PKGj: [0.16]

To begin, thank you for your work.
downloading PSP games is a function that I expected a lot.
however, for many PSP games, I get the following error:
"Download failure: unsupported package type: 15"
it looks like we're getting the same error with NPS Browser.
so it's not related to PKGj.

what do you think is the problem?
.tsv link ??

**Comment by blastrock** [comment]
If I remember correctly, you get this error for "Minis" games. They are not supported at the moment, I don't know if it is easy or hard to do, but I'm planning on adding support for them.

**Comment by RealVince99** [comment]
i already install one "minis"
Tetris (Minis) is working fine on my vita (download via PKGj of course)
it's not related !!

**Comment by RealVince99** [comment]
![2018-05-02-010220](https://user-images.githubusercontent.com/32538650/39497678-bd9bf778-4da4-11e8-8fe2-61d04a649906.jpg)

**Comment by RealVince99** [comment]
it's completely random.
some Minis download, others not ...
some neogeo stations are downloaded, others not ..
and the same for all other games.

good luck to find where the problem comes from ..
;)
