### ISSUE TITLE
ERROR Dowload failure: cannot create file sce_sys/livearea/contents/bg.png

### ISSUE THREAD

**Issue by monni89** [blastrock/pkgj#68]
I came across the next issue when I used pkgj:
Download failure: cannot create file sce_sys/livearea/contents/bg.png

**Comment by blastrock** [comment]
Please, include more detail (or fill in the template): What were you installing? Did you try multiple times? What version of pkgj were you using?

**Comment by monni89** [comment]
I'm using the latest version. 
I'm trying to install it again and get it message:
Error 0x8001002F

**Comment by blastrock** [comment]
It corresponds to error C1-2783-0. I don't think this is related to pkgj. Try restarting your vita... Some people suggest formatting your memory stick. I can't help much more than that...

**Comment by blastrock** [comment]
Probably not a pkgj bug
