### ISSUE TITLE
can't get list

### ISSUE THREAD

**Issue by jafalim** [blastrock/pkgj#73]
Version of firmware: 3.60
Version of PKGj: 0.18

## Steps to reproduce the issue

I installed pkgj as described. put url address with http in config.txt

Obtained result: got an error 0x80431075 can't get list: HttpError: sceHttpSendRequest failed
Expected result: [insert what you expected here]

what could it be?

**Comment by jafalim** [comment]
so, I've changed config a little bit. looks like this:
url_games http://nopaystation.com/tsv/psv_games.tsv
url_updates http://nopaystation.com/tsv/psv_updates.tsv
url_dlcs http://nopaystation.com/tsv/psv_dlcs.tsv
url_psx_games http://nopaystation.com/tsv/psx_games.tsv
url_psp_games http://nopaystation.com/tsv/psp_games.tsv
Sort name
Order asc
Filter EUR,USA

now I have another message: can't get list: HttpError: bad http status: 404

**Comment by danminrob** [comment]
Well, the 404 is because you need the .tsv name files to be in uppercase, in lowercase that URL doesn't exists.
But i'm also getting sceHttpGetResponseContentLength error.

**Comment by Malek1985** [comment]
Example: url_psp_games 
http://nopaystation.com/tsv/PSP_GAMES.tsv

**Comment by jafalim** [comment]
Thanks guys, problem solved.
