### ISSUE TITLE
Error 0x80870004

### ISSUE THREAD

**Issue by nosveratu88** [blastrock/pkgj#74]
Version of firmware: [3.60]
Version of PKGj: [0.18]

After downloading PSV game the error 0x80870004 is showing. I try change version of PKGj and it doesn't work. I tried download PSX games and the game is download successfully. Please help me!

**Comment by blastrock** [comment]
Sorry, I don't know this error, and can't find it on google... Check that your Internet works with the browser maybe...

**Comment by nosveratu88** [comment]
https://www.reddit.com/r/VitaPiracy/comments/8g1wf3/pkgj_error_fix/    But still i don't know what to do

**Comment by blastrock** [comment]
That's for error 0x80431075.

I still don't have anything to help you. Have you tried uninstalling, redownloading and reinstalling pkgj?

**Comment by sackc** [comment]
I literally have the exact same issue.  Same number and everything.  I uninstalled, reinstalled, redownloaded Nonpdrm everything.  I can download PSP and PSX games, but PS Vita just doesn’t work.  No clue why.

**Comment by blastrock** [comment]
Try to take the url of the game you want to download and open it in your ps vita browser directly, see if that works.

**Comment by nosveratu88** [comment]
You have to remove tai folder from ux0:  then download nonpdrm.skprx past it into tai folder in ur0: then open config file and add line under KERNEL line  ur0:tai/nonpdrm.skprx For today the best version of PKGj is 1.6

**Comment by nosveratu88** [comment]
[config.txt](https://github.com/blastrock/pkgj/files/2019343/config.txt)

**Comment by nosveratu88** [comment]
And remember after changing you have to restart ps vita/tv!

**Comment by blastrock** [comment]
Oh I thought you meant that the game didn't download, while the problem was that the game didn't run...

Well, thank you for finding this out!

**Comment by aytacdada** [comment]
@nosveratu88 thank you friend. i fix it with yours help. :D

**Comment by Kasarisenpai** [comment]
I know this was closed, but I'm still having this issue. I tried reinstalling nonpdrm, and made sure that everything was right but nothing seems to work. When I download a game, it gets to 100% then gives me the same error message.

**Comment by blastrock** [comment]
I can't help more than that, if scePromoterUtilityPromotePkgWithRif fails, the only reason I can think of is a problem with nonpdrm.

**Comment by sackc** [comment]
Oh, I actually figured it out.  Turns out its because I was using a USB add on with my PSTV.  I had installed the USB driver before Nonpdrm and that screwed it up.  You're supposed to install Nonpdrm first then the USB driver and it should work.

**Comment by wildarmtins** [comment]
sackc, you are my saviour ^_^ This was my exact problem. For anyone else stumbling across this, unmount your sd card and you will see the nonpdrm file dissapears from the tai folder on ux0. You need to unmount your card, follow the install procedure again installing to the pstv's internal memory, reboot, then remount your card, then the installation will stick.

**Comment by sobir8** [comment]
hi, to add a bit. if you;re on vita newly setup h-encore and going for SD2Vita. make sure you copy gamesd.skprx & nonpdrm.skprx on ux0 folder and edit the config before power off and on again. if you only did for gamesd.skprx for sd2vita only, the internal memory ex0 will be replaced with sd2vita which cause the PKGj error for copying on ux0 sd2vita instead of internal memory. hope its help. i tried it on ps vita slim btw

**Comment by nictse2013** [comment]
> Oh, I actually figured it out. Turns out its because I was using a USB add on with my PSTV. I had installed the USB driver before Nonpdrm and that screwed it up. You're supposed to install Nonpdrm first then the USB driver and it should work.

what usb driver u install?
