### ISSUE TITLE
PKGj v0.19 can't get list no update URL

### ISSUE THREAD

**Issue by Shadowtwin** [blastrock/pkgj#76]
Version of firmware: [3.60]
Version of PKGj: [0.19]

 Steps to reproduce the issue

Not exactly sure how to reproduce this issue, I am using SD 2 Vita so all of my config files are in ur0. 
I had to create PKGj folder in ux0 due to never having PKGi installed. 
Inserted config.txt file. I have nonpdrm.skprx added to my ur0 folder and made the changes to config.txt in ur0 by adding correct code under Kernel I repeatedly get an error when attempting to launch that says "can't get list no update URL" I double checked PKGj config.txt and made sure each link was written as HTTP instead of HTTPS. Any assistance would be greatly appreciated, I am totally stuck. Thank you. 
Obtained result: [List does not populate and error is given stating "can't get list no update URL]
Expected result: [List populates.]

[please make sure to add all possible details, like the title id (the 9-chars string in the left column) of the game you are talking about]

**Comment by blastrock** [comment]
I might have broken something with that, but I can't reproduce your issue.

If you have ur0:pkgi/config.txt, that file will be loaded. Otherwise ux0:pkgi/config.txt will be loaded. I tried moving my config to ur0:, but it still works for me. Can you give me more details?

pkgj is unrelated to nonpdrm and tai configuration, so you can put that wherever it works.

**Comment by GravuTrad** [comment]
Let config.txt in ux0 (even with sd2vita)
and don't forget to keep an empty lines between each line of the config.txt files, and even at the end of the file.

**Comment by Shadowtwin** [comment]
So all I did was create the PKGj directory in ux0 and threw the config.txt file with the web urls inside did I miss a step some where? Was I supposed to create a PKGi folder in ux0 even if i am using PKGj and then put config.txt with URLs in that? Does PKGj look for config.txt in a PKGi folder? Should it matter what I called the directory?

**Comment by Shadowtwin** [comment]
Wait I need to space out the URLs?

**Comment by Shadowtwin** [comment]
I guess what I am asking is where does the software look for the config.txt file?

**Comment by blastrock** [comment]
In ux0:pkgi/config.txt or ur0:pkgi/config.txt . I think that's in the readme On May 22, 2018 06:55, Shadowtwin <notifications@github.com> wrote:I guess what I am asking is where does the software look for the config.txt file?

**Comment by RY0M43CH1Z3N** [comment]
@Shadowtwin

**Comment by RY0M43CH1Z3N** [comment]
@Shadowtwin you can use vitashell to open it or in your PC you can use notepad or other tool to modify a text file.

And yes, you have to write every URL in diferent lines.

**Comment by blastrock** [comment]
I hope this is fixed too...
