### ISSUE TITLE
can't get list: HttpError: sceHttpSendRequest failed: 0x80436007

### ISSUE THREAD

**Issue by memphis2829** [blastrock/pkgj#77]
Version of firmware: [cfw 3.60]
Version of PKGj: [v0.19]
I followed all the steps and a few different ones from youtube vids and ended up with this

**Comment by blastrock** [comment]
That's SCE_HTTP_ERROR_RESOLVER_ENOHOST according to https://vitadevwiki.com/vita/Error_Codes . It usually means that you have a problem with your internet connection. Check that it works with your browser.

**Comment by Morshu** [comment]
I'm having the same error : I'm on CFW 3.60 and PKGJ 0.19 aswell but my internet is working just fine. I'm able to connect to PKGi without a problem but once I switch to PKGJ + changed the config.txt I'm having this error

**Comment by memphis2829** [comment]
I’ve never installed pkgi first but I will try to see if it works thanks guy

**Comment by memphis2829** [comment]
@Morshu i did install Pkgi and it worked thanks, next ill try out the Pkgj again
