### ISSUE TITLE
Restore download resume

### ISSUE THREAD

**Issue by Jlroxy** [blastrock/pkgj#78]
I can't resume my download, when do you plan to fix the resumable download?

**Comment by blastrock** [comment]
Yes, I dropped the feature for the moment. I don't know when I will restore it.

**Comment by Jlroxy** [comment]
Thanks man.. I'll looking forward to it.

**Comment by joseluisametller** [comment]
Also, is there a possibility to auto delete the temp created folder when a download fails?
