### ISSUE TITLE
can't get list: HttpError: bad http status: 404

### ISSUE THREAD

**Issue by Morshu** [blastrock/pkgj#79]
Version of firmware: [CFW 3.60]
Version of PKGj: [0.18](I'll try with 0.19 when I get home)

I get this error whenever I launch pkgj, I did what was explained to fix this error in other topics (http~~s~~, files name in upper case) but nothing changed

**Comment by Ickerday** [comment]
What was that "incredibly stupid" thing? I'm curious as I had some issues with config.txt that had to do with line endings. PKGJ seems to not stop parsing after encountering `.tsv` extension, which leads to some issues when people copy the config lines from a spreadsheet

**Comment by Ickerday** [comment]
You should reopen the issue IMHO.

**Comment by Morshu** [comment]
The issue is solved so I don't see why I should reopen this thread

**Comment by Ickerday** [comment]
Sorry for not providing any context. I was thinking of making it a bigger issue, which is PKGJ having problems with correct parsing of config.txt. You had some spaces, I had some tabs after copying the lines from somewhere - if you don't know what to look for in the hex editor then you're most likely screwed. How do we know there's some weird characters in the file if the app returns 404?
