### ISSUE TITLE
Bug downloading certain games

### ISSUE THREAD

**Issue by GODDUKEMONEXA** [blastrock/pkgj#8]
Salt and Sanctuary doesnt load and Tokyo Tattoo Girls even cant download it stucks at 45% or something, PKGJ needs improvements please thanks for your work

**Comment by richard1222** [comment]
Salt and sanctuary works fine i can't vouch for the second game

**Comment by GODDUKEMONEXA** [comment]
not for me, another user in reddit experience the same infinite load screen after title screen, but it solves installing from nps browser

**Comment by richard1222** [comment]
Glad it worked

**Comment by blastrock** [comment]
Salt and Sanctuary and Tokyo Tattoo Girls work for me with the last version. Reopen if you still have problems.
