### ISSUE TITLE
pkgj v.20 (no items-try to refresh)

### ISSUE THREAD

**Issue by ChrizTaylor** [blastrock/pkgj#82]
Version of firmware: [3.60]
Version of PKGj: [0.20]

## Steps to reproduce the issue

- just updated from v.18 to .20 

Obtained result: [cant load any content, used to worked proper, i have my .txt edited proper]
Expected result: [load as normal]

[just updated to the latest pkgj and now its not working. It used to work proper without any issue, i says that it needs to be refreshed but nothing happens]

**Comment by Ezzyjman007** [comment]
Had the same problem. Press triangle to bring menu.Then press X on refresh. Seems to work now.

**Comment by blastrock** [comment]
Wow, care to send me the core dump, please?

**Comment by ChrizTaylor** [comment]
Hi blackstrock, thanks for your time. Pkgj opens as normal, but it doesnt load anything, like whe  you dont have wifi on, i can browse the tabs for games, dlca, psp,psx  but it doesnt show anything. It keeps saying "No items! Try to refresh."

Other users on reddit told me the same, press triangle several times and it wull shlw the content but After pressing triangle several times the error appears

Where is the core dump located? 

Thanks!

**Comment by blastrock** [comment]
In ux0:data, they are ordered by date, so you can send me the last one.

**Comment by ChrizTaylor** [comment]
Got it, hope it works

https://mega.nz/#!aN5HUZCJ!Dlpa_1VObATOllMbfNKjm-D95raKz_xWJYMMbdxtWlA

**Comment by blastrock** [comment]
Hum, actually I can't do anything with this. Maybe that's fixed for the next release, I should be able to use the core dumps then.

In the meantime, I really can't reproduce this issue.

- When you click on refresh, nothing happens at all? No "Refreshing" appearing on the screen?
- Where is your config? ur0 or ux0?
- Do you have a proxy or some exotic way to connect to the internet from your vita?

**Comment by ChrizTaylor** [comment]
When i click refresh, nothing happens, it "loads" but nothing is shown. 

I have my config in ux0 and i dont use vita2sd, just have a normal 4g vita card

I use the same router i have always used in my house, never had problems before with vita, pkgj (past versions) or any device

**Comment by blastrock** [comment]
What do you mean by it "loads"?

**Comment by ChrizTaylor** [comment]
Here is a video, i recorded it landscape mode, dunno why it uploaded vertically

https://youtu.be/soXRBMXX1MI

**Comment by blastrock** [comment]
The bug your seeing is when you just press X, on the empty list, btw.

**Comment by ChrizTaylor** [comment]
I rebooted the vita, clicked refresh and now its working, weird
