### ISSUE TITLE
Downloads is stuck at random percentage

### ISSUE THREAD

**Issue by benarduino** [blastrock/pkgj#83]
Version of firmware: [3.60 - 10]
Version of PKGj: [0.20]

## Steps to reproduce the issue

- [download any 2gb games and sometimes the download seize and does not show any error code until you cancel it. it is annoying that i have to start the download all over again back to start]

Obtained result: [download pause or stops]
Expected result: [download finish and install]

[please make sure to add all possible details, like the title id (the 9-chars string in the left column) of the game you are talking about]

**Comment by blastrock** [comment]
Are you sure the psvita didn't go to sleep mode while downloading? Also, try to wait 10 minutes or so when the download is stuck, an error may appear.

**Comment by blastrock** [comment]
No answer
