### ISSUE TITLE
VA-11 HALL-A USA

### ISSUE THREAD

**Issue by militaumbro** [blastrock/pkgj#85]
Version of firmware: [3.65 enso]
Version of PKGj: [0.20]

## Problem when installing "VA-11 HALL-A" USA

The japanese version works wonders, but I yet do not fully understand Japanese so I downloaded the USA version and got and the game didn't have an icon when installed. I try to execute it and I get a a "parental control problem", but my Vita doesn't have it set up or anything.

Just donwload the USA game and run it;
I installed the Jap version first.

Obtained result: [not working game]
Expected result: [working game]

game code is :PCSE00756

**Comment by TheRadziu** [comment]
1.01 or so game patch fixed this issue. This issue is not related to pkgj at all, it was game's v1.00 error/bug. 

Please close this issue @blastrock
