### ISSUE TITLE
PKGJ refresh freezing issue

### ISSUE THREAD

**Issue by cvskid** [blastrock/pkgj#87]
Version of firmware: [3.60 henkaku enso]
Version of PKGJ: [0.21]

## Steps to reproduce the issue

- [clicking refresh on any category causes the app to freeze once it gets to a %100 refresh rate]

Obtained result: [pkgj app freezes]
Expected result: [for a gamelist to show up after refreshing]

The config.txt file contains:
url_games http://nopaystation.com/tsv/PSV_GAMES.tsv
url_updates http://nopaystation.com/tsv/PSV_UPDATES.tsv
url_dlcs http://nopaystation.com/tsv/PSV_DLCS.tsv
url_psx_games http://nopaystation.com/tsv/PSX_GAMES.tsv
url_psp_games http://nopaystation.com/tsv/PSP_GAMES.tsv

**Comment by Kojikun1** [comment]
yeah It takes some time to update the cache after 100% just wait .

**Comment by cvskid** [comment]
thank you @blastrock  AND @Kojikun1 for responding, it all good.
