### ISSUE TITLE
thying to change download location to uma0

### ISSUE THREAD

**Issue by jackcbel** [blastrock/pkgj#89]
Version of firmware: 3.60
Version of PKGj: pkgj v.021

hello

i have no clue how to change the download location of my psp/psx games to my uma0 folder

pls some advice

**Comment by TheRadziu** [comment]
`install_psp_psx_location uma0:`

All you needed to do is to check readme.md

**Comment by blastrock** [comment]
Thanks for your help on these issues @TheRadziu :)
