### ISSUE TITLE
download failure: scePromoterUtilityPromoterPkgWithRif failed: 0x80870004

### ISSUE THREAD

**Issue by smallpack** [blastrock/pkgj#92]
Version of firmware: [3.65]
Version of PKGj: [0.21]

- i installed nondprm plugin
- not it into the config in ur0:tai
- delete the folder ux0:tai

everytime when i download a vita game i got an error named 

download failure: scePromoterUtilityPromoterPkgWithRif failed: 0x80870004

**Comment by blastrock** [comment]
You probably didn't install nonpdrm correctly, duplicate of #74
