### ISSUE TITLE
PKG Integrity check failed

### ISSUE THREAD

**Issue by juliosueiras** [blastrock/pkgj#94]
Version of firmware: 3.65 enso
Version of PKGj: 0.21

## Steps to reproduce the issue
- download a game from NPS that has no sha256
- wait for 99% reach
- error pop up for integrity check

Obtained result: game not installed
Expected result: game installed

probably due to the current version of pkgj does not skip sha256 check for game that does not have it

**Comment by blastrock** [comment]
@TheRadziu I meant to ask this before but why are there games with a download link but no sha256? sha256 are just filled-in by downloading the file on a computer and hashing it, no?

**Comment by juliosueiras** [comment]
@blastrock because there is a fast method for people like me(require to update 20-40/month games) that can skip all download process and grab the zrif, so there is no download happening, which also mean no file for sha256 to create from

**Comment by juliosueiras** [comment]
there is also only one person that does the batch file size and sha calculation every now and then

**Comment by blastrock** [comment]
Hmm ok I see, thanks for the explanation
