### ISSUE TITLE
Can´t get list 0x80436003

### ISSUE THREAD

**Issue by Geramr** [blastrock/pkgj#95]
Version of firmware: [3.65]
Version of PKGj: [0.21]

## Steps to reproduce the issue

- I installed pkgj 0.21 for first time
- I refreshed the app as indicates
- I got the error: can´t get list: sceHttpSendrequest failed: 0x80436003

Obtained result: I can´t install anything, the folder only downloaded the db for vita games
Expected result: Download some updates

[please make sure to add all possible details, like the title id (the 9-chars string in the left column) of the game you are talking about]

**Comment by blastrock** [comment]
That's a DNS error (SCE_HTTP_ERROR_RESOLVER_ETIMEDOUT). It only seems to me that you have internet connectivity issues. Does the browser work?

**Comment by blastrock** [comment]
I don't think this is a problem with pkgj, closing this.
