### ISSUE TITLE
Option to see hidden games not supported on the current firm?

### ISSUE THREAD

**Issue by GyaragaX** [blastrock/pkgj#96]
Version of firmware: [3.65]
Version of PKGj: [v0.22]

Could there be an option to unhide games not supported on the current firmware? I'm staying on 3.65, for now, but I liked the convenience of being able to see what was available that required 3.67 & 3.68, without having to go to another device.

**Comment by blastrock** [comment]
I prefer not implementing too many features, and since this can be done with a computer anyway, it's not that necessary.

If more people ask for it, I will think about it.

**Comment by GyaragaX** [comment]
It worked fine in v0.21 and below, the way it displayed what firmware the games required, anyway, without hiding anything. I'm not sure why the change to hiding was necessary. If it could just work like that again, but with the enhancements and bugfixes you've made, that would be good.

There are two ways to go about, one, which, as you said, would require implementing features as a menu option to hide or unhide. The other would be to just keep it like it was, which I was fine with.

I appreciate your work and the improvements you've continued to make. I'd just rather not have what I saw as a feature stripped out. I'd still encourage you to reconsider.

Thanks.

**Comment by blastrock** [comment]
The rationale behind implementing this feature is that:

- it allows nps to remove the [3.61+] tags in the names
- it avoids bug reports from people trying to install games that are not supported on their platform

I know some of the features I add or remove won't be welcomed by the whole community, and it takes more work and more time to please everyone, so sorry for this one but I don't plan on going back. I may add something in the config file if it is asked by more people, as I said.

**Comment by GyaragaX** [comment]
No pressure. It's your project, and your decision. It's open source, and anyone is free to make a fork (pkgk?).

Again, I appreciate your work. Courteous people know what goes into building and maintaining software and don't want to bug you. _I_ don't want to bug you.

I've had [this survey](https://goo.gl/forms/fT1UbqH0BxdlctGX2) up on the relevant subreddit for less than a day, asking people who use pkgj and are on firmware below 3.68 to respond. [The responses are viewable here](https://docs.google.com/forms/d/e/1FAIpQLSec4YediQF5xoAEQozVGetU5AK0WfA9ppNE2xr_8cW__opptQ/viewanalytics).

Just wanted to add that information to your thoughts, as far as more people asking you goes. Most people may not ask directly, or know how, but when presented with the information and queried, the responses do tend to indicate a preference.

Again, up to you. It's your time, and I'm not ungrateful for it. Just wanted to present to you some more voices than my own.

**Comment by blastrock** [comment]
Alright, alright... ^^

I'll think about it. Thank you for taking the time to do that poll :)

**Comment by prashantkamdar** [comment]
I was looking for this exact same thing and noticed GyaragaX had already opened an issue for this.
Whenever possible, I would love to see this feature implemented.
I understand the point of avoidance of unnecessary bug reports, maybe make it so, so that only savvy people are able to switch it on (in hopes that they will not bug report).

I any case, thank you for your work.

**Comment by FuzzyPredator** [comment]
I'm hoping you can implement this feature sooner rather than later, even if it means including a line in the config file to activate the way it was before. I for one will not be updating from v0.21 until this is implemented.

**Comment by TheRadziu** [comment]
Actually, required FW won't be an issue anytime soon, but I'll need to talk to you @blastrock in private (preferably over Discord: https://discord.gg/6Udcx2w , just mention or DM me over Radziu#9094), because it will require you to implement more functionality to allow this.

**Comment by GyaragaX** [comment]
Feel free to close this out. Thanks blastrock. With v0.31, it's all good again, and then some. And thanks to dots_tb, CelesteBlue, and hype man TheRadziu.

**Comment by blastrock** [comment]
Yup, you're welcome
