### ISSUE TITLE
Downloading Errors

### ISSUE THREAD

**Issue by Yuberz** [blastrock/pkgj#97]
Version of firmware: 3.65 + H-encore
Version of PKGj: v0.22

## Steps to reproduce the issue
Download a game. When it finishes, it gives an error.
Obtained result: "Download failure: scePromoterUtilityPromotePkgWithRif failed: 0x80870004" It also downloads the game but does nothing with it? I have to go into vitashell to delete the folder.
Expected result: ?

This happens to what seems like all games to me. I tried 3. (Persona 4 Golden, Deemo: The last recital, and LIMBO)

**Comment by Yuberz** [comment]
I just realized I mistyped the directory in the tai folder. False alarm.

**Comment by squishy519** [comment]
having the same issue. can you share what you did?

**Comment by blastrock** [comment]
I guess I can close this then
