### ISSUE TITLE
DB init error: can't open DB out of memory

### ISSUE THREAD

**Issue by vxbinaca** [blastrock/pkgj#98]
Version of firmware: 3.60
Version of PKGj: v0.22

## Steps to reproduce the issue

- Fresh install of henkaku from factory reset state on PSTV
- Install NoNPDRM from Autoplugin (actually all of the plugins)
- Install PKGj

Obtained result: "DB Initialization error: can't open database: out of memory, try to delete them?"
Expected result: That it would work or give me button input and a option to 'try to delete them?' so it would work.

**Comment by Desolate27** [comment]
Same issue. Any advice?

**Comment by vxbinaca** [comment]
@Desolate27 Follow Skullators video on PKGj, it's the missing config. Do the config for PKGi and you'll be set. Use Skullators config.
