### ISSUE TITLE
Suggestion: Bake in config URLs for script into repo

### ISSUE THREAD

**Issue by vxbinaca** [blastrock/pkgj#99]
All you'd need to do is point the program to look at this repo for the config on first install, it grabs it from the external site and install it. Nice thing is if the domain is shut down you can quickly point people to a new one and set PKGj to re-try for this repo for the new URLs.

This eliminates a step in the setup process and more idiot-proofs it.

**Comment by blastrock** [comment]
I agree with you on the benefits, but I prefer not associating this repository with illegal contents. It was the decision of the previous maintainer too.
